### ISSUE TITLE
CUDA Error: unknown error

### ISSUE THREAD

**Issue by sujithm** [AlexeyAB/darknet#1070]
Hello

I could successfully build darknet, but when it is executed, I just see an error like this.

```
D:\darknet\build\darknet\x64>darknet.exe detector train cfg/obj.data cfg/yolo-obj.cfg darknet19_448.conv.23
CUDA Error: unknown error
CUDA Error: unknown error: No error
```

No further information is shown there and thus I am not able to detect the problem.  However, when I compiled and executed darknet_no_gpu, it works but as expected is very slow.

So I doubt if this issue has any reference with my GPU, but I am not able to trace it out.  Can you please give me some guidance on this?

I use:
MSVS 2015
CUDA 9.1
cuDNN 7.0
OpenCV 3.4.0

Thanks & Regards
Sujith

**Comment by AlexeyAB** [comment]
@sujithm Hello,

* What GPU do you use?
* Can you run this command successfully?
`darknet.exe detector test data/coco.data yolov3.cfg yolov3.weights -i 0 -thresh 0.25 dog.jpg -ext_output`

**Comment by sujithm** [comment]
@AlexeyAB 

Thanks for your quick response.  I am so sorry for posting that silly issue without more checking.  In fact, due to some reasons, my graphics driver was stopped and I updated the driver and then the training process started working smoothly.

Just to update you, I use "NVIDIA GeForce GTX 1060 6GB"

Sorry for wasting your time on this.

Thanks & Regards
Sujith

**Comment by ladykaka007** [comment]
I have the same problem as you.
Can you tell me ,how did you fix it ?
Where can I see that whether my graphics driver is stopped?
Thank U very much!

**Comment by biewenwoaaaa** [comment]
> I have the same problem as you.
> Can you tell me ,how did you fix it ?
> Where can I see that whether my graphics driver is stopped?
> Thank U very much!

Usually, the problem was caused by the insufficient driver version of GPU. You can update the driver of GPU to solve this. Considering we have installed CUDA , we can update the driver by GeForce Experience software manully. In fact, I had downloaded the driver from NVIDIA Home myself, but it cannot be installed and suggested installing by GeForce Experience. 
the way to see whether your graphics driver was stopped is trying running your graphic card manage software on your local machine, if it couldn't be connected, means it stop running.
I hope my experience can help you.
