### ISSUE TITLE
Not able to train with VOC data, get "incorrect value batch=1 for Training!"

### ISSUE THREAD

**Issue by Jped** [AlexeyAB/darknet#1124]
Hi I have followed your tutorial for training with pascal voc data, but when I run the command I get 
"Error: You set incorrect value batch=1 for Training! You should set batch=64 subdivision=64"
any word on why this is happening? 
Here is an image of both my yolov3-voc.cfg and the error. 
![image](https://user-images.githubusercontent.com/5013466/42172086-0195018a-7de9-11e8-86fb-909de7b5a5c9.png)

**Comment by Jped** [comment]
Turns out i was looking at the wrong cfg folder. 
But now it returns a cuda out of memory error, any word on why that would happen? I have an nvidia 1070.

**Comment by AlexeyAB** [comment]
@Jped Hi,

Your GPU doesn't have enough memory.

Increase `subduvisions=` 
If it doesn't help, set `random=0`
If it doesn't help, set `width=288 height=288`

https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> if error Out of memory occurs then in .cfg-file you should increase subdivisions=16, 32 or 64: link

**Comment by Jped** [comment]
That seemed to work. Thank you for your quick response and for this implementation of darknet.
