### ISSUE TITLE
Makefile:127: recipe for target 'darknet' failed

### ISSUE THREAD

**Issue by sainisanjay** [AlexeyAB/darknet#1158]
Anyone has idea whatś the error????
Makefile Setting: 
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=1
```
.../Deeplearning/darknet$ make
g++  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/http_stream.cpp -o obj/http_stream.o
./src/http_stream.cpp: In member function ‘bool MJPGWriter::write(const cv::Mat&)’:
./src/http_stream.cpp:184:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (n < outlen)
           ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/gemm.c -o obj/gemm.o
./src/gemm.c: In function ‘gemm_ongpu’:
./src/gemm.c:310:14: warning: unused variable ‘stream_status’ [-Wunused-variable]
  cudaError_t stream_status = cublasSetStream(handle, get_cuda_stream());
              ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/utils.c -o obj/utils.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/cuda.c -o obj/cuda.o
./src/cuda.c: In function ‘get_cuda_stream’:
./src/cuda.c:75:9: warning: unused variable ‘buffer’ [-Wunused-variable]
    char buffer[256];
         ^
./src/cuda.c: In function ‘cudnn_handle’:
./src/cuda.c:95:17: warning: unused variable ‘status’ [-Wunused-variable]
   cudnnStatus_t status = cudnnSetStream(handle[i], get_cuda_stream());
                 ^
./src/cuda.c: In function ‘blas_handle’:
./src/cuda.c:108:18: warning: unused variable ‘status’ [-Wunused-variable]
   cublasStatus_t status = cublasSetStream(handle[i], get_cuda_stream());
                  ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/convolutional_layer.c -o obj/convolutional_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/list.c -o obj/list.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/image.c -o obj/image.o
./src/image.c: In function ‘draw_detections_cv_v3’:
./src/image.c:476:10: warning: variable ‘rgb’ set but not used [-Wunused-but-set-variable]
    float rgb[3];
          ^
./src/image.c: In function ‘draw_detections_cv’:
./src/image.c:574:10: warning: variable ‘rgb’ set but not used [-Wunused-but-set-variable]
    float rgb[3];
          ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/activations.c -o obj/activations.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/im2col.c -o obj/im2col.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/col2im.c -o obj/col2im.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/blas.c -o obj/blas.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/crop_layer.c -o obj/crop_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/dropout_layer.c -o obj/dropout_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/maxpool_layer.c -o obj/maxpool_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/softmax_layer.c -o obj/softmax_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/data.c -o obj/data.o
./src/data.c: In function ‘load_data_detection’:
./src/data.c:783:30: warning: passing argument 1 of ‘fill_truth_detection’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
         fill_truth_detection(filename, boxes, d.y.vals[i], classes, flip, dx, dy, 1./sx, 1./sy, small_object, w, h);
                              ^
./src/data.c:293:6: note: expected ‘char *’ but argument is of type ‘const char *’
 void fill_truth_detection(char *path, int num_boxes, float *truth, int classes, int flip, float dx, float dy, float sx, float sy,
      ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/matrix.c -o obj/matrix.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/network.c -o obj/network.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/connected_layer.c -o obj/connected_layer.o
./src/connected_layer.c: In function ‘forward_connected_layer_gpu’:
./src/connected_layer.c:279:9: warning: unused variable ‘i’ [-Wunused-variable]
     int i;
         ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/cost_layer.c -o obj/cost_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/parser.c -o obj/parser.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/option_list.c -o obj/option_list.o
./src/option_list.c: In function ‘get_metadata’:
./src/option_list.c:46:13: warning: implicit declaration of function ‘get_labels’ [-Wimplicit-function-declaration]
   m.names = get_labels(name_list);
             ^
./src/option_list.c:46:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   m.names = get_labels(name_list);
           ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/darknet.c -o obj/darknet.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/detection_layer.c -o obj/detection_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/captcha.c -o obj/captcha.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/route_layer.c -o obj/route_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/writing.c -o obj/writing.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/box.c -o obj/box.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/nightmare.c -o obj/nightmare.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/normalization_layer.c -o obj/normalization_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/avgpool_layer.c -o obj/avgpool_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/coco.c -o obj/coco.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/dice.c -o obj/dice.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/yolo.c -o obj/yolo.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/detector.c -o obj/detector.o
./src/detector.c: In function ‘validate_detector_recall’:
./src/detector.c:473:8: warning: unused variable ‘l’ [-Wunused-variable]
  layer l = net.layers[net.n - 1];
        ^
./src/detector.c: In function ‘validate_detector_map’:
./src/detector.c:561:7: warning: variable ‘map’ set but not used [-Wunused-but-set-variable]
  int *map = 0;
       ^
./src/detector.c:554:6: warning: unused variable ‘j’ [-Wunused-variable]
  int j;
      ^
./src/detector.c: In function ‘calc_anchors’:
./src/detector.c:1018:11: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘double’ [-Wformat=]
    printf(" Wrong label: i = %d, box_w = %d, box_h = %d, anchor_w = %d, anchor_h = %d, iou = %f \n",
           ^
./src/detector.c:1018:11: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘double’ [-Wformat=]
./src/detector.c:1018:11: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘double’ [-Wformat=]
./src/detector.c:1018:11: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘double’ [-Wformat=]
./src/detector.c: In function ‘test_detector’:
./src/detector.c:1188:12: warning: passing argument 1 of ‘free_ptrs’ from incompatible pointer type [-Wincompatible-pointer-types]
  free_ptrs(names, net.layers[net.n - 1].classes);
            ^
In file included from ./src/detector.c:4:0:
./src/utils.h:32:18: note: expected ‘void **’ but argument is of type ‘char **’
 YOLODLL_API void free_ptrs(void **ptrs, int n);
                  ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/layer.c -o obj/layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/compare.c -o obj/compare.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/classifier.c -o obj/classifier.o
./src/classifier.c: In function ‘predict_classifier’:
./src/classifier.c:738:9: warning: unused variable ‘size’ [-Wunused-variable]
     int size = net.w;
         ^
./src/classifier.c: In function ‘threat_classifier’:
./src/classifier.c:904:40: warning: passing argument 1 of ‘get_capture_video_stream’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
         cap = get_capture_video_stream(filename);
                                        ^
In file included from ./src/classifier.c:25:0:
./src/http_stream.h:12:12: note: expected ‘char *’ but argument is of type ‘const char *’
 CvCapture* get_capture_video_stream(char *path);
            ^
./src/classifier.c: In function ‘gun_classifier’:
./src/classifier.c:1042:40: warning: passing argument 1 of ‘get_capture_video_stream’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
         cap = get_capture_video_stream(filename);
                                        ^
In file included from ./src/classifier.c:25:0:
./src/http_stream.h:12:12: note: expected ‘char *’ but argument is of type ‘const char *’
 CvCapture* get_capture_video_stream(char *path);
            ^
./src/classifier.c: In function ‘demo_classifier’:
./src/classifier.c:1125:40: warning: passing argument 1 of ‘get_capture_video_stream’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
         cap = get_capture_video_stream(filename);
                                        ^
In file included from ./src/classifier.c:25:0:
./src/http_stream.h:12:12: note: expected ‘char *’ but argument is of type ‘const char *’
 CvCapture* get_capture_video_stream(char *path);
            ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/local_layer.c -o obj/local_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/swag.c -o obj/swag.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/shortcut_layer.c -o obj/shortcut_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/activation_layer.c -o obj/activation_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/rnn_layer.c -o obj/rnn_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/gru_layer.c -o obj/gru_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/rnn.c -o obj/rnn.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/rnn_vid.c -o obj/rnn_vid.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/crnn_layer.c -o obj/crnn_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/demo.c -o obj/demo.o
./src/demo.c: In function ‘fetch_in_thread’:
./src/demo.c:76:10: warning: return makes pointer from integer without a cast [-Wint-conversion]
   return EXIT_FAILURE;
          ^
./src/demo.c: In function ‘demo’:
./src/demo.c:157:34: warning: passing argument 1 of ‘get_capture_video_stream’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   cap = get_capture_video_stream(filename);
                                  ^
In file included from ./src/demo.c:27:0:
./src/http_stream.h:12:12: note: expected ‘char *’ but argument is of type ‘const char *’
 CvCapture* get_capture_video_stream(char *path);
            ^
./src/demo.c:332:12: warning: passing argument 1 of ‘free_ptrs’ from incompatible pointer type [-Wincompatible-pointer-types]
  free_ptrs(names, net.layers[net.n - 1].classes);
            ^
In file included from ./src/demo.c:5:0:
./src/utils.h:32:18: note: expected ‘void **’ but argument is of type ‘char **’
 YOLODLL_API void free_ptrs(void **ptrs, int n);
                  ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/tag.c -o obj/tag.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/cifar.c -o obj/cifar.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/go.c -o obj/go.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/batchnorm_layer.c -o obj/batchnorm_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/art.c -o obj/art.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/region_layer.c -o obj/region_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/reorg_layer.c -o obj/reorg_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/reorg_old_layer.c -o obj/reorg_old_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/super.c -o obj/super.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/voxel.c -o obj/voxel.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/tree.c -o obj/tree.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/yolo_layer.c -o obj/yolo_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/upsample_layer.c -o obj/upsample_layer.o
nvcc  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61]  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC" -c ./src/convolutional_kernels.cu -o obj/convolutional_kernels.o
./src/convolutional_kernels.cu(128): warning: variable "alpha" was declared but never referenced

./src/convolutional_kernels.cu(128): warning: variable "beta" was declared but never referenced

./src/convolutional_kernels.cu(283): warning: variable "alpha" was declared but never referenced

./src/convolutional_kernels.cu(283): warning: variable "beta" was declared but never referenced

./src/convolutional_kernels.cu(128): warning: variable "alpha" was declared but never referenced

./src/convolutional_kernels.cu(128): warning: variable "beta" was declared but never referenced

./src/convolutional_kernels.cu(283): warning: variable "alpha" was declared but never referenced

./src/convolutional_kernels.cu(283): warning: variable "beta" was declared but never referenced

./src/convolutional_kernels.cu(128): warning: variable "alpha" was declared but never referenced

./src/convolutional_kernels.cu(128): warning: variable "beta" was declared but never referenced

./src/convolutional_kernels.cu(283): warning: variable "alpha" was declared but never referenced

./src/convolutional_kernels.cu(283): warning: variable "beta" was declared but never referenced

./src/convolutional_kernels.cu(128): warning: variable "alpha" was declared but never referenced

./src/convolutional_kernels.cu(128): warning: variable "beta" was declared but never referenced

./src/convolutional_kernels.cu(283): warning: variable "alpha" was declared but never referenced

./src/convolutional_kernels.cu(283): warning: variable "beta" was declared but never referenced

./src/convolutional_kernels.cu(128): warning: variable "alpha" was declared but never referenced

./src/convolutional_kernels.cu(128): warning: variable "beta" was declared but never referenced

./src/convolutional_kernels.cu(283): warning: variable "alpha" was declared but never referenced

./src/convolutional_kernels.cu(283): warning: variable "beta" was declared but never referenced

./src/convolutional_kernels.cu(128): warning: variable "alpha" was declared but never referenced

./src/convolutional_kernels.cu(128): warning: variable "beta" was declared but never referenced

./src/convolutional_kernels.cu(283): warning: variable "alpha" was declared but never referenced

./src/convolutional_kernels.cu(283): warning: variable "beta" was declared but never referenced

nvcc  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61]  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC" -c ./src/activation_kernels.cu -o obj/activation_kernels.o
nvcc  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61]  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC" -c ./src/im2col_kernels.cu -o obj/im2col_kernels.o
nvcc  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61]  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC" -c ./src/col2im_kernels.cu -o obj/col2im_kernels.o
nvcc  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61]  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC" -c ./src/blas_kernels.cu -o obj/blas_kernels.o
nvcc  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61]  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC" -c ./src/crop_layer_kernels.cu -o obj/crop_layer_kernels.o
nvcc  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61]  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC" -c ./src/dropout_layer_kernels.cu -o obj/dropout_layer_kernels.o
nvcc  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61]  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC" -c ./src/maxpool_layer_kernels.cu -o obj/maxpool_layer_kernels.o
nvcc  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61]  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC" -c ./src/network_kernels.cu -o obj/network_kernels.o
nvcc  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61]  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN --compiler-options "-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC" -c ./src/avgpool_layer_kernels.cu -o obj/avgpool_layer_kernels.o
g++  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda-8.0/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC obj/http_stream.o obj/gemm.o obj/utils.o obj/cuda.o obj/convolutional_layer.o obj/list.o obj/image.o obj/activations.o obj/im2col.o obj/col2im.o obj/blas.o obj/crop_layer.o obj/dropout_layer.o obj/maxpool_layer.o obj/softmax_layer.o obj/data.o obj/matrix.o obj/network.o obj/connected_layer.o obj/cost_layer.o obj/parser.o obj/option_list.o obj/darknet.o obj/detection_layer.o obj/captcha.o obj/route_layer.o obj/writing.o obj/box.o obj/nightmare.o obj/normalization_layer.o obj/avgpool_layer.o obj/coco.o obj/dice.o obj/yolo.o obj/detector.o obj/layer.o obj/compare.o obj/classifier.o obj/local_layer.o obj/swag.o obj/shortcut_layer.o obj/activation_layer.o obj/rnn_layer.o obj/gru_layer.o obj/rnn.o obj/rnn_vid.o obj/crnn_layer.o obj/demo.o obj/tag.o obj/cifar.o obj/go.o obj/batchnorm_layer.o obj/art.o obj/region_layer.o obj/reorg_layer.o obj/reorg_old_layer.o obj/super.o obj/voxel.o obj/tree.o obj/yolo_layer.o obj/upsample_layer.o obj/convolutional_kernels.o obj/activation_kernels.o obj/im2col_kernels.o obj/col2im_kernels.o obj/blas_kernels.o obj/crop_layer_kernels.o obj/dropout_layer_kernels.o obj/maxpool_layer_kernels.o obj/network_kernels.o obj/avgpool_layer_kernels.o -o darknet -lm -pthread  `pkg-config --libs opencv`  -L/usr/local/cuda-8.0/lib64 -lcuda -lcudart -lcublas -lcurand -L/usr/local/cudnn/lib64 -lcudnn -lstdc++ 
obj/http_stream.o: In function `get_capture_video_stream':
http_stream.cpp:(.text+0x7d): undefined reference to `cv::VideoCapture::VideoCapture(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/http_stream.o: In function `get_webcam_frame':
http_stream.cpp:(.text+0x32b): undefined reference to `cv::Mat::operator _IplImage() const'
obj/http_stream.o: In function `image_data_augmentation':
http_stream.cpp:(.text+0x512): undefined reference to `cv::cvarrToMat(void const*, bool, bool, int)'
http_stream.cpp:(.text+0x670): undefined reference to `vtable for cv::_InputArray'
http_stream.cpp:(.text+0x6fa): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat const&)'
http_stream.cpp:(.text+0x8b0): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
http_stream.cpp:(.text+0x8c3): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
http_stream.cpp:(.text+0x990): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
http_stream.cpp:(.text+0x99b): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
http_stream.cpp:(.text+0x9dd): undefined reference to `cv::split(cv::Mat const&, std::vector<cv::Mat, std::allocator<cv::Mat> >&)'
http_stream.cpp:(.text+0xa16): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
http_stream.cpp:(.text+0xa70): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
http_stream.cpp:(.text+0xb02): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
http_stream.cpp:(.text+0xb09): undefined reference to `vtable for cv::_InputArray'
http_stream.cpp:(.text+0xb53): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
http_stream.cpp:(.text+0xb7b): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
http_stream.cpp:(.text+0xb88): undefined reference to `cv::merge(std::vector<cv::Mat, std::allocator<cv::Mat> > const&, cv::_OutputArray const&)'
http_stream.cpp:(.text+0xb93): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
http_stream.cpp:(.text+0xb9e): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
http_stream.cpp:(.text+0xc56): undefined reference to `cv::Mat::operator _IplImage() const'
http_stream.cpp:(.text+0xe87): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
http_stream.cpp:(.text+0xf1f): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
http_stream.cpp:(.text+0xf2a): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
http_stream.cpp:(.text+0xfd5): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
obj/http_stream.o: In function `send_mjpeg':
http_stream.cpp:(.text+0x12c2): undefined reference to `cv::cvarrToMat(void const*, bool, bool, int)'
http_stream.cpp:(.text+0x1481): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
http_stream.cpp:(.text+0x14d3): undefined reference to `cv::imencode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
collect2: error: ld returned 1 exit status
Makefile:127: recipe for target 'darknet' failed
make: *** [darknet] Error 1

```

**Comment by sainisanjay** [comment]
@AlexeyAB, 
Any idea how to resolve the issue.
Seems, OpenCV 3.4.1 is creating issue. Because without opencv its working fine.

**Comment by sainisanjay** [comment]
Even i have degraded opencv version then also same error. Now opencv version is 
```
>>> import cv2
>>> cv2.__version__
'3.3.1'
>>> 

```

**Comment by nafis00141** [comment]
@sainisanjay i think the opencv you are using is for python.
You need to install opencv for c.
OpenCV 3.4.0: [https://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.4.0/opencv-3.4.0-vc14_vc15.exe/download](https://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.4.0/opencv-3.4.0-vc14_vc15.exe/download)

**Comment by nafis00141** [comment]
follow this video: [https://www.youtube.com/watch?v=jS7To92cnds](https://www.youtube.com/watch?v=jS7To92cnds)
use this file of opencv : [https://github.com/opencv/opencv/archive/3.4.0.zip](https://github.com/opencv/opencv/archive/3.4.0.zip) instead of the github repo specified in the video.

**Comment by AlexeyAB** [comment]
@sainisanjay Use OpenCV 3.4.0 instead of 3.4.1

https://github.com/AlexeyAB/darknet#you-only-look-once-unified-real-time-object-detection-versions-2--3

> This repository supports:
> 
> both Windows and Linux
> **both OpenCV 2.x.x and OpenCV <= 3.4.0 (3.4.1 and higher isn't supported)**
> both cuDNN v5-v7
> CUDA >= 7.5
> also create SO-library on Linux and DLL-library on Windows

**Comment by sainisanjay** [comment]
@AlexeyAB , 
I have install Opencv 3.4.0 but still its giving error, however error is difference then previous.
```
.../darknet$ make
mkdir -p obj
mkdir -p backup
mkdir -p results
g++  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/http_stream.cpp -o obj/http_stream.o
In file included from /usr/local/include/opencv2/core.hpp:59:0,
                 from /usr/local/include/opencv2/opencv.hpp:52,
                 from ./src/http_stream.cpp:46:
/usr/local/include/opencv2/opencv2/core/mat.hpp:58:28: error: invalid use of incomplete type ‘class cv::Mat’
 inline void Mat::initEmpty()
                            ^
compilation terminated due to -Wfatal-errors.
Makefile:133: recipe for target 'obj/http_stream.o' failed
make: *** [obj/http_stream.o] Error 1
```

**Comment by AlexeyAB** [comment]
@sainisanjay Try to change these includes: https://github.com/AlexeyAB/darknet/blob/e301fee8a0d1343824dd8038bc051f728b93bc57/src/http_stream.cpp#L46-L52
as said here: http://answers.opencv.org/question/54308/why-incomplete-type-and-forward-declaration-depending-on-includes/

**Comment by sainisanjay** [comment]
@AlexeyAB  Now i am getting following error??
```
...darkent/make
g++  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -fPIC -c ./src/http_stream.cpp -o obj/http_stream.o
In file included from /usr/local/include/opencv2/core.hpp:52:0,
                 from /usr/local/include/opencv2/opencv.hpp:52,
                 from ./src/http_stream.cpp:46:
/usr/local/include/opencv2/core/cvdef.h:421:4: error: #error "OpenCV 4.x+ requires enabled C++11 support"
 #  error "OpenCV 4.x+ requires enabled C++11 support"
    ^
compilation terminated due to -Wfatal-errors.
Makefile:133: recipe for target 'obj/http_stream.o' failed
make: *** [obj/http_stream.o] Error 1

```

**Comment by AlexeyAB** [comment]
It means, that you still use OpenCV 3.4.1.

Delete your OpenCV installation, and download this one: https://github.com/opencv/opencv/archive/3.4.0.zip

**Comment by sainisanjay** [comment]
@AlexeyAB ,
No, I am using OpenCV 3.4.0
```
sanjay@sanjay:~$ pkg-config --modversion opencv
3.4.0

```

**Comment by AlexeyAB** [comment]
@sainisanjay 
Try to use 3.3.0: https://github.com/opencv/opencv/archive/3.3.0.zip

**Comment by sainisanjay** [comment]
Thanks @AlexeyAB  OpenCV 3.3.0 works for me.

**Comment by uday60** [comment]
@AlexeyAB I am facing the same issue in opencv 3.4.0 
Have we changed anything recently in the makefile because earlier it was working perfectly with 3.4.0 ?

**Comment by sainisanjay** [comment]
@uday60, 
Exactly, for me also it was working absolutely fine few days back on OpenCV 3.4.0. But after some changes in the project directory on 4th July(by @AlexeyAB ), it stopped working with OpenCV 3.4.0. Finally i end-up with degrading OpenCV version to 3.3.0.

**Comment by AlexeyAB** [comment]
@uday60 @sainisanjay 

Can you successfully compile this version of Darknet with OpenCV 3.4.0? 
* Jun 30, 2018  https://github.com/AlexeyAB/darknet/archive/1e9d1fcedf1a361bcdb384f15b5b14bdb526576d.zip

* or Jun 1, 2018 https://github.com/AlexeyAB/darknet/archive/ba70801e982ada241ced55bedad2a411da1896c4.zip

May be OpenCV 3.4.0 was changed (added C API bug), not Darknet.

**Comment by JasOlean** [comment]
So, I would like to ask about opencv version. For your darknet, Opencv 3.4.0 is ok. Right?
In my case, I am using opencv3.4.3. I got the error like that. That is why I need to change to 3.4.0 version. But I still need to use this 3.4.3 version in my other experiment. In this situation, how can I use both version in my case?
