### ISSUE TITLE
Training Error: CUDA Error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by JakupGuven** [AlexeyAB/darknet#1264]
I'm training Yolov2-tiny on the COCO dataset and I've added some classes of my own to the dataset and have changed all the configuration accordingly.

First I add 5 classes with and relevant data to my dataset, change configuration and train a new model without any issues.
Then I decide to add 6 more classes (91) and add relevant data, change configuration and try to train a new model but I'm getting strange illegal memory access errors as well as unspecified launch error.

I decide to revert to my previous dataset and configuration setup which I know has worked before but I'm still getting the same error. Sometimes it manages to train for a few iterations before crash but it mostly crashes immediately. 

I'm attaching my cfg 

`C:\Users\IZ\Desktop\myesteemebackend\darknet-master\build\darknet\x64>darknet.exe detector train cfg/MyEsteeme.DATA cfg/yolov2-tiny.cfg yolov2-tiny.conv.13                                                                                                                                                                  yolov2-tiny                                                                                                                                                                                                                                                                                                                  layer     filters    size              input                output                                                                                                                                                                                                                                                               0 conv     16  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  16                                                                                                                                                                                                                                                            1 max          2 x 2 / 2   416 x 416 x  16   ->   208 x 208 x  16                                                                                                                                                                                                                                                            2 conv     32  3 x 3 / 1   208 x 208 x  16   ->   208 x 208 x  32                                                                                                                                                                                                                                                            3 max          2 x 2 / 2   208 x 208 x  32   ->   104 x 104 x  32                                                                                                                                                                                                                                                            4 conv     64  3 x 3 / 1   104 x 104 x  32   ->   104 x 104 x  64                                                                                                                                                                                                                                                            5 max          2 x 2 / 2   104 x 104 x  64   ->    52 x  52 x  64                                                                                                                                                                                                                                                            6 conv    128  3 x 3 / 1    52 x  52 x  64   ->    52 x  52 x 128                                                                                                                                                                                                                                                            7 max          2 x 2 / 2    52 x  52 x 128   ->    26 x  26 x 128                                                                                                                                                                                                                                                            8 conv    256  3 x 3 / 1    26 x  26 x 128   ->    26 x  26 x 256                                                                                                                                                                                                                                                            9 max          2 x 2 / 2    26 x  26 x 256   ->    13 x  13 x 256                                                                                                                                                                                                                                                           10 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512                                                                                                                                                                                                                                                           11 max          2 x 2 / 1    13 x  13 x 512   ->    13 x  13 x 512                                                                                                                                                                                                                                                           12 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024                                                                                                                                                                                                                                                           13 conv    512  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x 512                                                                                                                                                                                                                                                           14 conv    460  1 x 1 / 1    13 x  13 x 512   ->    13 x  13 x 460                                                                                                                                                                                                                                                           15 detection                                                                                                                                                                                                                                                                                                              mask_scale: Using default '1.000000'                                                                                                                                                                                                                                                                                         Loading weights from yolov2-tiny.conv.13...                                                                                                                                                                                                                                                                                   seen 32                                                                                                                                                                                                                                                                                                                     Done!                                                                                                                                                                                                                                                                                                                        Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005                                                                                                                                                                                                                                                                            If error occurs - run training with flag: -dont_show                                                                                                                                                                                                                                                                        Resizing                                                                                                                                                                                                                                                                                                                     608                                                                                                                                                                                                                                                                                                                           try to allocate workspace = 8388608 * sizeof(float),  CUDA allocate done!                                                                                                                                                                                                                                                   Loaded: 0.000998 seconds                                                                                                                                                                                                                                                                                                     CUDA Error: an illegal memory access was encountered                                                                                                                                                                                                                                                                         CUDA Error: an illegal memory access was encountered: No error `

[yolov2-tiny.cfg.txt](https://github.com/AlexeyAB/darknet/files/2222447/yolov2-tiny.cfg.txt)

**Comment by JakupGuven** [comment]
Got blue screens Video Scheduler Internal Error. Reinstalled NVIDIA Drivers, CUDA, CUDNN and Darknet and that solved the problem.
