### ISSUE TITLE
failed to train on 3 gpus

### ISSUE THREAD

**Issue by erikguo** [AlexeyAB/darknet#1404]
@AlexeyAB ,  

We are training yolov3 on a machine with 3 gtx 1080ti 11G.

We have a problem when starting the training as the following:
1.  In the yolov3 cfg, we set up batch = 64, subdivision=32, width=1024, height=704
2. The training will consume 8.5G video memory on each card. But when we start the training with all 3 1080ti (-gpus 0,1,2),   it always succeeds to allocate 8.5G on each two cards, and fails to allocate enough memory on the third card (CUDA error: Out of memory).   
3. If we change the subdivision = 64, then the training can start successfully. (Only consume 4.6G on each card)

We are so confused. Is there some restricts in your program on training 3 gpus?  

Thank you for your help.

**Comment by erikguo** [comment]
@AlexeyAB ，

Sorry, we found the reason and solved the problem.  It's because the system memory + virtual memory  is lower than 44G.  According to our yolov3 cfg, the training need about 17G (2 x 8.5G) for each GPU.  So 17G x 3 = 51G > 44G

FYI.
