### ISSUE TITLE
different results between gpu version and cpu version

### ISSUE THREAD

**Issue by Carloqiang** [AlexeyAB/darknet#1565]
hi,AlexeyAB, your project helps me a lot,  really appreciate,I have a question, When I use " Detector::detect(image_t img, float thresh, bool use_mean)" to process a series images, there are big difference in CPU version and GPU version. CPU version is correct, and  it seems someing wrong in GPU version。the code like below:
        
           init() 
           while(1)
           {
              image=imread("...");
              detect(image,......);
            }
  And when I use GPU version to run these images one by one,the results are correct and different with the continue run

**Comment by AlexeyAB** [comment]
@Carloqiang Hi,

> And when I use GPU version to run these images one by one,the results are **correct** and **different** with the continue run

* Do you mean that only result for the first image is correct, but for results for the subsequent images  are not correct?

* What model do you use? Try to use the default model yolov3.cfg/weights.

* Do you get wrong result if you use `./darknet detector test cfg/coco.names cfg/yolov3.cfg yolov3.weights` and then enter images one by one?

* Do you get wrong result if you use `./uselib data/coco.names cfg/yolov3.cfg yolov3.weights` and then enter images one by one?

* What params do you use in the Makefile for GPU and for CPU?

* Can you show me some several screenshots with different results?

**Comment by Carloqiang** [comment]
sorry ,I find the issue related with OPENMP, when OPENMP=1, the result is not correct ,both in CPU and GPU version。
I test on the Linux and Windows. In linux ,some results are not correct, but in Windows Release ,the results are correct, but in Windows Debug the  crash happen

**Comment by AlexeyAB** [comment]
@Carloqiang Do you mean that on Linux for OPENMP=1 on GPU result is incorrect, but for OPENMP=0 on GPU result is correct?
OPENMP shouldn't affect on Yolo on GPU.

**Comment by Carloqiang** [comment]
Hi,AlexeyAB:
    I think I find the OPENMP bug. In gemm.c: line 1127:  int c,w,h; 
I think param 'w' and 'h' should define after  ' #pragma omp parallel for' . Because 'w','h' should be shared in different threads.

**Comment by AlexeyAB** [comment]
@Carloqiang 
In the current version there is no `#pragme omp ...` in these lines
https://github.com/AlexeyAB/darknet/blob/57e878b4f9512cf9995ff6b5cd6e0d7dc1da9eaf/src/gemm.c#L1035
https://github.com/AlexeyAB/darknet/blob/57e878b4f9512cf9995ff6b5cd6e0d7dc1da9eaf/src/gemm.c#L1127

What version of Darknet do you use?

What function are you talking about?

There are no `w, h` variables in the `gemm_nn()` and `gemm_cpu()` functions at all: https://github.com/AlexeyAB/darknet/blob/57e878b4f9512cf9995ff6b5cd6e0d7dc1da9eaf/src/gemm.c#L559-L614

https://github.com/AlexeyAB/darknet/blob/57e878b4f9512cf9995ff6b5cd6e0d7dc1da9eaf/src/gemm.c#L2026-L2054

**Comment by Carloqiang** [comment]
In function ‘im2col_cpu_custom’， line 1033: "int c, h, w;" .  Value 'h' and 'w' should be defined after '#pragma omp parallel for'. Change line 1033 to "int c;" . Insert "int h,w;" between 1042 and 1043.

Because 'w','h' should be shared in different threads.You can debug the issue use "yolov3-tiny.cfg and yolov3-tiny.weights and dog.jpg",and the value 'im_row' in line  1152 can equal '-1' ,out of image index.,because the shared value w and h may be changed in other threads. Please check ,thank you

**Comment by AlexeyAB** [comment]
@Carloqiang Yes, that's right, I fixed it. Thank you.
