### ISSUE TITLE
Different results between GPU-mode and CPU-mode

### ISSUE THREAD

**Issue by Carloqiang** [AlexeyAB/darknet#1785]
Hi, I find the results between CPU version and GPU version are different in your latest version . The results are better in CPU version . The cfg file and weights are yolov3-spp.cfg and yolov3-spp.weights.

**Comment by AlexeyAB** [comment]
@Carloqiang Hi,

I fixed it. 
Now results are the same on CPU and GPU for yolov3-spp.cfg.

![image](https://user-images.githubusercontent.com/4096485/47190141-8c509f00-d348-11e8-8a53-c7fa8febc92e.png)
