### ISSUE TITLE
Demo video error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by PumayHui** [AlexeyAB/darknet#1886]
When I run on my linux machine:
`sudo ./darknet detector demo test.data yolov3.cfg yolov3_final.weights test.avi`
It occurs such errors:

 101 yolo
 102 route  98
 103 conv    128  1 x 1 / 1    38 x  38 x 256   ->    38 x  38 x 128 0.095 BF
 104 upsample            2x    38 x  38 x 128   ->    76 x  76 x 128
 105 route  104 36
 106 conv    128  1 x 1 / 1    76 x  76 x 384   ->    76 x  76 x 128 0.568 BF
 107 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256 3.407 BF
 108 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128 0.379 BF
 109 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256 3.407 BF
 110 conv    128  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x 128 0.379 BF
 111 conv    256  3 x 3 / 1    76 x  76 x 128   ->    76 x  76 x 256 3.407 BF
 112 conv     18  1 x 1 / 1    76 x  76 x 256   ->    76 x  76 x  18 0.053 BF
 113 yolo
Total BFLOPS 140.273 
Loading weights from yolov3_final.weights...
 seen 64 
Done!
video file: test.avi
Unable to stop the stream: Invalid argument
 Video-stream stoped! 
Stream closed.
 Video-stream stoped! 
Stream closed.
CUDA Error: invalid argument
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)

ThenI do such works:
1. OpenCV version 3.4.0.
2. I played multiple avi files same error.
3. Use the latest version from GitHub.
4. Do the same change as mentioned in https://github.com/AlexeyAB/darknet/issues/863.
But it still occurs errors. Any solution for this?

**Comment by PumayHui** [comment]
I have re-compiled ffmpeg and OpenCV.
And I ran demo again, then I met such errors:
   83 route  79
   84 conv    256  1 x 1 / 1    14 x  14 x 512   ->    14 x  14 x 256  0.051 BFLOPs
   85 upsample            2x    14 x  14 x 256   ->    28 x  28 x 256
   86 route  85 61
   87 conv    256  1 x 1 / 1    28 x  28 x 768   ->    28 x  28 x 256  0.308 BFLOPs
   88 conv    512  3 x 3 / 1    28 x  28 x 256   ->    28 x  28 x 512  1.850 BFLOPs
   89 conv    256  1 x 1 / 1    28 x  28 x 512   ->    28 x  28 x 256  0.206 BFLOPs
   90 conv    512  3 x 3 / 1    28 x  28 x 256   ->    28 x  28 x 512  1.850 BFLOPs
   91 conv    256  1 x 1 / 1    28 x  28 x 512   ->    28 x  28 x 256  0.206 BFLOPs
   92 conv    512  3 x 3 / 1    28 x  28 x 256   ->    28 x  28 x 512  1.850 BFLOPs
   93 conv     18  1 x 1 / 1    28 x  28 x 512   ->    28 x  28 x  18  0.014 BFLOPs
   94 yolo
   95 route  91
   96 conv    128  1 x 1 / 1    28 x  28 x 256   ->    28 x  28 x 128  0.051 BFLOPs
   97 upsample            2x    28 x  28 x 128   ->    56 x  56 x 128
   98 route  97 36
   99 conv    128  1 x 1 / 1    56 x  56 x 384   ->    56 x  56 x 128  0.308 BFLOPs
  100 conv    256  3 x 3 / 1    56 x  56 x 128   ->    56 x  56 x 256  1.850 BFLOPs
  101 conv    128  1 x 1 / 1    56 x  56 x 256   ->    56 x  56 x 128  0.206 BFLOPs
  102 conv    256  3 x 3 / 1    56 x  56 x 128   ->    56 x  56 x 256  1.850 BFLOPs
  103 conv    128  1 x 1 / 1    56 x  56 x 256   ->    56 x  56 x 128  0.206 BFLOPs
  104 conv    256  3 x 3 / 1    56 x  56 x 128   ->    56 x  56 x 256  1.850 BFLOPs
  105 conv     18  1 x 1 / 1    56 x  56 x 256   ->    56 x  56 x  18  0.029 BFLOPs
  106 yolo
Loading weights from yolov3_final.weights...Done!
video file: test.avi
Segmentation fault (core dumped)

**Comment by Mainvooid** [comment]
@PumayHui 你需要把opencv_ffmpeg340_64.dll放在\build\darknet\x64目录下,要有搜索是否有同类问题的好习惯。
refer to
https://github.com/AlexeyAB/darknet/issues/1832#issuecomment-433965808

**Comment by PumayHui** [comment]
> @PumayHui 你需要把opencv_ffmpeg340_64.dll放在\build\darknet\x64目录下,要有搜索是否有同类问题的好习惯。
> refer to
> [#1832 (comment)](https://github.com/AlexeyAB/darknet/issues/1832#issuecomment-433965808)

@Mainvooid 
请注意“When I run on my linux machine:”，谢谢。

**Comment by PumayHui** [comment]
I have solved this problem by:
1. uninstall all ffmpeg in ubuntu, including "make install" and "apt-get";
2. rebuild opencv version 3.3.1 with opencv_contrib.
