### ISSUE TITLE
Why use LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH? 

### ISSUE THREAD

**Issue by gameon67** [AlexeyAB/darknet#2392]
I'm curious when we want to run the library `darknet.so`, why we have to use `LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH` in `LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./uselib test.mp4` command?

I tried to input the command without `LD_LIBRARY_PATH` like this `./uselib test.mp4` and works fine. But after I re-run the command again it shows error : 
```
 cuDNN status Error in: file: ./src/convolutional_layer.c : () : line: 288 : build time: Feb 13 2019 - 14:39:29 
cuDNN Error: CUDNN_STATUS_BAD_PARAM
cuDNN Error: CUDNN_STATUS_BAD_PARAM: File exists
uselib: ./src/utils.c:277: error: Assertion `0' failed.
Aborted (core dumped)
```
I keep getting error even if I input the command using `LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH` again.

**Comment by AlexeyAB** [comment]
`LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH` - is used just to search `libdarknet.so` library in the same directory where is executable file `./uselib`

Sometimes it is required, sometimes isn't.

----

> But after I re-run the command again it shows error 

* Did you change anything in the source code?

* Can you show screenshot of this error?

* After you have gotten an error, run this commands and show output:
```
nvcc --version
nvidia-smi
```

**Comment by gameon67** [comment]
I didn't change the source code.
My nvidia driver works well also. Anyway the problem gone away after I restart the computer (Still not sure why).
