### ISSUE TITLE
unable to compile opencv from source

### ISSUE THREAD

**Issue by jillelajitta** [AlexeyAB/darknet#2498]
Hi Alexy,

I'm getting error while trying to install opencv from source. Please check the attached screenshot.

Thanks.
![screenshot from 2019-02-28 17-56-26](https://user-images.githubusercontent.com/11436918/53606974-710d6000-3b82-11e9-83c8-c6a5762b6a62.png)

**Comment by gameon67** [comment]
Have you installed cuda?

**Comment by jillelajitta** [comment]
OpenCV is working now @gameon67 but darknet is not detecting my GPU. I have installed everything. I'm able to run tensorflow object detection api successfully on my GPU but darknet is not detecting my gpu. Do you have any idea?

I'm using below script 
./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights -c 0

**Comment by AlexeyAB** [comment]
@jillelajitta 

Did you set
```
GPU=1
CUDNN=1
OPENCV=1
```
Here? https://github.com/AlexeyAB/darknet/blob/master/Makefile#L1-L4

**Comment by jillelajitta** [comment]
@AlexeyAB Yes I did, I realized some problem with OPENCV, I compiled it from source. I tried running yolo and tensorflow object detection API, both are very slow then I pip install opencv 4.0, tensorflow object detection is working perfect.

I tried both OPENCV 3.3 and 3.4 but no luck on yolo. Can you please help me in solving this problem.

I follwed this link http://www.codebind.com/cpp-tutorial/install-opencv-ubuntu-cpp/ for installing OPENCV.

Thank you.

**Comment by AlexeyAB** [comment]
@jillelajitta 

What version of Linux do you use?

Try to install OpenCV by using this command:
`sudo apt-get install libopencv-dev`


----

> both are very slow

OpenCV shouldn't affect on detection speed of Darknet-Yolo on GPU.
I think you just compiled Darknet without GPU supporting.

**Comment by jillelajitta** [comment]
amazing sudo apt-get install libopencv-dev, this is working, but YOLO is utilizing only 10% of my RTX2080TI??

**Comment by AlexeyAB** [comment]
@jillelajitta 

> YOLO is utilizing only 10% of my RTX2080TI??

* Can you show screenshot of GPU-Z?
* What command do you use?
* What params did you set in Makefile?

**Comment by jillelajitta** [comment]
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=1

I used nvidia-smi command.

![gpu](https://user-images.githubusercontent.com/11436918/54763952-e2aa5e00-4bc4-11e9-8073-b67950ef4c0c.png)

**Comment by AlexeyAB** [comment]
* What Darknet command do you use for detection?
* What resolution of video-file do you use?

**Comment by jillelajitta** [comment]
I'm using darknet_video.py file and I'm using 1080p camera, 416x416 in my configuration file.

**Comment by jillelajitta** [comment]
I'm using darknet_video.py file and I'm using 1080p camera, 416x416 in my configuration file. YOLO is not taking more than 1893MiB of my GPU everytime.

**Comment by AlexeyAB** [comment]
@jillelajitta 

`darknet_video.py` is just an example that doesn't use mutli-threading. So you should implement it by yourself in the Python.

Yolo speed depends on GPU-usage rather than GPU-RAM.

**Comment by jillelajitta** [comment]
Sure Thanks. I'm trying to implement multi camera, but I'm unable to achieve more than 3 FPS on my 2 cameras. I have used multi threading too but no luck.


if __name__ == "__main__":
    while True:
        for i in range(2):
            YOLO(i)
