### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by anthonymg1994** [AlexeyAB/darknet#2501]
When execute this command
 darknet.exe detector test data/coco.data cfg/yolov3.cfg yolov3.weights -i 0 -thresh 0.25
 in terminal my result is
CUDA status Error: file: c:\darknet\src\cuda.c : cuda_set_device() : line: 22 : build time: Mar  1 2019 - 20:44:49
CUDA Error: unknown error
CUDA Error: unknown error: No error
and executed another command **nvidia-smi** 
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running. This can also be happening if non-NVIDIA GPU is running as primary display, and NVIDIA GPU is in WDDM mode.

**Comment by jklemmack** [comment]
Similar issue with me. I have a Lenovo Y-series laptop with discrete NVidia GFX960M GPU, along side an integrated Intel driver, running Windows 10.  I was receiving "Unknown Error" from cuda.c line 307.

To resolve, go to Settings -> System -> Display and at the bottom choose "Graphics Settings".  I selected "Classic App", then browsed to and selected the "darknet.exe" file, and forced it to use the GPU. 

Voila - problem solved.
