### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by mervesahar** [AlexeyAB/darknet#2554]
![sdfasd](https://user-images.githubusercontent.com/40631375/53949136-787cbe00-40da-11e9-8760-71deaed49042.JPG)

cuda v10.0

nvidia-smi here: 
![fffff](https://user-images.githubusercontent.com/40631375/53949319-da3d2800-40da-11e9-9f82-d2f113f0f9fe.JPG)

**Comment by yxwLearn** [comment]
@mervesahar
what's you cuda version?

**Comment by mervesahar** [comment]
> @mervesahar
> what's you cuda version?

This error with cuda v10.0         
and i can't build project with v9.0

**Comment by yxwLearn** [comment]
@mervesahar 
can you use the cmd show the cuda version by command "nvcc -V"?

**Comment by duohappy** [comment]
@mervesahar hi, try to update your gpu driver, version `385.54` is too old

**Comment by mervesahar** [comment]
@yxwLearn @duohappy  thanks for your comment.
Problem solved that build with cuda9.0
