### ISSUE TITLE
CUDA errors when buikding darknet.sln

### ISSUE THREAD

**Issue by hadi-ghnd** [AlexeyAB/darknet#2624]
I am trying to build **darknet.sln** with:

- openCV 3.4.0 (built with cuda 9.1)
- CUDA 9.1
- cudnn

but I get these errors:

![Untitled](https://user-images.githubusercontent.com/24352869/54476456-1572e180-47d4-11e9-90eb-550abc1a83d7.png)

I tried this with another openCV (**opencv-3.4.0-vc14_vc15**) that is not compiled with CUDA, and I the program works. Is it possible to make it work with the first OpenCV or should I just use the non-CUDA OpenCV?

**Comment by AlexeyAB** [comment]
@hadi-ghnd Hi,

Try to compile Darknet by using Cmake to use it with OpenCV[cuda]

**Comment by VonSdite** [comment]
I got the same problem. 
I found **one** error in `cudaarithm.hpp` is the macro definition of `min`.
![image](https://user-images.githubusercontent.com/25704948/54484349-ad89cd00-489f-11e9-8630-0c70ca91c39e.png)

So I add `NOMINMAX` in `darknet property` => `C/C++` => `Preprocessor`
![image](https://user-images.githubusercontent.com/25704948/54484362-2ee15f80-48a0-11e9-9700-75cf23c38a68.png)

And rebuild the project. Finally I solved it by this.

@hadi-ghnd

**Comment by hadi-ghnd** [comment]
@VonSdite Thank you for your solution. It worked well.
