### ISSUE TITLE
CUDA status Error: file: ..\..\src\dark_cuda.c 

### ISSUE THREAD

**Issue by abdou31** [AlexeyAB/darknet#2691]
I just encountred this error :
Demo
CUDA status Error: file: ....\src\dark_cuda.c : get_gpu_compute_capability() : line: 335 : build time: Mar 20 2019 - 15:18:40
CUDA Error: unknown error
when i run this command line below:

> darknet.exe detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights

Can you explain the source of the error and how to solve it?
Thanks

**Comment by AlexeyAB** [comment]
Did you compile by using Make or Cmake?
What params did you use in the `Makefile`?
What versions of CUDA and cuDNN do you use?
Can you show output of commands?
```
nvcc --version
nvidia-smi
```

**Comment by abdou31** [comment]
I didn't do compile beacause Make doesn't work , i had tried to use MinGw64 , but it show some error...
I compile the solution darknet.sln using visual studio 2017 with option generation
For the version , i use 
+CUDA 10.0 ( Nvidia Corporation )
+cudnn 7.4.2.24
When i execute commands i get those output:
for nvcc --version : 

> nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130

and for nvidia-smi i get:
> nvidia-smi is not recognized as an internal or external command operable program or batch file

**Comment by AlexeyAB** [comment]
What GPU do you use?

**Comment by abdou31** [comment]
I had two graphic card : 
+ Nvidia Geforce 840m
+ Intel HD graphic

**Comment by AlexeyAB** [comment]
Try to reinstall GPU Driver.
If it doesn't help - try to reinstall CUDA.

**Comment by abdou31** [comment]
okey , 
just i want to tell you that when i change 'demo' by 'train' in the command line , it work but it show in the last line that could not open data/coco/coco.data

**Comment by AlexeyAB** [comment]
Also can you rename this file to cmd-file, run it and show screenshot
[nvidia-smi.cmd.txt](https://github.com/AlexeyAB/darknet/files/2994281/nvidia-smi.cmd.txt)

**Comment by abdou31** [comment]
> Fri Mar 22 00:08:12 2019
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 418.96       Driver Version: 418.96       CUDA Version: 10.1     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce 840M       WDDM  | 00000000:03:00.0 Off |                  N/A |
> | N/A   32C    P8    N/A /  N/A |     40MiB /  4096MiB |    ERR!      Default |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+

**Comment by abdou31** [comment]
the problem is changed to : 

> CUDA status Error: file: ..\..\src\dark_cuda.c : cuda_set_device() : line: 32 : build time: Mar 22 2019 - 15:55:12
CUDA Error: unknown error

CUDA Error: unknown error: No error

**Comment by AlexeyAB** [comment]
@abdou31 Can you run any other CUDA application successfully, for examle, can you open Tab "Performance" in CUDA-Z programm? http://cuda-z.sourceforge.net/

**Comment by abdou31** [comment]
yes i download CUDA-Z program , tab Performance show this : 
https://i.imgur.com/2IdWqEH.png

**Comment by AlexeyAB** [comment]
@abdou31 
This is very strange.

1. Try to copy `cudnn64_7.dll` `cudart64_100.dll` `cublas64_100.dll` `curand64_100.dll` from `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin` to the folder where is `darknet\build\darknet\x64\darknet.exe`

2. If it doesn't help - then try to download the latest version of Darknet, and try to compile it again.

3. If it doesn't help, then try to compile Darknet by using Cmake.
* Rename this file to cmd-file and run it [run_cmake.cmd.txt](https://github.com/AlexeyAB/darknet/files/2997768/run_cmake.cmd.txt)
* press `Configure` -> Optional Platform for generator `x64` -> Finish -> Generate -> Open Project -> Set x64 & Release at the top of MSVS -> Build -> Build ALL

And copy all result files from `darknet\Release` to `darknet\build\darknet\x64`

![image](https://user-images.githubusercontent.com/4096485/54844494-1f22aa80-4ce8-11e9-85c7-bd7f50a78ea7.png)

**Comment by abdou31** [comment]
I don't have cudnn64_7.dll in the folder bin of Nvidia Corporation Toolkit

**Comment by abdou31** [comment]
I get those error in Cmake:

> CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:99 (message):
  Could not find toolchain file: /scripts/buildsystems/vcpkg.cmake
Call Stack (most recent call first):
  CMakeLists.txt:14 (project)


Configuring incomplete, errors occurred!

**Comment by AlexeyAB** [comment]
> I don't have cudnn64_7.dll in the folder bin of Nvidia Corporation Toolkit,

Get it from cuDNN folder or archive.


> I get those error in Cmake:
> 
> CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:99 (message):
> Could not find toolchain file: /scripts/buildsystems/vcpkg.cmake
> Call Stack (most recent call first):
> CMakeLists.txt:14 (project)
> 
> Configuring incomplete, errors occurred!


Did you run this file? https://github.com/AlexeyAB/darknet/files/2997768/run_cmake.cmd.txt

Did you install VCPKG?

**Comment by abdou31** [comment]
I run this file , but i didn't install vcpkg beacause the installation is not mentionned that is required to test darknet.exe, but i will do the installation now in visual studio 2017

**Comment by abdou31** [comment]
I build with CMAKE but i get somme errors
[https://i.imgur.com/3ryfNtV.png](url)

**Comment by AlexeyAB** [comment]
> I build with CMAKE but i get somme errors
> https://i.imgur.com/3ryfNtV.png

This isn't error, this is just info-message. All is OK.
You can continue to build Darknet as I described. https://github.com/AlexeyAB/darknet/issues/2691#issuecomment-475728768

**Comment by abdou31** [comment]
but i didnt get folder named release

**Comment by AlexeyAB** [comment]
1. Can you show screenshot of MSVS after that your press ` Open Project ` button in Cmake-gui?

2. Also can you show screenshot in MSVS -> (right click on) darknet -> General

**Comment by abdou31** [comment]
I think that it worked right now,
Thank you , you are awsome 
I didn't have any words .
you save my life my friend

**Comment by AlexeyAB** [comment]
Does this command work successfully?
`darknet.exe detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights test.mp4`

**Comment by abdou31** [comment]
when i run this command i get this error : 
https://i.imgur.com/cSJOAZi.png
But for the previous command , the webcam opened and it detect object ( work perfectly )
Also when i use test instead demo , it work perfectly with picture

**Comment by AlexeyAB** [comment]
Just copy `opencv_ffmpeg340_64.dll` from your OpenCV directory `C:\opencv_3.0\opencv\build\bin` to the darknet.exe directory

**Comment by abdou31** [comment]
i do this , 
the same issue persist

**Comment by AlexeyAB** [comment]
Do you have file `test.mp4`? Just use any mp4 or avi file that you have instead of `test.mp4`

**Comment by abdou31** [comment]
Thanks , it work perfectly

**Comment by abdou31** [comment]
when i used train instead demo, i get this:


 Error: You set incorrect value batch=1 for Training! You should set batch=64 subdivision=64

**Comment by AlexeyAB** [comment]
So do what is written, set batch=64 subdivisions=64 in you cfg-file.
And read: https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

**Comment by abdou31** [comment]
I get this error when i change this:
CUDA status Error: file: C:\Users\Abdou\darknet\src\dark_cuda.c : cuda_make_array() : line: 231 : build time: Mar 22 2019 - 22:08:26
CUDA Error: out of memory

**Comment by AlexeyAB** [comment]
You didn't set subivisions=64

**Comment by abdou31** [comment]
I set it and i get this error:
https://i.imgur.com/cLyW1au.png

**Comment by AlexeyAB** [comment]
Read `Training YOLO on COCO` https://pjreddie.com/darknet/yolo/

**Comment by abdou31** [comment]
I download all training , but when i execute python voc_label.py , i get this error:

> IOError: [Errno 2] No such file or directory: 'VOCdevkit/VOC2012/ImageSets/Main/train.txt'

**Comment by abdou31** [comment]
Good morning , it works fine , but i have one problem when i trying train that average loss ( do not answer )
i didn't know the reason , My gpu works fine 
When did i get the graph ? after how much iteration?
https://i.imgur.com/G7AQlD5.png

**Comment by abdou31** [comment]
I didn't know what is mean showing there , i talking about ( -nan(ind))
https://i.imgur.com/IFBCFo7.png

**Comment by stuhk** [comment]
你好，最初的问题是因为没有设置环境变量的原因 把C:\Program Files\NVIDIA Corporation\NVSMI加入环境变量就没问题了

**Comment by ycchanau** [comment]
> 你好，最初的问题是因为没有设置环境变量的原因 把C:\Program Files\NVIDIA Corporation\NVSMI加入环境变量就没问题了

老哥 我也遇到這個問題 設置環境變量後也不行啊

**Comment by liupailife** [comment]
> > 你好，最初的问题是因为没有设置环境变量的原因 把C:\Program Files\NVIDIA Corporation\NVSMI加入环境变量就没问题了
> 
> 老哥 我也遇到這個問題 設置環境變量後也不行啊

我也是···，请问您现在解决了吗

**Comment by vasanth4224** [comment]
CUDA status Error: file: /media/a/2TB/darknet-master/src/dark_cuda.c : () : line: 39 : build time: Nov  5 2020 - 11:26:35 

 CUDA Error: unknown error
CUDA Error: unknown error: Bad file descriptor


Hi... I got same error in ubuntu 20.04.    Several times I reinstalled cuda but its remains same.
Anyone can solve this issue?

**Comment by Malithi-gif** [comment]
PS C:\darknet> ./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg
CUDA status Error: file: C:\darknet\src\dark_cuda.c : cuda_set_device() : line: 39 : build time: Nov 17 2020 - 18:52:29

Can anyone help to fix this?

I haven't GPU
I used CUDA 10.1

**Comment by andrewssobral** [comment]
Hello guys,
I also have the following issue:
```
~/darknet$ ./darknet detector train ./rotaeng/obj.data ./rotaeng/yolov4-tiny-custom-rotaeng.cfg ./models/yolov4-tiny.conv.29 -clear 2>&1 | tee ./rotaeng/train_log.txt
Darknet error location: /home/proactive/darknet/src/dark_cuda.c, check_error, line #70
CUDA Error: unknown error: Bad file descriptor
CUDA status Error: file: /home/proactive/darknet/src/dark_cuda.c : () : line: 39 : build time: Aug 18 2021 - 15:37:56 

 CUDA Error: unknown error
```
How can I solve it? I din't find a good answer in this thread.

**Comment by andrewssobral** [comment]
Problem seems to be gone after rebooting my computer...crazy...
