### ISSUE TITLE
Cuda error when increase resolution

### ISSUE THREAD

**Issue by Bigoudom** [AlexeyAB/darknet#2761]
Hi,

I want to look for the effect of resolution on training. 
My original images were 416 * 416 and I first launched a training with height and width = 224.
I do no encountered any problem.
I then try with height and width = 318 and I get the following `error:`

`darknet : ./src/cuda.c : 36 : Assertion "0" failed.`

As you proposed in the issue #712 (https://github.com/AlexeyAB/darknet/issues/712), I replaced random=1 with random=0 in each [yolo] layer. And this works!

However, when I changed height and width to 416 (still with random = 0  in each [yolo] layer), I get the following error:
`CUDA Error: out of memory: File exists
darknet: ./src/utils.c:293: error: Assertion `0' failed.
Aborted (core dumped)`

Has someone an idea that may explain or resolve this issue?
Below is my hardware configuration.
Many thanks!

System information

    Operating system: Ubuntu 18.04 Bionic Beaver (64bits)
    Compiler version: gcc/g++ 6.5.0 / cmake 3.10.2
    CUDA version: 9.0
    cuDNN version: 7.1
    OpenCV : 3.2.0
    NVIDIA driver version: 390.116
    GPU models: GeForce GTX 1080
    CPU : Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz

**Comment by Bigoudom** [comment]
I forget to precise this:
I use Yolo-v3 (last update), train on 23760 images and 42 classes (I modified the cfg file as explained in https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects).

**Comment by drapado** [comment]
It's seems that you are running out of memory while training? If you have a low value in subdivisions (yolov3.cfg file) like 4,8 or 16 try to change it to 32 or 64 and see what happens

**Comment by Bigoudom** [comment]
@drapado
I try with subdivisions = 64 and it works, thank you for your help!
