### ISSUE TITLE
cuDNN Error: CUDNN_STATUS_BAD_PARAM: File exists

### ISSUE THREAD

**Issue by MateuszKlimas** [AlexeyAB/darknet#2791]
When I try to run 
`./darknet detector demo data/coco.data cfg/yolov3-person.cfg yolov3-person_3200.weights config/test1.mp4 -out_filename res.avi`

I got the following error: 
 cuDNN status Error in: file: ./src/convolutional_layer.c : () : line: 295 : build time: Apr  1 2019 - 08:03:43 
cuDNN Error: CUDNN_STATUS_BAD_PARAM
cuDNN Error: CUDNN_STATUS_BAD_PARAM: File exists
darknet: ./src/utils.c:293: error: Assertion `0' failed.
Aborted (core dumped)

I have been working working with darknet on Windows and everything worked finde, but now that I have moved to Ubuntu I got this problem. Any idea?

**Comment by AlexeyAB** [comment]
Try to use another version of cuDNN.

What GPU, CUDA and cuDNN do you use?

**Comment by MateuszKlimas** [comment]
The GPU is a K80, using CUDA 10.0.130 and cuDNN 7.5.0

> Try to use another version of cuDNN.
> 
> What GPU, CUDA and cuDNN do you use?

The GPU is a K80, using CUDA 10.0.130 and cuDNN 7.5.0

**Comment by MateuszKlimas** [comment]
> Try to use another version of cuDNN.
> 
> What GPU, CUDA and cuDNN do you use?

The GPU is a K80, using CUDA 10.0.130 and cuDNN 7.5.0. Disabling cuDNN works, but it gets worst performance. Should I downgrade the version?

**Comment by AlexeyAB** [comment]
> Should I downgrade the version?

Yes, try to downgrade cuDNN.

Or try to downgrade CUDA & cuDNN: to CUDA 9.0 and cuDNN for CUDA 9.0.

**Comment by MateuszKlimas** [comment]
Just downgraded the version and now it works, but still have one problem. When I run the detector on a video on my computer I got an average of 28FPS using a GTX1080, but now I'm doing it on the cloud, and it's averaging 10FPS with a K80. I'm using Xvfb :1 & to simulate a desktop on the VM, but I'm not sure if this related with the low rate of FPS. Any idea?

**Comment by AlexeyAB** [comment]
@MateuszKlimas 

K80 cointains 2 GPUs chips. For detection on one video-stream the Yolo can use only 1 GPU chip. So single chip on K80 is ~2x slower than GTX 1080. So it is normal to have 10 FPS.

**Comment by MateuszKlimas** [comment]
Alright, that makes sense. Thank you for the help!
