### ISSUE TITLE
How to accelerate training speed?

### ISSUE THREAD

**Issue by toplinuxsir** [AlexeyAB/darknet#2876]
How to accelerate training speed? 
If I use multi GPU,such as up to 4 gpus ,The speed is 4x faster than before ?
Thanks

**Comment by DarylWM** [comment]
On my data I've seen a 1.9x training speed improvement by using two GTX1070s rather than one.

**Comment by AlexeyAB** [comment]
Also increasing `subdivisions=` with keeping the same `batch=64` can accelerate training, but very high `subdivisions` causes CUDA out of memory error.

**Comment by toplinuxsir** [comment]
@AlexeyAB  Thanks!

**Comment by xiaohai12** [comment]
> @toplinuxsir @DarylWM
> 
> Also increasing `subdivisions=` with keeping the same `batch=64` can accelerate training, but very high `subdivisions` causes CUDA out of memory error.

sorry, if I understand correctly, low subdivisions value with causes OOM error rather than high subdivisions value? and also for the speed?

**Comment by AlexeyAB** [comment]
@xiaohai12 Sure, I fixed it.

Lowering `subdivisions=` with keeping the same `batch=64` can accelerate training, but very low `subdivisions` causes CUDA out of memory error.
