### ISSUE TITLE
Cuda errors

### ISSUE THREAD

**Issue by sealedtx** [AlexeyAB/darknet#3129]
I have few detectors running on my system Ubuntu 18.04, nvidia 1080ti, and from time to time one detector (the biggest network i have - yolov3) stops with cuda errors:

CUDA Error Prev: an illegal memory access was encountered
python3: : Unknown error -493295724

or

cuDNN status Error in: file: ./src/convolutional_kernels.cu : () : line: 544 : build time: Mar  6 2019 - 11:12:11
cuDNN Error: CUDNN_STATUS_EXECUTION_FAILED
Unknown error -1141889204

or

CUDA status Error: file: ./src/blas_kernels.cu : () : line: 459 : build time: Mar  6 2019 - 11:12:11
CUDA Error: misaligned address
python3: : Unknown error -1621145749

each time different erorrs.
Here is my nvidia-smi:
![Screenshot from 2019-05-10 10-49-03](https://user-images.githubusercontent.com/11164874/57511248-7ff65880-7311-11e9-996c-ccd90883f4b4.png)

As you can see I have still some free GPU memory, and I don't know why this detector fails. If you have ideas, please help ;)

**Comment by sealedtx** [comment]
@AlexeyAB Hi! Recently I have found what causes these errors. The problem was that I had few threads which had same darknet network instance and in moments when they access it simultaneously these errors appear.
Problem - simultaneous memory access.
Solution - single queue for network inference tasks from different threads
