### ISSUE TITLE
Starting from commit 038289e I get "Assertion `0' failed."

### ISSUE THREAD

**Issue by Yagger** [AlexeyAB/darknet#3259]
Starting from commit
https://github.com/AlexeyAB/darknet/commit/038289eb7d337047074565e159166ebf74badd4e I get the following error, when running train command.
```
CUDA Error Prev: an illegal memory access was encountered
CUDA Error Prev: an illegal memory access was encountered: File exists
darknet: ./src/utils.c:293: error: Assertion `0' failed.
```

If I checkout to the commit right before 038289e, then it works as expected. The error remains in the latest (to this moment) commit on the branch, which is 55dcd1b.

**Comment by AlexeyAB** [comment]
@Yagger Hi,

Can you show screenshot of this error with previous lines?

What command do you use?
What params do you use in the Makefile?
Which versions of OpenCV, CUDA, cuDNN do you use?

**Comment by Yagger** [comment]
Hi @AlexeyAB,

Here is the screenshot
<img width="576" alt="Screenshot 2019-05-29 at 09 50 09" src="https://user-images.githubusercontent.com/1056226/58535919-bf6ce200-81f7-11e9-944e-8e5081c921d6.png">

Here are Makefile params
```
GPU=1
CUDNN=0
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0
```

OpenCV version I think is 3.2, and Cuda 8.0.61

And here is the Google Colab file that shows my setup is precise steps.
[yolo_training.ipynb.zip](https://github.com/AlexeyAB/darknet/files/3231099/yolo_training.ipynb.zip)

If I comment out line `!git checkout 8c970498a296ed129ffef7d872ccc25d42d1afda`, it fails to train (it still works for other commands, like detect).

**Comment by Dylan-Duault** [comment]
Hello !

I'm having the same issue, I tried to update Cuda to version 10.1 but the error remains the same.
![image](https://user-images.githubusercontent.com/1349678/58564994-45a41b00-822e-11e9-9108-dfe767fc4478.png)

Tested with Yolov3 and yolov3-tiny

**Comment by Gbellport** [comment]
Hey I have encountered the same exact error and found this: https://stackoverflow.com/a/27278218/6417245, which I assume helps you figure out why and where the error is being produced. Here's a screenshot of my output when I use cuda-memcheck:
![issue2](https://user-images.githubusercontent.com/19672976/59472791-55625880-8e05-11e9-842c-a5234d0308cf.PNG)
I am too using Colab and my Makefile is the same as the person who posted this issue. I tried using CUDNN=1 but it did not fix the error.

**Comment by AlexeyAB** [comment]
@Yagger @Dylan-Duault @Gbellport 

I fixed several bugs.

Try to use the latest version of Darknet.

**Comment by gnefihs** [comment]
i'm still seeing the same error.

`Can't open label file. (This can be normal only if you use MSCOCO): /home/sf/darknet/data/coco/labels/train2014/COCO_train2014_000000171736.txt 
Can't open label file. (This can be normal only if you use MSCOCO): /home/sf/darknet/data/coco/labels/val2014/COCO_val2014_000000028508.txt 
CUDA Error Prev: an illegal memory access was encountered
CUDA Error Prev: an illegal memory access was encountered: File exists
darknet: ./src/utils.c:293: error: Assertion `0' failed.
[1]    12733 abort (core dumped)  ./darknet detector train cfg/coco.data cfg/yolov3.coco-giou-12.cfg  -map -gpu
`
How do i go about solving this?

**Comment by ambr89** [comment]
I'm still seeing the same error.
How can I resolve?

**Comment by AlexeyAB** [comment]
@ambr89 
What command do you use?
What params do you use in the Makefile?
Which versions of OpenCV, CUDA, cuDNN do you use?
Show output of commands
```
nvcc --version
nvidia-smi
```

**Comment by ambr89** [comment]
I'm on ubuntu 
first I've build with
`make`
and after I would try to make my own train with this:
`./darknet detector train data/obj.data cfg/yolov3-tiny_xnor_custom.cfg data/brav/darknet53.conv.74`
error is on the second command

I've set `GPU=1 CUDNN=0 CUDNN_HALF=0`

`nvcc --version`

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

`nvidia-smi`

```
Fri Nov  8 00:06:04 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   31C    P8    13W / 275W |    538MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

```

If I set 
`GPU=1 CUDNN=1 CUDNN_HALF=0`

I receive this error on `make`
```

chmod +x *.sh
g++ -std=c++11 -Iinclude/ -I3rdparty/stb/include -DGPU -I/usr/local/cuda-10.1/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/image_opencv.cpp -o obj/image_opencv.o
In file included from ./src/image.h:3:0,
from ./src/image_opencv.h:4,
from ./src/image_opencv.cpp:1:
include/darknet.h:44:19: fatal error: cudnn.h: No such file or directory
compilation terminated.
Makefile:149: recipe for target 'obj/image_opencv.o' failed
make: *** [obj/image_opencv.o] Error 1
```

thanks in advance!

**Comment by AlexeyAB** [comment]
Try to use GPU=1 CUDNN=1

**Comment by ambr89** [comment]
I'll do it!

**Comment by deep-practice** [comment]
Learning Rate: 0.00025, Momentum: 0.9, Decay: 0.0005
Resizing
608 x 608 
 try to allocate additional workspace_size = 13.11 MB 
 CUDA allocate done! 
Loaded: 0.000126 seconds
CUDA Error Prev: an illegal memory access was encountered
CUDA Error Prev: an illegal memory access was encountered: File exists
darknet: ./src/utils.c:297: error: Assertion `0' failed.
Aborted (core dumped)

The original darknet can run sucessfully

**Comment by deep-practice** [comment]
NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1
Cudnn 7.5
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0

**Comment by AlexeyAB** [comment]
@deep-practice I fixed this bug several hours ago.

**Comment by deep-practice** [comment]
@AlexeyAB Thx.
