### ISSUE TITLE
Detect stops working all of a sudden

### ISSUE THREAD

**Issue by iskandari** [AlexeyAB/darknet#3342]
Hi Alexey, 

Thanks again for making this great repo.  I got `detect` to work and to return images with bounding boxes, and then images cropped with the bounding box cut out (by uncommenting the code in image.c  - that was amazing!! )

I am running `detect` on dozens of images and for some reason, all of a sudden I get the error:

```
CUDA status Error: file: ./src/dark_cuda.c : () : line: 235 : build time: Jun  5 2019 - 17:47:38
CUDA Error: out of memory
CUDA Error: out of memory: File exists
darknet: ./src/utils.c:293: error: Assertion `0' failed. 
```
This is after it ran successfully many times.  What could be the cause of this? 

```
$ nvidia-smi
Thu Jun  6 14:01:29 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.40.04    Driver Version: 418.40.04    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M60           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   37C    P0    40W / 150W |   6722MiB /  7618MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      4288      C   ./darknet                                    929MiB |
|    0      4378      C   ./darknet                                   1334MiB |
|    0      4499      C   ./darknet                                   1109MiB |
|    0      4587      C   ./darknet                                   1162MiB |
|    0      4653      C   ./darknet                                   1334MiB |
|    0      4778      C   ./darknet                                    837MiB |
+-----------------------------------------------------------------------------+
```

**Comment by AlexeyAB** [comment]
@iskandari Hi,
>  (by uncommenting the code in image.c - that was amazing!! )

What code did you uncomment?

**Comment by iskandari** [comment]
```
qsort(selected_detections, selected_detections_num, sizeof(*selected_detections), compare_by_probs);
    for (i = 0; i < selected_detections_num; ++i) {
            int width = im.h * .006;
            if (width < 1)
                width = 1;

            /*
            if(0){
            width = pow(prob, 1./2.)*10+1;
            alphabet = 0;
            }
            */

            //printf("%d %s: %.0f%%\n", i, names[selected_detections[i].best_class], prob*100);
            int offset = selected_detections[i].best_class * 123457 % classes;
            float red = get_color(2, offset, classes);
            float green = get_color(1, offset, classes);
            float blue = get_color(0, offset, classes);
            float rgb[3];

            //width = prob*20+2;

            rgb[0] = red;
            rgb[1] = green;
            rgb[2] = blue;
            box b = selected_detections[i].det.bbox;
            printf("%f %f %f %f\n", b.x, b.y, b.w, b.h);

            int left = (b.x - b.w / 2.)*im.w;
            int right = (b.x + b.w / 2.)*im.w;
            int top = (b.y - b.h / 2.)*im.h;
            int bot = (b.y + b.h / 2.)*im.h;

            if (left < 0) left = 0;
            if (right > im.w - 1) right = im.w - 1;
            if (top < 0) top = 0;
            if (bot > im.h - 1) bot = im.h - 1;

            int b_x_center = (left + right) / 2;
            int b_y_center = (top + bot) / 2;
            int b_width = right - left;
            int b_height = bot - top;
            char labelstr;
            sprintf(labelstr, "%d x %d - w: %d, h: %d", b_x_center, b_y_center, b_width, b_height);

            // you should create directory: result_img
            static int copied_frame_id = -1;
            static image copy_img;
            if (copied_frame_id != frame_id) {
                copied_frame_id = frame_id;
                if (copy_img.data) free_image(copy_img);
                copy_img = copy_image(im);
            }
            image cropped_im = crop_image(copy_img, left, top, right - left, bot - top);
            static int img_id = 0;
            img_id++;
            char image_name[1024];
            int best_class_id = selected_detections[i].best_class;
            sprintf(image_name, "result_img/%s.jpg", frame_id, img_id, best_class_id, names[best_class_id]);
            save_image(cropped_im, image_name);
            free_image(cropped_im);
```

**Comment by iskandari** [comment]
This has produced cropped images of the bounding boxes - and it works well.    It's the
```
CUDA Error: out of memory 
CUDA Error: out of memory: File exists
```
that I don't understand

**Comment by AlexeyAB** [comment]
Check that `/result_img/` folder is emtpy before runing the Darknet.

If it doesn't help then try to change this line:
`sprintf(image_name, "result_img/img_%d_%d_%d_%s.jpg", frame_id, img_id, best_class_id, names[best_class_id]);`
to this:
`sprintf(image_name, "result_img/img_%d_%d_%d_%s_%d.jpg", frame_id, img_id, best_class_id, names[best_class_id], rand());`

Does it help?
