### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by ddurgaprasad** [AlexeyAB/darknet#361]
Following [this ](https://github.com/AlexeyAB/darknet#how-to-train-pascal-voc-data) instructions.
Fialing with below error at Step#7

(C:\Program Files\Anaconda3) D:\SAI\darknet\build\darknet\x64>darknet.exe detector train data/voc.data yolo-voc.2.0.cfg darknet19_448.conv.23

CUDA Error: unknown error
CUDA Error: unknown error: No error

**Comment by AlexeyAB** [comment]
* Just create `yolo_train.cmd` file
* then using Notepad put this text `darknet.exe detector train data/voc.data yolo-voc.2.0.cfg darknet19_448.conv.23` to the file `yolo_train.cmd`
* and run this file `yolo_train.cmd` - double click on this file

**Comment by ddurgaprasad** [comment]
Training kicked off well ! Thank you

**Comment by willfu** [comment]
I encountered the same issue, but not working for the yolo_train.cmd.

 ./darknet.exe detector train data/obj.data yolo-obj.cfg darknet19_448.conv.23
CUDA Error: unknown error
CUDA Error: unknown error: No error

after double click yolo_train.cmd, the window seems flush and disappear.

**Comment by willfu** [comment]
not sure why the issue came out again... my vs is 2013, cuda 9.1, with cudnn. 
./darknet.exe detector train data/obj.data yolo-obj.cfg darknet53.conv.74
CUDA Error: unknown error
CUDA Error: unknown error: No error

Last time, I just checkout the latest code, the issue gone... Why? @AlexeyAB
