### ISSUE TITLE
4CUDA status Error: file: ./src/dark_cuda.c : () : line: 317 

### ISSUE THREAD

**Issue by lunasdejavu** [AlexeyAB/darknet#3618]
os:linux 
input size 256 128
batch size 128 
subdivision 8
CUDA 10.0

I was training peacefully after hours then the errors showed up then the training ended.

 (next mAP calculation at 11150 iterations)
 11149: 0.002806, 0.005395 avg loss, 0.001000 rate, 0.836109 seconds, 1427072 images
 MJPEG-stream sent.
Loaded: 0.000054 seconds
Region Avg IOU: 0.951268, Class: 0.998667, Obj: 0.948771, No Obj: 0.012058, Avg Recall: 1.000000,  count: 16
Region Avg IOU: 0.952377, Class: 0.999942, Obj: 0.948683, No Obj: 0.012607, Avg Recall: 1.000000,  count: 16
Region Avg IOU: 0.935879, Class: 0.999916, Obj: 0.943895, No Obj: 0.012042, Avg Recall: 1.000000,  count: 16
Region Avg IOU: 0.947085, Class: 0.999189, Obj: 0.945228, No Obj: 0.012510, Avg Recall: 1.000000,  count: 16
Region Avg IOU: 0.939592, Class: 0.999398, Obj: 0.948521, No Obj: 0.012134, Avg Recall: 1.000000,  count: 16
Region Avg IOU: 0.949924, Class: 0.999052, Obj: 0.945865, No Obj: 0.012360, Avg Recall: 1.000000,  count: 16
Region Avg IOU: 0.946217, Class: 0.999530, Obj: 0.955150, No Obj: 0.012836, Avg Recall: 1.000000,  count: 16
Region Avg IOU: 0.954375, Class: 0.997456, Obj: 0.952333, No Obj: 0.013153, Avg Recall: 1.000000,  count: 16

 (next mAP calculation at 11150 iterations)
 11150: 0.002303, 0.005086 avg loss, 0.001000 rate, 0.830077 seconds, 1427200 images
Resizing to initial size: 256 x 128
 used slow CUDNN algo without Workspace! Need memory: 5864710144, available: 5860753408
 CUDNN-slow  try to allocate additional workspace_size = 4706.03 MB
 CUDA allocate done!

 calculation mAP (mean average precision)...
4CUDA status Error: file: ./src/dark_cuda.c : () : line: 317 : build time: Jul 18 2019 - 14:58:18
CUDA Error: an illegal memory access was encountered
CUDA Error: an illegal memory access was encountered: Broken pipe
darknet: ./src/utils.c:293: error: Assertion `0' failed.
Aborted

what happened on line 317  in darknet_cuda.c is   CHECK_CUDA(status);
```
void cuda_pull_array(float *x_gpu, float *x, size_t n)
{
    size_t size = sizeof(float)*n;
    //cudaError_t status = cudaMemcpy(x, x_gpu, size, cudaMemcpyDeviceToHost);
    cudaError_t status = cudaMemcpyAsync(x, x_gpu, size, cudaMemcpyDeviceToHost, get_cuda_stream());
    CHECK_CUDA(status);
    cudaStreamSynchronize(get_cuda_stream());
}

```
I didn't see any error messages when I execute 'make'
I can use ./ darknet detector test normally by the  yolov2_last wieghts.

**Comment by cenit** [comment]
which gpu? how much memory? maybe you just have to increase subdivisions...

**Comment by iaixuexi** [comment]
I have the same problem with you. whether you solved it?

**Comment by lunasdejavu** [comment]
I solved it by adding more subdivisions

**Comment by iaixuexi** [comment]
What is the subdivisions you selected, I set the batch to 64, subdivisions to 32, or I have encountered an illegal memory access problem. 





------------------ 原始邮件 ------------------
发件人: "lunasdejavu"<notifications@github.com>;
发送时间: 2019年7月30日(星期二) 上午10:04
收件人: "AlexeyAB/darknet"<darknet@noreply.github.com>;
抄送: "happy sir"<854284535@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [AlexeyAB/darknet] 4CUDA status Error: file: ./src/dark_cuda.c :() : line: 317  (#3618)




Closed #3618.

**Comment by lunasdejavu** [comment]
128 64 works for me
