### ISSUE TITLE
CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by koko-bap** [AlexeyAB/darknet#3766]
Hi, when i run `./darknet rnn train cfg/rnn.train.cfg -file /whatever.txt` or `./darknet rnn generate cfg/rnn.cfg etc` i get the error CUDNN_STATUS_BAD_PARAM for the line 234 in [convolutional_layer.c](https://github.com/AlexeyAB/darknet/blob/4c315ea26b56c2bf20ebc240d94386c6e3cc83db/src/convolutional_layer.c#L234):

`CHECK_CUDNN(cudnnSetConvolutionGroupCount(l->convDesc, l->groups));`

The error msg:

```
[sk@sk dark2]$ ./darknet rnn train cfg/rnn.train.cfg backup/rnn.backup -file /home/sk/dark2/new\ 2.txt 
rnn
   layer   filters  size/strd(dil)      input                output
   0 RNN Layer: 256 inputs, 512 outputs
		
 cuDNN status Error in: file: ./src/convolutional_layer.c : () : line: 234 : build time: Aug 14 2019 - 15:59:55 
cuDNN Error: CUDNN_STATUS_BAD_PARAM
cuDNN Error: CUDNN_STATUS_BAD_PARAM: File exists
darknet: ./src/utils.c:293: error: Assertion 0 failed.
Aborted (core dumped)
```

Ive tried with several older versions of CUDA (9.2 - 10.1) and CUDNN and also for both windows and linux, but nothing helped, except compiling without CUDNN. 

Both training and detection works with CUDNN if using `detector train/test/demo`. Any help would be greatly appreciated!

(Ive been using a GTX1070 on the win10 box and RTX2060 on Fedora)

**Comment by 326-T** [comment]
Hi, I have same problem. LSTM layer doesn't work.
Is there any progress?

**Comment by 326-T** [comment]
I found a bug in connected_layer.c!
That is some function for convolutional_layer are loaded.
So, if you comment out these function while referring to the original code https://github.com/pjreddie/darknet, you can load the RNN layer.

But, LSTM layer still doesn't work!!
Is there another place to fix?
Thank you in advance!

**Comment by AlexeyAB** [comment]
@koko-bap @326-T I fixed it: https://github.com/AlexeyAB/darknet/commit/7bf83018e48ffaf3883f2020dedebb98929acf4f

**Comment by 326-T** [comment]
@AlexeyAB 
Thank you!!!
It works.
