### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by FilipaRamos** [AlexeyAB/darknet#392]
Hello!

Thanks for your work on darknet for windows! 
I am trying to train the model on the PASCAL VOC dataset but once I reach the 6th layer I get a 'CUDA Error: out of memory'

I am running this:
```
darknet detector train data/voc.data yolo-voc.2.0.cfg darknet19_448.conv.23
``` 

I have a NVIDIA GeForce GTX 950M with 2GB dedicated memory and CC = 5.0. Is this not enough to train the model or am I doing something wrong?
Thanks!

**Comment by AlexeyAB** [comment]
Hi, yes, 2 GB GPU-RAM is to train the model.

Try to set:
```
batch=64
subdivisions=32
```

----

https://github.com/AlexeyAB/darknet#how-to-improve-object-detection
> if error Out of memory occurs then in .cfg-file you should increase subdivisions=16, 32 or 64:

**Comment by FilipaRamos** [comment]
Thanks a lot! It's working now. Hadn't found that on the README

**Comment by SouradipBh** [comment]
@FilipaRamos I have tried it with Subdivision=64 in cfg file.My Gpu is RTX 2080.It still happens.Did you find any solution for this?
