### ISSUE TITLE
Problem --->  Cuda Error: invalid device function

### ISSUE THREAD

**Issue by VitaliCzymmek** [AlexeyAB/darknet#40]
Hi, 
i got a CUDA error and can't solve it.
When i use the darknet_coco or voc.cmd i get the following problem: 

CUDA error: invalid device function
CUDA error: invalid device function: No error

![darknet_cmd_problem](https://cloud.githubusercontent.com/assets/26389656/23869294/b65476ac-0822-11e7-871f-4174e24ef639.jpg)

The darknet_no_gpu.exe works fine. The samples of CUDA are also working.
I use VS2015 Community, CUDA 8.0, OpenCV 2.4.9 and CuDnn 5.1

I hope you can help me! 
Thanks in advance

Greetings
Vitali

**Comment by VitaliCzymmek** [comment]
Found the problem!

Had to change in VS2015 the CUDA C/C++ Device settings from compute_52,sm_52 to ---> compute_20, sm_20.

But the next problem is, that I dont get any recognition when using cuDNN. The dog gets diplayed by OpenCV but no rectangels.
Without cuDNN everything works fine.

Any solutions?

Greetings 
Vitali

**Comment by AlexeyAB** [comment]
@VitaliCzymmek 

Try to put `cudnn64_5.dll` near with `darknet.exe` file. 
What model of GPU do you use?

**Comment by VitaliCzymmek** [comment]
The cudnn64_5.dll file is already near darknet.exe.

I use a geforce gt720m.

**Comment by AlexeyAB** [comment]
@VitaliCzymmek 

I use the same  VS2015 Community, CUDA 8.0, OpenCV 2.4.9 and CuDnn 5.1 - and it works fine for both full & tiny models.

My be cuDNN has some incompatibility with old GPU CC 2.0

Check, did you download correct version of cuDNN 5.1? https://developer.nvidia.com/rdp/cudnn-download
You should download `Download cuDNN v5.1 (Jan 20, 2017), for CUDA 8.0`
**but not** `Download cuDNN v5.1 (Jan 20, 2017), for CUDA 7.5`

**Comment by VitaliCzymmek** [comment]
Did everything like in your manual. Reinstalled today everything but got the same result. 

![problem cudnn](https://cloud.githubusercontent.com/assets/26389656/23909196/654452be-08d6-11e7-9919-aa892faa5624.png)

Could the GPU be the problem?

**Comment by AlexeyAB** [comment]
I think yes, we have only a different GPU.
Everything else is the same: Windows 7x64, MSVS2015 Community, OpenCV 2.4.9, CUDA 8.0, cuDNN 5.1 (for CUDA 8.0), Yolo v2.

On nVidia GeForce GTX 970 (GM204) 4GB RAM with **CC 5.2** I got:

![result](https://cloud.githubusercontent.com/assets/4096485/23911911/4798662e-08ef-11e7-947c-f9b263059253.jpg)

**Comment by AlexeyAB** [comment]
I think cuDNN has some incompatibility with old GPU CC 2.0
