### ISSUE TITLE
Attention please! Cmake Cuda not found and no exe file builded

### ISSUE THREAD

**Issue by VZcoding** [AlexeyAB/darknet#4017]
Once again I want your attention that your tutorial is different or outdated! First of all cmake does not match, there is no selection for cuda and cdnn locations, cmake cannot find cuda, I already tested on two devices. Everything is installed and Paths added. Also when building with Visual Studio 2019 there is still no darknet.exe file in x64 directory or anywhere else. Could you please correctly explain how to build it on Windows, or why you just wont upload compiled exe file, why make so complicated??  So many steps to make, additional applications needs to be installed and configured, and for what, one exe file? that you could just upload to repository....

![cd](https://user-images.githubusercontent.com/35932738/66037786-132a6780-e519-11e9-83c0-b673c595a52c.png)
![vs](https://user-images.githubusercontent.com/35932738/66037787-13c2fe00-e519-11e9-9b3c-f95728ec8a6d.png)

**Comment by AlexeyAB** [comment]
* Did you install CUDA after MSVS had been installed?
* Did you look at the directory `/darknet-master/Release/` ?

**Comment by VZcoding** [comment]
1. Yes CUDA installed after Visual Studio 
2. Yes there is exe file inside, how can I be sure it will use GPU properly if the compilation was without CUDA? 
Thanks

**Comment by AlexeyAB** [comment]
Try to run detection or training and look at the GPU-usage in GPU-Z monitor: https://www.techpowerup.com/download/techpowerup-gpu-z/

**Comment by VZcoding** [comment]
Everything happens too fast to notice recourses usage. If I use darknet_no_gpu.exe then CPU all cores works 100% and learning is forever, when I use darknet.exe it finishes in few seconds: "Done! Loaded 45 layers from weights-file" opens blank chart without any lines in it....

**Comment by AlexeyAB** [comment]
What command do you use?

**Comment by VZcoding** [comment]
`darknet.exe detector train data/obj.data yolo-obj.cfg yolov3-tiny.conv.15`

**Comment by AlexeyAB** [comment]
> "Done! Loaded 45 layers from weights-file" opens **blank chart without any lines** in it....

Can you show screenshot?

**Comment by VZcoding** [comment]
print screen does not capture the graph window but its totally empty appears for breaf moment and then closes...
![Untitled](https://user-images.githubusercontent.com/35932738/66116190-f6566880-e5da-11e9-8e18-29fd75b368ff.png)

**Comment by AlexeyAB** [comment]
What is your max_batches= in cfg-file?

**Comment by VZcoding** [comment]
[net]
batch=64
subdivisions=8
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation=1.5
exposure=1.5
hue=0.1
learning_rate=0.001
burn_in=1000
max_batches=0
policy=steps
steps=0,0
scales=0.1,0.1

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

> hange line max_batches to (classes*2000), f.e. max_batches=6000 if you train for 3 classes

**Comment by MSJawad** [comment]
This error means that you didnt install cuda correctly. use vcpkg to install cuda/ try reinstalling(the former worked for me)

**Comment by VZcoding** [comment]
what vcpkg has to do with cuda? All installed correctly, paths are set.
![Untitled](https://user-images.githubusercontent.com/35932738/66132977-94a7f580-e5fe-11e9-96ae-9b8192389354.png)

**Comment by VZcoding** [comment]
"use vcpkg to install cuda" - what do you mean?

**Comment by MSJawad** [comment]
All paths are not set, sir. you need to include the cuda bin folders and the cuda include folders in path and try and see if that works. If not, try uninstalling cuda and installing it through vcpkg. you can google the command (probably vcpkg install cuda:x64-windows). This error is most likely because youre compiling cmake using vs, but vs cant locate your cuda compiler thats nvcc.exe. also, advanced warning, vs2019 isnt supported by cuda yet. compile with vs2017. the error could also be because of that. in fact, its the most likely scenario

**Comment by VZcoding** [comment]
Installed cuda via vcpkg, added variables, used VS2017 in cmake and still get same CUDA compiler - not found...

![1](https://user-images.githubusercontent.com/35932738/66169623-b8dcf400-e649-11e9-9a26-132ab03a9e90.png)
![2](https://user-images.githubusercontent.com/35932738/66169624-b8dcf400-e649-11e9-8da0-0f18de34c9d3.png)

**Comment by VZcoding** [comment]
> https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
> 
> > hange line max_batches to (classes*2000), f.e. max_batches=6000 if you train for 3 classes

Changed max_batches to 6000 still finishes in few seconds and empty chart window.

Can I request somebody for remote help?(paid).

**Comment by AlexeyAB** [comment]
Check that batch=64

**Comment by VZcoding** [comment]
![Untitled](https://user-images.githubusercontent.com/35932738/66206837-e8c3e000-e6b9-11e9-908e-bf69e052d7ca.png)

**Comment by AlexeyAB** [comment]
Compile Darknet with GPU

**Comment by VZcoding** [comment]
How? tried everything...
![Untitled](https://user-images.githubusercontent.com/35932738/66207280-12313b80-e6bb-11e9-9afa-1e27742d5b15.png)

**Comment by MSJawad** [comment]
Did you use x64 VS2017?

**Comment by VZcoding** [comment]
> Did you use x64 VS2017?

omg.... Finally, thank you so much!!

**Comment by VZcoding** [comment]
![Untitled](https://user-images.githubusercontent.com/35932738/66208518-e82d4880-e6bd-11e9-8683-ca7d605da5b9.png)

**Comment by MSJawad** [comment]
No problem. You can close the issue now.
