### ISSUE TITLE
Error after processing test

### ISSUE THREAD

**Issue by agirbau** [AlexeyAB/darknet#4277]
Hello!

I was trying the new changes introduced in darknet (right now I was testing gaussian yolo). In training it seems to work nicely, but after processing a test file (all frames results are computed) it handles this error:

Enter Image Path: CUDA status Error: file: ./src/dark_cuda.c : () : line: 301 : build time: Nov 11 2019 - 11:36:28 
CUDA Error: invalid device pointer
CUDA Error: invalid device pointer: File exists
darknet: ./src/utils.c:293: error: Assertion `0' failed.

I tried with the same exact model with a standard YOLO layer and it raises exactly the same error.

**Comment by scipioni** [comment]
same for me https://github.com/AlexeyAB/darknet/issues/4275

**Comment by AlexeyAB** [comment]
I fixed it.

**Comment by agirbau** [comment]
Thank you! Closing the issue!
