### ISSUE TITLE
Jetson_TX2_4GB: CUDA Error Prev: unspecified launch failure

### ISSUE THREAD

**Issue by QuentinBoul** [AlexeyAB/darknet#4289]
Using TX2 dev kit as TX2_4GB : JP4.2.2:
when running darknet.py: CUDA Error Prev: unspecified launch failure

I fixed this issue with git checkout bb7d699

Please, @AlexeyAB , can you fixe it on master branch? I don't know if only the jetson TX2 4GB is concerned by this problem....

Makefile:

```
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=1
ZED_CAMERA=0
...
# For Jetson Tx2 or Drive-PX2 uncomment:
ARCH= -gencode arch=compute_62,code=[sm_62,compute_62]
```

Thank you!

**Comment by AlexeyAB** [comment]
> I fixed this issue with git checkout bb7d699

Do you mean that previous version of Darknet works well?

Does it work with any new commits than https://github.com/AlexeyAB/darknet/commit/bb7d69941cbce4f67f10406395d685ea92be9478 ? Just to localize the error.

**Comment by QuentinBoul** [comment]
the last commit to work is the 0eee840, the d91d59 does not work. ;-)

**Comment by AlexeyAB** [comment]
@QuentinBoul I fixed it. Try to download Darknet again and recompile.

**Comment by QuentinBoul** [comment]
Great! Thank you @AlexeyAB!
