### ISSUE TITLE
yolo v3 ，can't it be used for multithreading？

### ISSUE THREAD

**Issue by basailuonaaa** [AlexeyAB/darknet#4356]
I want use the same model to detect multiple videos in the same time, in multi-threads,but  report errors! such as (1)CUDA Error Prev: misaligned address;(2)CUDA status Error: file: ./src/dark_cuda.c.....
 how to solve this problem..

**Comment by DarkSand** [comment]
i got this problem too

**Comment by DarkSand** [comment]
i fixed this problem by using threading.Lock()

**Comment by x0rzkov** [comment]
I have this problem too ! How to solve it ?

**Comment by KyloEntro** [comment]
Hi,
What I understand you use mutex to be sure that only one thread do the detection to avoid at least 2 threads use the same ressources ? 

So it is not different than queuing ?
