### ISSUE TITLE
CUDA Error: unknown error during test

### ISSUE THREAD

**Issue by beriusaverio** [AlexeyAB/darknet#4502]
hi @AlexeyAB,
I trained correctly my yolo for detecting costumed objects(3 dog's breeds). I also tested it 2 days ago with the same command line and it worked,  but today it gives me this error: 
```
C:\Users\beriu\Desktop\darknet-master\build\darknet\x64>darknet.exe detector test data/obj.data cfg/yolo-obj.cfg backup/yolo-obj_4000.weights data/testina.jpg
CUDA status Error: file: c:\users\beriu\desktop\darknet-master\src\dark_cuda.c : get_gpu_compute_capability() : line: 468 : build time: Dec  3 2019 - 15:46:35
CUDA Error: unknown error

CUDA Error: unknown error: No error
Assertion failed: 0, file c:\users\beriu\desktop\darknet-master\src\utils.c, line 295
```
training instead works fine, for example
` darknet.exe detector train data/obj.data cfg/yolo-obj.cfg backup/yolo-obj_2000.weights`
worked fine.
I don't know what can I do.

**Comment by beriusaverio** [comment]
I tried again for fun with the same command (didn't change anything at code level) line and now it works fine. it also tested a directory with a list of images and saved results in result.txt
what problem could it have been before??
