### ISSUE TITLE
CUDA Error: unknown error: Bad file descriptor

### ISSUE THREAD

**Issue by ss24cs** [AlexeyAB/darknet#4535]
I have the question, can you help please?
CUDA status Error: file: ./src/dark_cuda.c : () : line: 36 : build time: xxxx
CUDA Error: unknown error
CUDA Error: unknown error: Bad file descriptor
darknet: ./src/utils.c:297: error: Assertion `0' failed.
Aborted (core dumped)

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

Makefile:
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0

nvidia-smi:
NVIDIA-SMI 440.36 Driver Version: 440.36 CUDA Version: 10.2

pkg-config opencv --modversion
3.4.2

**Comment by AlexeyAB** [comment]
Show full screenshot of nvidia-smi command

**Comment by ss24cs** [comment]
-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.36       Driver Version: 440.36       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0  On |                  N/A |
| 46%   24C    P8    14W / 175W |    159MiB /  7979MiB |      4%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2070    Off  | 00000000:03:00.0 Off |                  N/A |
| 48%   22C    P8     9W / 175W |      1MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1270      G   /usr/lib/xorg/Xorg                           157MiB |
+-----------------------------------------------------------------------------+

here, thanks, I used wrong version of CUDA?

**Comment by ss24cs** [comment]
-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.36       Driver Version: 440.36       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0  On |                  N/A |
| 46%   24C    P8    14W / 175W |    159MiB /  7979MiB |      4%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2070    Off  | 00000000:03:00.0 Off |                  N/A |
| 48%   22C    P8     9W / 175W |      1MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1270      G   /usr/lib/xorg/Xorg                           157MiB |
+-----------------------------------------------------------------------------+

**Comment by AlexeyAB** [comment]
> 
> I have the question, can you help please?
> CUDA status Error: file: ./src/dark_cuda.c : () : line: 36 : build time: xxxx
> CUDA Error: unknown error

What command do you use?

**Comment by ss24cs** [comment]
./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights t1.mp4

**Comment by AlexeyAB** [comment]
@ss24cs 

Those. no one Darknet command working?
Can you successfully launch any other application that uses CUDA?

**Comment by ss24cs** [comment]
I'm try this: 
cd /usr/local/cuda-10.0/samples/1_Utilities/deviceQuery
sudo make
sudo ./deviceQuery

and result:
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 2 CUDA Capable device(s)

Device 0: "GeForce RTX 2070"
  CUDA Driver Version / Runtime Version          10.2 / 10.0
  CUDA Capability Major/Minor version number:    7.5
  Total amount of global memory:                 7979 MBytes (8366784512 bytes)
  (36) Multiprocessors, ( 64) CUDA Cores/MP:     2304 CUDA Cores
  GPU Max Clock rate:                            1620 MHz (1.62 GHz)
  Memory Clock rate:                             7001 Mhz
  Memory Bus Width:                              256-bit
  L2 Cache Size:                                 4194304 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1024
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 3 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

Device 1: "GeForce RTX 2070"
  CUDA Driver Version / Runtime Version          10.2 / 10.0
  CUDA Capability Major/Minor version number:    7.5
  Total amount of global memory:                 7982 MBytes (8370061312 bytes)
  (36) Multiprocessors, ( 64) CUDA Cores/MP:     2304 CUDA Cores
  GPU Max Clock rate:                            1620 MHz (1.62 GHz)
  Memory Clock rate:                             7001 Mhz
  Memory Bus Width:                              256-bit
  L2 Cache Size:                                 4194304 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1024
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 3 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 3 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
> Peer access from GeForce RTX 2070 (GPU0) -> GeForce RTX 2070 (GPU1) : No
> Peer access from GeForce RTX 2070 (GPU1) -> GeForce RTX 2070 (GPU0) : No

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 10.2, CUDA Runtime Version = 10.0, NumDevs = 2
Result = PASS

**Comment by AlexeyAB** [comment]
> CUDA status Error: file: ./src/dark_cuda.c : () : line: 36 : build time: xxxx
> CUDA Error: unknown error
> CUDA Error: unknown error: Bad file descriptor
> darknet: ./src/utils.c:297: error: Assertion `0' failed.
> Aborted (core dumped)

Try to compile Darknet with DEBUG=1 in the Makefile.
And show full screenshot of this error with previous messages.

**Comment by ss24cs** [comment]
I did, DEBUG =1 , ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights t1.mp4
and result: 
Video-stream stopped! 
 Video-stream stopped! 
 Video-stream stopped! 
 Video-stream stopped! 
 Video-stream stopped! 
 Video-stream stopped! 
 Video-stream stopped! 
 Video-stream stopped! 
 Video-stream stopped! 
 Video-stream stopped! 
 Video-stream stopped! 
^C

**Comment by ss24cs** [comment]
But use this command:  ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 65.864 
 Allocate additional workspace_size = 52.43 MB 
Loading weights from yolov3.weights...
 seen 64 
Done! Loaded 107 layers from weights-file 
data/dog.jpg: Predicted in 26.879000 milli-seconds.
bicycle: 99%
dog: 100%
truck: 93%

**Comment by AlexeyAB** [comment]
> t1.mp4

Check that you have file t1.mp4
and try another video-file

Can you run successfully this command with DEBUG=0 and DEBUG=1? 
` ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg`

**Comment by ss24cs** [comment]
DEBUG=1 , ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg success:
Done! Loaded 107 layers from weights-file 
data/dog.jpg: Predicted in 28.274000 milli-seconds.
bicycle: 99%
dog: 100%
truck: 93%

DEBUG=0.  ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg , success:
Done! Loaded 107 layers from weights-file 
data/dog.jpg: Predicted in 20.657000 milli-seconds.
bicycle: 99%
dog: 100%
truck: 93%

**Comment by ss24cs** [comment]
And the t1.mp4 is a cs1.6 video, I try use this for test. Thanks a lot!

**Comment by AlexeyAB** [comment]
Did you try other video files?

**Comment by ss24cs** [comment]
Not yet, I haven't found a suitable test short video in my computer. And I will try to find some in website.

**Comment by ss24cs** [comment]
ok, ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights t2.mp4 .The one of the other video success:
FPS:51.2
Objects:

skis: 43% 

FPS:47.2
Objects:

umbrella: 48% 

FPS:51.8
Objects:

knife: 28% 

FPS:51.8
Objects:

knife: 57% 
skis: 31% 
.......
Thanks a lot! buddy.

**Comment by AlexeyAB** [comment]
It seems that just your first videofile is broken or in the unsupported format for OpenCV.
So this is an issue of your videofile vs OpenCV vs video-codecs.

**Comment by ss24cs** [comment]
Actually, at the beginning I ran this command: ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg, also got the same error: CUDA status Error: file: ./src/dark_cuda.c : () : line: 36 : build time: xxxx
CUDA Error: unknown error
CUDA Error: unknown error: Bad file descriptor
darknet: ./src/utils.c:297: error: Assertion `0' failed.
Therefore, I follow your suggestion, set DEBUG = 1, and recompile in Makefile, the cuda error has been solved. Thanks! I'm very grateful.

**Comment by AlexeyAB** [comment]
Do you still get this error if you recompile with DEBUG=0?

**Comment by ss24cs** [comment]
No, this error never happened again. Command ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights t3.mp4 and ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg are running fine.

**Comment by ss24cs** [comment]
And what is the root cause of this error? opencv encoder? Or cuda version? Please?

**Comment by ss24cs** [comment]
Oh NO, I reboot my computer, this error happened again.

**Comment by AlexeyAB** [comment]
Something wrong with your system, I don't know.

**Comment by ss24cs** [comment]
em...., I will check. Thanks.

**Comment by beriusaverio** [comment]
I have the same problem on windows 10, with cuda 10.0. Test or demo or map command randomly don't work. But if I launch a random train comand(blocking it just after it starts plotting the loss, because I don't need it) few times, then test command works. I can't understand why. Sometimes it also helps to reboot pc.

**Comment by ss24cs** [comment]
I find a method, in my PC, I just input:
1 cd /usr/local/cuda-10.0/samples/1_Utilities/deviceQuery
2 sudo make
3 sudo ./deviceQuery
And open darknet file, Command ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights t3.mp4 and ./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg are work again.

**Comment by aidamanzano** [comment]
Hello I am having this same issue. I've been having an issue with Libcublas.so.10 recently where sometimes I would try to run the command `./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg 
`
and I would get the error: `./darknet: error while loading shared libraries: libcublas.so.10: cannot open shared object file: No such file or directory`

I found this similar issue: [here](https://discuss.mxnet.apache.org/t/libcublas-so-10-cannot-open-shared-object-file-no-such-file-or-directory-mxnet/6678) and for a while every time it would throw that error I would run `find /usr -name libcublas*` and then `export LD_LIBRARY_PATH=/usr/local/cuda-10.2/targets/x86_64-linux/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}` and then I could run the detector without a problem. 

I was training a model and it was running fine, its the second time Im training and then I come back I think I may have had a power cut but essentially I opened the terminal and this is the last thing that was written: `v3 (mse loss, Normalizer: (iou: 0.75, cls: 1.00) Region 106 Avg (IOU: 0.000000, GIOU: 0.000000), Class: 0.000000, Obj: 0.000000, No Obj: 0.000000, .5R: 0.000000, .75R: 0.000000, count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000 
CUDA status Error: file: /home/aida/darknet/src/dark_cuda.c : () : line: 469 : build time: May 28 2020 - 21:57:20 ` 
I tried to restart the training from the last saved weights and I got the following error: `CUDA status Error: file: /home/aida/darknet/src/dark_cuda.c : () : line: 39 : build time: May 28 2020 - 21:57:20`

I followed the steps on this thread and tried running `./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg` and again I got the same issue `CUDA status Error: file: /home/aida/darknet/src/dark_cuda.c : () : line: 39 : build time: May 28 2020 - 21:57:20`

I recompiled darknet with DEBUG=1 and this is the log output I get:
`-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;6.0;6.1;7.0;7.0+PTX;7.5;7.5+PTX
-- Building with CUDA flags: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_70,code=compute_70;-gencode;arch=compute_75,code=compute_75
-- Your setup supports half precision (it requires CC >= 7.0)
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
--   ->  darknet is fine for now, but uselib_track has been disabled!
--   ->  Please rebuild OpenCV from sources with CUDA support to enable it
-- CMAKE_CUDA_FLAGS: -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_70,code=compute_70 -gencode arch=compute_75,code=compute_75 --compiler-options " -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -Wno-deprecated-declarations -Wno-write-strings -DGPU -DCUDNN -DOPENCV -fPIC -fopenmp -Ofast " 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/aida/darknet/build_release
[  0%] Building C object CMakeFiles/darknet.dir/src/activation_layer.c.o
[  1%] Building C object CMakeFiles/darknet.dir/src/darknet.c.o
[  2%] Building C object CMakeFiles/darknet.dir/src/activations.c.o
[  2%] Building C object CMakeFiles/darknet.dir/src/avgpool_layer.c.o
[  2%] Building CXX object CMakeFiles/dark.dir/src/yolo_v2_class.cpp.o
[  3%] Building C object CMakeFiles/darknet.dir/src/art.c.o
[  5%] Building C object CMakeFiles/dark.dir/src/activation_layer.c.o
[  5%] Building C object CMakeFiles/darknet.dir/src/batchnorm_layer.c.o
In file included from /home/aida/darknet/src/yolo_v2_class.cpp:1:0:
/home/aida/darknet/include/darknet.h:43:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
CMakeFiles/dark.dir/build.make:82: recipe for target 'CMakeFiles/dark.dir/src/yolo_v2_class.cpp.o' failed
make[2]: *** [CMakeFiles/dark.dir/src/yolo_v2_class.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  5%] Building C object CMakeFiles/darknet.dir/src/blas.c.o
In file included from /home/aida/darknet/src/darknet.c:1:0:
/home/aida/darknet/include/darknet.h:43:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
In file included from /home/aida/darknet/src/activations.h:3:0,
                 from /home/aida/darknet/src/activations.c:1:
/home/aida/darknet/include/darknet.h:43:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
compilation terminated.
CMakeFiles/darknet.dir/build.make:108: recipe for target 'CMakeFiles/darknet.dir/src/activations.c.o' failed
make[2]: *** [CMakeFiles/darknet.dir/src/activations.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/darknet.dir/build.make:82: recipe for target 'CMakeFiles/darknet.dir/src/darknet.c.o' failed
make[2]: *** [CMakeFiles/darknet.dir/src/darknet.c.o] Error 1
In file included from /home/aida/darknet/src/blas.h:4:0,
                 from /home/aida/darknet/src/blas.c:1:
/home/aida/darknet/include/darknet.h:43:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
In file included from /home/aida/darknet/src/network.h:4:0,
                 from /home/aida/darknet/src/art.c:1:
/home/aida/darknet/include/darknet.h:43:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
CMakeFiles/darknet.dir/build.make:160: recipe for target 'CMakeFiles/darknet.dir/src/blas.c.o' failed
make[2]: *** [CMakeFiles/darknet.dir/src/blas.c.o] Error 1
CMakeFiles/darknet.dir/build.make:121: recipe for target 'CMakeFiles/darknet.dir/src/art.c.o' failed
make[2]: *** [CMakeFiles/darknet.dir/src/art.c.o] Error 1
In file included from /home/aida/darknet/src/activations.h:3:0,
                 from /home/aida/darknet/src/activation_layer.h:4,
                 from /home/aida/darknet/src/activation_layer.c:1:
/home/aida/darknet/include/darknet.h:43:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
In file included from /home/aida/darknet/src/image.h:3:0,
                 from /home/aida/darknet/src/avgpool_layer.h:4,
                 from /home/aida/darknet/src/avgpool_layer.c:1:
/home/aida/darknet/include/darknet.h:43:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
In file included from /home/aida/darknet/src/activations.h:3:0,
                 from /home/aida/darknet/src/activation_layer.h:4,
                 from /home/aida/darknet/src/activation_layer.c:1:
/home/aida/darknet/include/darknet.h:43:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
In file included from /home/aida/darknet/src/image.h:3:0,
                 from /home/aida/darknet/src/batchnorm_layer.h:4,
                 from /home/aida/darknet/src/batchnorm_layer.c:1:
/home/aida/darknet/include/darknet.h:43:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.
compilation terminated.
CMakeFiles/darknet.dir/build.make:134: recipe for target 'CMakeFiles/darknet.dir/src/avgpool_layer.c.o' failed
make[2]: *** [CMakeFiles/darknet.dir/src/avgpool_layer.c.o] Error 1
CMakeFiles/darknet.dir/build.make:147: recipe for target 'CMakeFiles/darknet.dir/src/batchnorm_layer.c.o' failed
make[2]: *** [CMakeFiles/darknet.dir/src/batchnorm_layer.c.o] Error 1
CMakeFiles/dark.dir/build.make:95: recipe for target 'CMakeFiles/dark.dir/src/activation_layer.c.o' failed
make[2]: *** [CMakeFiles/dark.dir/src/activation_layer.c.o] Error 1
CMakeFiles/darknet.dir/build.make:95: recipe for target 'CMakeFiles/darknet.dir/src/activation_layer.c.o' failed
make[2]: *** [CMakeFiles/darknet.dir/src/activation_layer.c.o] Error 1
CMakeFiles/Makefile2:153: recipe for target 'CMakeFiles/dark.dir/all' failed
make[1]: *** [CMakeFiles/dark.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/darknet.dir/all' failed
make[1]: *** [CMakeFiles/darknet.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2`
I'm training YOLOv3 with OpenCV version 3.4.4. It worked perfectly fine in June I don't think I have changed anything. I was getting the sporadic issue with Libcublas that I could fix as mentioned recently, but now I cannot even run the training

**Comment by aidamanzano** [comment]
Hi,

Sorry why has this issue been closed? I have not found a solution to my error.

Thank you.

Kind regards,
Aida

De: Stefano Sinigardi<mailto:notifications@github.com>
Enviado: 21 January 2021 18:39
Para: AlexeyAB/darknet<mailto:darknet@noreply.github.com>
CC: A. M Manzano Kharman<mailto:aidammk@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Asunto: Re: [AlexeyAB/darknet] CUDA Error: unknown error: Bad file descriptor (#4535)


Closed #4535<https://github.com/AlexeyAB/darknet/issues/4535>.

**Comment by cenit** [comment]
please open a new issue. The original issue was solved and that's why the issue was closed
