### ISSUE TITLE
CUDA Error: an illegal memory access was encountered: File exists

### ISSUE THREAD

**Issue by alexschultz** [AlexeyAB/darknet#4647]
Tried training Yolov3 using nvidia-docker
I am able to train yolo v3 tiny using the same image with the GPU but I get this error when trying to train on the full yolov3. 

```
...

  94 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
  95 route  91 		                           ->   26 x  26 x 256 
  96 conv    128       1 x 1/ 1     26 x  26 x 256 ->   26 x  26 x 128 0.044 BF
  97 upsample                 2x    26 x  26 x 128 ->   52 x  52 x 128
  98 route  97 36 	                           ->   52 x  52 x 384 
  99 conv    128       1 x 1/ 1     52 x  52 x 384 ->   52 x  52 x 128 0.266 BF
 100 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
 101 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
 102 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
 103 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
 104 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
 105 conv     18       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x  18 0.025 BF
 106 yolo

[yolo] params: iou loss: mse (2), iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 65.304 
 Allocate additional workspace_size = 49.84 MB 
Loading weights from /opt/resources/darknet53.conv.74...
 seen 64 
Done! Loaded 75 layers from weights-file 
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Resizing
608 x 608 
 try to allocate additional workspace_size = 106.46 MB 
 CUDA allocate done! 
Loaded: 0.000029 seconds

CUDA status Error: file: ./src/blas_kernels.cu : () : line: 656 : build time: Jan  7 2020 - 18:50:25 CUDA Error: an illegal memory access was encountered
CUDA Error: an illegal memory access was encountered: File exists
darknet: ./src/utils.c:297: error: Assertion `0' failed.
```

When I build the container without GPU support, training works, albeit very slowly.

I am running Ubuntu 18.04 with an Nvidia 1080ti on the host.

**Comment by KhoiNguyen1112** [comment]
i have same error, i use 1080ti

**Comment by AlexeyAB** [comment]
Attach your cfg-file in zip-archive.

**Comment by AlexeyAB** [comment]
@alexschultz @KhoiNguyen1112 

I fixed this bug.

The error was in the `resize_shortcut_layer()` function which I just fixed: https://github.com/AlexeyAB/darknet/commit/9bd88d7fd7cef872998aa931f8280a1ba1578822#diff-452556c0247ea5a4e6095f1c065edcbeR118-R132

**Comment by alexschultz** [comment]
I pulled the latest and am able to train now. Thanks for fixing this so fast!
