### ISSUE TITLE
Can't train yolov3_tiny_pan3 on new repo (29Jan2020)

### ISSUE THREAD

**Issue by BernoGreyling** [AlexeyAB/darknet#4771]
Hi,

I can't seem to get yolov3_tiny_pan3 trained on my dataset after I upgraded to the new repo. The previous repo that worked was from 15 Jan 2020. I simply cloned the new repo, compiled with the same Makefile settings. I am able to train yolov3_tiny_3l while yolov3_tiny_pan3 starts diverging after a few iterations and then throws a illegal memory access error as soon as most of the `IOU` metrics hit 0.

![image](https://user-images.githubusercontent.com/14345568/73354422-5fef3680-429e-11ea-8daf-49a4fc7d4955.png)

Setup :
RTX 2070 super
CUDA 10.2 cuddn : 7.6.5

Makefile : 
GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=1
AVX=0

OPENMP=0
LIBSO=1
ZED_CAMERA=0
 

[yolov3_tiny_pan3.zip](https://github.com/AlexeyAB/darknet/files/4127768/yolov3_tiny_pan3.zip)

**Comment by AlexeyAB** [comment]
* What command do you use for training?
* Can you share your dataset?
* Try to compile:
```
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0

OPENMP=0
LIBSO=0
ZED_CAMERA=0
```

**Comment by AlexeyAB** [comment]
@BernoGreyling 

I fixed a bug: https://github.com/AlexeyAB/darknet/commit/2862b28dc7327b2ec7085da0f06b665e48c71b50



----

Also I recommend:


* Remove all lines with `antialiasing=1`
* Use default anchors

**Comment by BernoGreyling** [comment]
Hi @AlexeyAB ,

Thanks! The issue has been resolved with the bux fix.
