### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by apennisi** [AlexeyAB/darknet#4921]
Hi @AlexeyAB ,

When I use the C++ wrapper and I call it for the detection, I got the following error:

```
try to allocate additional workspace_size = 52.43 MB 
 CUDA allocate done! 

 cuDNN status Error in: file: ./src/convolutional_kernels.cu : () : line: 544 : build time: Feb 25 2020 - 16:15:07 

 cuDNN Error: CUDNN_STATUS_EXECUTION_FAILED

```

I have CUDA 10.2 and CUDNN 7.6.5. 
If I use uselib or darknet, everything works fine, without any problem.

Can you help me in fixing such an error?

**Comment by apennisi** [comment]
**Update:**  I solved the problem. Darknet and zed cannot work in the same thread. So, the easiest solution is to launch a different thread where darknet can work without any problem.
