### ISSUE TITLE
How to train in FP16

### ISSUE THREAD

**Issue by violet17** [AlexeyAB/darknet#5007]
Hi Alexey,
Thanks for the great work.

I have some questions about training at FP16.

I set `CUDNN_HALF =1` in Makefile.
My CUDA version is  9.0.
And I found some codes in `convolutional_kernels.cu` line `423` and line `675`:
```
    if (state.index != 0 && state.net.cudnn_half && !l.xnor && (!state.train || iteration_num > 3*state.net.burn_in) &&
        (l.c / l.groups) % 8 == 0 && l.n % 8 == 0 && !state.train && l.groups <= 1 && l.size > 1)
```
I think state.train=1 for training, then training darknet  won't go to the code of training in FP16.

Then I revised the codes as 
```
    if (state.index != 0 && state.net.cudnn_half && !l.xnor && 
        (l.c / l.groups) % 8 == 0 && l.n % 8 == 0  && l.size > 1)
```

PS: `l.groups = 1` all the time

At last, I got some errors:
 cuDNN status Error in: file: ./src/convolutional_kernels.cu : () : line: 727 : build time: Mar 11 2020 - 21:18:52 

 cuDNN Error: CUDNN_STATUS_BAD_PARAM
cuDNN Error: CUDNN_STATUS_BAD_PARAM: File exists
darknet: ./src/utils.c:325: error: Assertion `0' failed.
Aborted (core dumped)

Do you have some advice on this issue?

**Comment by AlexeyAB** [comment]
Mixed-precision by using Tensor-Cores are temporary disabled for Training.

To enable, remove `&& !state.train` in both places:
* https://github.com/AlexeyAB/darknet/blob/49a7cdd26852e2f77be470874adc26fda7f89671/src/convolutional_kernels.cu#L675-L676
* https://github.com/AlexeyAB/darknet/blob/49a7cdd26852e2f77be470874adc26fda7f89671/src/convolutional_kernels.cu#L675-L676

**Comment by violet17** [comment]
@AlexeyAB  Yeah, I deleted  `&& !state.train`  and `(!state.train || iteration_num > 3*state.net.burn_in) && `. I want to train in FP16 from iteration one.
Then I got errors:

cuDNN status Error in: file: ./src/convolutional_kernels.cu : () : line: 727 : build time: Mar 11 2020 - 21:18:52

**cuDNN Error: CUDNN_STATUS_BAD_PARAM
cuDNN Error: CUDNN_STATUS_BAD_PARAM: File exists
darknet: ./src/utils.c:325: error: Assertion `0' failed.
Aborted (core dumped)**

**Comment by AlexeyAB** [comment]
@violet17 
I fixed it. 
Try to download the latest Darknet, make your changes and recompile.

Also add to your cfg-file
```
[net]
loss_scale=128
```

**Comment by violet17** [comment]
Thanks for the update.
After download the latest version and add `loss_scale=128` to cfg-file,
I got:
v3 (mse loss, Normalizer: (iou: 0.75, cls: 1.00) Region 106 Avg (IOU: -nan, GIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.516698, .5R: -nan, .75R: -nan, count: 0, class_loss = 4902.201660, iou_loss = 0.000000, total_loss = 4902.201660 
**Floating point exception (core dumped)**

**Comment by AlexeyAB** [comment]
Show training command
Attach your cfg-file in zip-archive
And how many iterations can you train before error occurs?

**Comment by violet17** [comment]
Thanks for the early reponse.
cfg-file:
[yolov3_b.zip](https://github.com/AlexeyAB/darknet/files/4321912/yolov3_b.zip)

training command :
`./darknet detector train cfg/voc_b.data cfg/yolov3_b.cfg yolov3_b.weights.74   -gpus 0 -map -dont_show`
I think in the first iteration the error occurs.

I only revised line `423` and line `675` in `convolutional_kernel.cu` , like 
```
    if (state.index != 0 && state.net.cudnn_half && !l.xnor && 
        (l.c / l.groups) % 8 == 0 && l.n % 8 == 0  && l.groups <= 1 && l.size > 1)
```

The other code is the same as  latest version.

The GPU is Titan V.

**Comment by violet17** [comment]
Update:
I reivsed line `423` in `convolutional_kernel.cu `, like

```
    if (state.index != 0 && state.net.cudnn_half && !l.xnor && 
        (l.c / l.groups) % 8 == 0 && l.n % 8 == 0  && l.groups <= 1 && l.size > 1)
```
and line `675` in `convolutional_kernel.cu` , like
```
    if (state.index != 0 && state.net.cudnn_half && !l.xnor && 
        (l.c / l.groups) % 8 == 0 && l.n % 8 == 0  **&& !state.train** && l.groups <= 1 && l.size > 1)

```
That is, I disable backward using FP16.

Then, I got errors:
```
 CUDNN_HALF!!! state.index = 104 
v3 (mse loss, Normalizer: (iou: 0.75, cls: 1.00) Region 106 Avg (IOU: -nan, GIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.498382, .5R: -nan, .75R: -nan, count: 0, class_loss = 4563.255371, iou_loss = 0.000000, total_loss = 4563.255371 


 Tensor Cores are disabled until the first 3000 iterations are reached. (next mAP calculation at 2146 iterations) 
 1: 2087.693848, 2087.693848 avg loss, 0.000000 rate, 6.855694 seconds, 64 images
Loaded: 0.000110 seconds
CUDA status Error: file: ./src/dark_cuda.c : () : line: 469 : build time: Mar 12 2020 - 09:08:22 

 CUDA Error: an illegal memory access was encountered
CUDA Error: an illegal memory access was encountered: File exists
darknet: ./src/utils.c:325: error: Assertion `0' failed.
Aborted (core dumped)

```

**Comment by violet17** [comment]
@AlexeyAB 
Hi, is there any commit could be trained in FP16?
I used the commit on 26 Dec 2018, 1 Mar 2019, Sep 2019 to train in FP16. But all of them were failed.
Do you have any advice for training in FP16 using Titan V?

**Comment by AlexeyAB** [comment]
@violet17 I added fix.

* Use this commit: https://github.com/AlexeyAB/darknet/commit/18d877a1ac0fdfbc82e0f32f5fefee6ef2c2f63b
    (or do these changes for newer commits https://github.com/AlexeyAB/darknet/issues/5007#issuecomment-597663243  )
* Compile with `GPU=1 CUDNN=1 CUDNN_HALF=1 OPENCV=1`
* add to cfg-file
```
[net]
loss_scale=128
```
And run training on RTX or V100 GPUs, I just tested it works.

If you will successfully train yolov3.cfg on MS COCO, then show me Loss&mAP chart or cfg/weights files, if it show good accuracy - I will add option, so you can eable Tensor Cores just by adding flag to the training command without changing source code.

**Comment by violet17** [comment]
@AlexeyAB 
Thanks for reply.

I have tried to use the latest version commit 1[8d877a](https://github.com/AlexeyAB/darknet/commit/18d877a1ac0fdfbc82e0f32f5fefee6ef2c2f63b) and make these revisitions.
After 3000 iteration, this issue happen:
**`Floating point exception (core dumped)`**

Do you have any suggestion about it?

**Comment by AlexeyAB** [comment]
Can you show a screenshot of the whole error?

**Comment by violet17** [comment]
@AlexeyAB  
![image](https://user-images.githubusercontent.com/4042800/76701564-4fcfd100-66fd-11ea-9014-4122a598f5c2.png)
I started to use FP16 after 3000 iterations.
I saw some issue in github mention this error, but haven't found a way to solve this error.

**Comment by AlexeyAB** [comment]
> I started to use FP16 after 3000 iterations.

What does it mean? 
Did you change anything in the source code?

Thanks! Try to run training with flag `-cuda_debug_sync` and show error message

**Comment by violet17** [comment]
@AlexeyAB 
I means  the code start to use FP16 after ` iteration_num > 3*state.net.burn_in`.  Just remove 4 `!state.train` and no other changes.

The training command is 
`./darknet detector train cfg/voc_b.data cfg/yolov3_b.cfg yolov3_b_3000.weights   -gpus 0,1 -cuda_debug_sync -map -dont_show`

The logs of using flag `-cuda_debug_sync` are shown below:

> v3 (mse loss, Normalizer: (iou: 0.75, cls: 1.00) Region 106 Avg (IOU: -nan, GIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.000003, .5R: -nan, .75R: -nan, count: 0, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000 
> 
> 
>  Tensor Cores are used. (next mAP calculation at 5146 iterations) 
>  3002: 0.512627, 0.512627 avg loss, 0.002000 rate, 9.785406 seconds, 384256 images
> Loaded: 0.000025 seconds
> 
>  CUDNN_HALF!!! state.index = 1 
> 
>  CUDNN_HALF!!! state.index = 3 
> 
>  CUDNN_HALF!!! state.index = 5 
> 
>  CUDNN_HALF!!! state.index = 7 
> 
>  CUDNN_HALF!!! state.index = 10 
> 
>  CUDNN_HALF!!! state.index = 12 
> 
>  CUDNN_HALF!!! state.index = 14 
> 
>  CUDNN_HALF!!! state.index = 17 
> 
>  CUDNN_HALF!!! state.index = 20 
> 
>  CUDNN_HALF!!! state.index = 23 
> 
>  CUDNN_HALF!!! state.index = 26 
> 
>  CUDNN_HALF!!! state.index = 1 
> 
>  CUDNN_HALF!!! state.index = 29 
> 
>  CUDNN_HALF!!! state.index = 32 
> 
>  CUDNN_HALF!!! state.index = 35 
> 
>  CUDNN_HALF!!! state.index = 37 
> 
>  CUDNN_HALF!!! state.index = 39 
> 
>  CUDNN_HALF!!! state.index = 42 
> 
>  CUDNN_HALF!!! state.index = 45 
> 
>  CUDNN_HALF!!! state.index = 3 
> 
>  CUDNN_HALF!!! state.index = 48 
> 
>  CUDNN_HALF!!! state.index = 51 
> 
>  CUDNN_HALF!!! state.index = 5 
> 
>  CUDNN_HALF!!! state.index = 54 
> 
>  CUDNN_HALF!!! state.index = 57 
> 
>  CUDNN_HALF!!! state.index = 7 
> 
>  CUDNN_HALF!!! state.index = 60 
> 
>  CUDNN_HALF!!! state.index = 62 
> 
>  CUDNN_HALF!!! state.index = 10 
> 
>  CUDNN_HALF!!! state.index = 64 
> 
>  CUDNN_HALF!!! state.index = 12 
> 
>  CUDNN_HALF!!! state.index = 67 
> 
>  CUDNN_HALF!!! state.index = 14 
> 
>  CUDNN_HALF!!! state.index = 17 
> 
>  CUDNN_HALF!!! state.index = 70 
> 
>  CUDNN_HALF!!! state.index = 20 
> 
>  CUDNN_HALF!!! state.index = 23 
> 
>  CUDNN_HALF!!! state.index = 73 
> 
>  CUDNN_HALF!!! state.index = 26 
> 
>  CUDNN_HALF!!! state.index = 76 
> 
>  CUDNN_HALF!!! state.index = 29 
> 
>  CUDNN_HALF!!! state.index = 78 
> 
>  CUDNN_HALF!!! state.index = 32 
> 
>  CUDNN_HALF!!! state.index = 35 
> 
>  CUDNN_HALF!!! state.index = 80 
> 
>  CUDNN_HALF!!! state.index = 37 
> 
>  CUDNN_HALF!!! state.index = 39 
> 
>  CUDNN_HALF!!! state.index = 42 
> 
>  CUDNN_HALF!!! state.index = 45 
> 
>  CUDNN_HALF!!! state.index = 48 
> 
>  CUDNN_HALF!!! state.index = 51 
> 
>  CUDNN_HALF!!! state.index = 54 
> 
>  CUDNN_HALF!!! state.index = 57 
> 
>  CUDNN_HALF!!! state.index = 60 
> 
>  CUDNN_HALF!!! state.index = 62 
> 
>  CUDNN_HALF!!! state.index = 64 
> 
>  CUDNN_HALF!!! state.index = 67 
> 
>  CUDNN_HALF!!! state.index = 70 
> 
>  CUDNN_HALF!!! state.index = 73 
> 
>  CUDNN_HALF!!! state.index = 76 
> 
>  CUDNN_HALF!!! state.index = 78 
> 
>  CUDNN_HALF!!! state.index = 80 
> v3 (mse loss, Normalizer: (iou: 0.75, cls: 1.00) Region 82 Avg (IOU: 0.459538, GIOU: 0.326366), Class: 0.668937, Obj: 0.775384, No Obj: 0.001240, .5R: 0.250000, .75R: 0.000000, count: 4, class_loss = 0.499224, iou_loss = 1.045687, total_loss = 1.544911 
> 
>  CUDNN_HALF!!! state.index = 88 
> 
>  CUDNN_HALF!!! state.index = 90 
> 
>  CUDNN_HALF!!! state.index = 92 
> v3 (mse loss, Normalizer: (iou: 0.75, cls: 1.00) Region 82 Avg (IOU: 0.557366, GIOU: 0.537487), Class: 0.400753, Obj: 0.962273, No Obj: 0.001922, .5R: 0.600000, .75R: 0.200000, count: 5, class_loss = 1.132696, iou_loss = 0.742852, total_loss = 1.875548 
> 
>  CUDNN_HALF!!! state.index = 88 
> 
>  CUDNN_HALF!!! state.index = 90 
> 
>  CUDNN_HALF!!! state.index = 92 
> v3 (mse loss, Normalizer: (iou: 0.75, cls: 1.00) Region 94 Avg (IOU: -nan, GIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.000008, .5R: -nan, .75R: -nan, count: 0, class_loss = 0.000001, iou_loss = 0.000000, total_loss = 0.000001 
> 
>  CUDNN_HALF!!! state.index = 100 
> 
>  CUDNN_HALF!!! state.index = 102 
> 
>  CUDNN_HALF!!! state.index = 104 
> v3 (mse loss, Normalizer: (iou: 0.75, cls: 1.00) Region 94 Avg (IOU: -nan, GIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.000010, .5R: -nan, .75R: -nan, count: 0, class_loss = 0.000012, iou_loss = 0.000000, total_loss = 0.000012 
> 
>  CUDNN_HALF!!! state.index = 100 
> 
>  CUDNN_HALF!!! state.index = 102 
> 
>  CUDNN_HALF!!! state.index = 104 
> v3 (mse loss, Normalizer: (iou: 0.75, cls: 1.00) Region 106 Avg (IOU: -nan, GIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.000003, .5R: -nan, .75R: -nan, count: 0, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000 
> v3 (mse loss, Normalizer: (iou: 0.75, cls: 1.00) Region 106 Avg (IOU: -nan, GIOU: -nan), Class: -nan, Obj: -nan, No Obj: 0.000003, .5R: -nan, .75R: -nan, count: 0, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000 
> Floating point exception (core dumped)

**Comment by AlexeyAB** [comment]
@violet17 

* Can you show output of the error if you run with flag `-benchmark_layers` ?
* Do you get this error if you don't use `loss_scale=128` ?
* Do you get this error if you don't use Tensor Cores, use `&& !state.train` in both forward & backward?
* Do you get if you train with Darknet compiled with CUDNN_HALF=0 ?
* DO you get this error on other datasets?

I removed `iteration_num > 3*state.net.burn_in` so as not to wait for 3000 iterations, and train by using https://github.com/AlexeyAB/darknet/files/4321912/yolov3_b.zip cfg-file on MS COCO, but I can not reproduce this error even after 100 iterations.

![image](https://user-images.githubusercontent.com/4096485/76703796-61a57a00-66e5-11ea-805b-f05256a8c2cc.png)

**Comment by AlexeyAB** [comment]
@violet17 

Also try to add these lines:
```
    if (count == 0) count = 1;
    if (class_count == 0) class_count = 1;
```

there and recompile: https://github.com/AlexeyAB/darknet/blob/8ffc2b0b36b16cb0d9456a5f732191f56458e7ed/src/yolo_layer.c#L543

**Comment by violet17** [comment]
@AlexeyAB 

- The logs after using `-benchmark_layers`:

[logs using benchmark layers.txt](https://github.com/AlexeyAB/darknet/files/4334386/logs.using.benchmark.layers.txt)

- some logs of removing `loss_scale=128`


> Do you get this error if you don't use Tensor Cores, use && !state.train in both forward & backward?
No. Using `&& !state.train ` in both forward & backward won't got this error.

> Do you get if you train with Darknet compiled with CUDNN_HALF=0 ?
No errors.
> DO you get this error on other datasets?
Haven't tried to train other datasets in FP16.

**Comment by violet17** [comment]
@AlexeyAB 
The same error.
The logs of Adding 
```
 if (count == 0) count = 1;
    if (class_count == 0) class_count = 1;
```
in line 543 of yolo_layer.c:
[logs of adding count=1.txt](https://github.com/AlexeyAB/darknet/files/4334402/logs.of.adding.count.1.txt)

**Comment by AlexeyAB** [comment]
@violet17 
> I notice that IOU, GIOU, Class, Obj, .5R , .75R, class_loss , iou_loss , total_loss are all zeros.
> Note: There are some images without any object in the datasets. Will this be a problem? Everything is right when without CUDNN_HALF=1

No, this is not a problem.
May be there are some objects with zero or negative size, but Yolo should reject such objects without falling.

I think some  error is in the [yolo] layer.

Try to replace file `src/yolo_layer.c` by this [yolo_layer.c.txt](https://github.com/AlexeyAB/darknet/files/4335010/yolo_layer.c.txt)
(remove txt extension)

And show an error.

**Comment by violet17** [comment]
@AlexeyAB 

The logs are attached.
[logs of replacing yolo_layer.txt](https://github.com/AlexeyAB/darknet/files/4335677/logs.of.replacing.yolo_layer.txt)
Thanks!

**Comment by violet17** [comment]
@AlexeyAB 
The logs of training in MS COCO 2014 using FP16.
[logs of training on COCO2014 using FP16.txt](https://github.com/AlexeyAB/darknet/files/4338455/logs.of.training.on.COCO2014.using.FP16.txt)

> Floating point exception (core dumped)

**Comment by AlexeyAB** [comment]
@violet17 Thanks.
Can you also try to change these two files:
1. [yolo_layer.c.txt](https://github.com/AlexeyAB/darknet/files/4338836/yolo_layer.c.txt)

2. [network_kernels.cu.txt](https://github.com/AlexeyAB/darknet/files/4338840/network_kernels.cu.txt)


Run training on 1 GPU with flags `-cuda_debug_sync -benchmark_layers` and show output? 

----

* What OS do you use?
* Show output of commands:
```
nvcc --version
nvidia-smi
gcc --version
```

* Also show such output:
![image](https://user-images.githubusercontent.com/4096485/76772781-8582c180-67b2-11ea-8fcf-7a2339740bc6.png)

**Comment by violet17** [comment]
@AlexeyAB 
Thanks for helping.
The logs of  training with COCO 2014 on 1 GPU with flags `-cuda_debug_sync -benchmark_layers` and show output:
[logs of training coco after replacing yolo layer and network kernel cu.txt](https://github.com/AlexeyAB/darknet/files/4339041/logs.of.training.coco.after.replacing.yolo.layer.and.network.kernel.cu.txt)

Note: I have removed my cudnn version 7.6.4 last weekend, because I thought the cudnn is too old, but the error is always there, and I recover it to the previous version 7.1.6. Now the Cudnn version is 7.1.6.

> What OS do you use?

$ uname -a
Linux adc-v100 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

> Show output of commands:
> nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

> nvidia-smi
Mon Mar 16 23:56:15 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.34                 Driver Version: 387.34                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Graphics Device     Off  | 00000000:2D:00.0 Off |                  N/A |
| 28%   43C    P0    36W / 250W |      0MiB / 12036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Graphics Device     Off  | 00000000:99:00.0 Off |                  N/A |
| 30%   45C    P0    37W / 250W |      0MiB / 12058MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
> gcc --version
gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`$ lspci | grep VGA`
2d:00.0 VGA compatible controller: NVIDIA Corporation GV100 [TITAN V] (rev a1)
99:00.0 VGA compatible controller: NVIDIA Corporation GV100 [TITAN V] (rev a1)


![image](https://user-images.githubusercontent.com/4042800/76777066-9ba87600-67e2-11ea-8c12-59d89f49ec10.png)

**Comment by AlexeyAB** [comment]
@violet17 
> Driver Version: 387.34      

Isn't this Driver version is too old for Tesla V100?
May be you should update your driver or install CUDA 10.0 with new Drivers?

Also try to keep changed previous files.
And also change this file: [convolutional_kernels.cu.txt](https://github.com/AlexeyAB/darknet/files/4339230/convolutional_kernels.cu.txt)

Recompile, run with `-cuda_debug_sync -benchmark_layers` and show an error.

**Comment by violet17** [comment]
@AlexeyAB 
Thank you very much for your kindly help!

I copied all code and coco dataset to Tesla T4 with Cuda 10.0 on it, then run it without any error.
And I updated my cuda in TITAN V to cuda 10.0, cudnn to 7.6.5(NV driver to 410.48 ). Now it can run successfully.
![image](https://user-images.githubusercontent.com/4042800/76858291-11b7e600-6892-11ea-83cf-ba2b91639fc2.png)

**Comment by AlexeyAB** [comment]
@violet17 Nice!
It seems that Bug was in `CUDA 9.0 + cuDNN 7.1.4`

**Comment by violet17** [comment]
> @violet17 Nice!
> It seems that Bug was in `CUDA 9.0 + cuDNN 7.1.4`

Yeah. CUDA 9.0 is the bug.
This code cann't train in FP16 using CUDA 9.0.

Thanks a lot for your help!

**Comment by AlexeyAB** [comment]
@violet17 

In the latest Darknet version, for training in FP16 you should just
* compile Darknet with GPU=1 CUDNN=1 CUDNN_HALF=1 (and preferably OPENCV=1)
* add parameter `[net] loss_scale=128` to your cfg-file

**Comment by violet17** [comment]
@AlexeyAB 
All my CUDA version have been upgrade to CUDA 10.0. No more CUDA 9.0.
Sorry that I cann't test them in CUDA 9.0.
Why the previous version cannot work in CUDA 9.0? They have different CUDA function?
