### ISSUE TITLE
mAP count stopped working (cudnn error)

### ISSUE THREAD

**Issue by dkubatin** [AlexeyAB/darknet#5014]
Good day, @AlexeyAB !
After the last commits **mAP** ceased to be considered.

- Videocard: RTX 2080Ti
- CUDA Version: 10.2
- OpenCV version: 3.2.0
- cuDNN: 7

![Снимок экрана от 2020-03-12 17-15-58](https://user-images.githubusercontent.com/56879344/76530812-53f1b980-6485-11ea-928b-feaf91a1ac72.png)

He rolled back to the commit from Feb 20 and everything works.

**Comment by AlexeyAB** [comment]
This seems like a hardware error message. Try again with the last commit.

**Comment by dkubatin** [comment]
mAP is still **not considered**.
I checked all the commits, the error is in the March 11 commit.
Link to commit: [commit](https://github.com/AlexeyAB/darknet/commit/1a56ef588a37f047bbac938d677c42b91a2b80bd)

_It was at this commit that this error appeared.
Checked on two devices._

**Comment by AlexeyAB** [comment]
Do you get the same error message in all cases?
Do you use the same directory on HDD for all commits?

> Checked on two devices.

On 2 different computers?
Or on 1 computer with 2 GPUs?

**Comment by dkubatin** [comment]
> Do you get the same error message in all cases?

Yes.

> Do you use the same directory on HDD for all commits?

No, on different computers, with different drives

**Comment by AlexeyAB** [comment]
Show content of obj.data file

**Comment by dkubatin** [comment]
> Show content of obj.data file

classes=1
train=/home/dkubatin/learn_plate_20/train.txt
valid=/home/dkubatin/learn_plate_20/test.txt
names=/home/dkubatin/learn_plate_20/metadata/classes.names
backup=/home/dkubatin/learn_plate_20/backup

**Comment by AlexeyAB** [comment]
Can you successfully run object detection on video or calc_anchors?

`./darknet detector calc_anchors obj.data -num_of_clusters 9 -width 416 -height 416`

**Comment by dkubatin** [comment]
calc_anchors **works**, but the demo on the video does **not work**, writes:  _Video-stream stopped!_

**Comment by AlexeyAB** [comment]
>  the demo on the video does not work, writes: Video-stream stopped!

Can you show screenshot?

**Comment by AlexeyAB** [comment]
Set in obj.data file
```
train=/home/dkubatin/learn_plate_20/test.txt
```
run calc_anchors and show me result

**Comment by dkubatin** [comment]
![Снимок экрана от 2020-03-13 15-33-00](https://user-images.githubusercontent.com/56879344/76621230-f2daec00-653f-11ea-8d36-2fefe1199e49.png)

**Comment by AlexeyAB** [comment]
Try to run mAP calculation with flag `-cuda_debug_sync`

**Comment by dkubatin** [comment]
He doesn’t count with the flag either, however, after the pull of recent changes, the map calculation works both with and without the flag.

**Comment by AlexeyAB** [comment]
Is problem solved?

**Comment by dkubatin** [comment]
Yes!
