### ISSUE TITLE
bad file descriptor

### ISSUE THREAD

**Issue by cat768** [AlexeyAB/darknet#5226]
When I do `./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg
`, it responds with:

CUDA status Error: file: ./src/dark_cuda.c : () : line: 39 : build time: Apr 13 2020 - 10:26:41 

 CUDA Error: unknown error
CUDA Error: unknown error: Bad file descriptor
darknet: ./src/utils.c:325: error: Assertion `0' failed.
Aborted (core dumped)

Here is my nvidia-smi:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.44       Driver Version: 440.44       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    On   | 00000000:01:00.0  On |                  N/A |
| N/A   50C    P8    11W /  N/A |    642MiB /  8111MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1238      G   /usr/lib/xorg/Xorg                            18MiB |
|    0      1276      G   /usr/bin/gnome-shell                          21MiB |
|    0      1463      G   /usr/lib/xorg/Xorg                           295MiB |
|    0      1605      G   /usr/bin/gnome-shell                         153MiB |
|    0      2124      G   ...AAAAAAAAAAAAAAgAAAAAAAAA --shared-files    88MiB |
|    0      4478      G   gnome-control-center                           1MiB |
|    0      8564      G   ...quest-channel-token=8237868688173725965    57MiB |
+-----------------------------------------------------------------------------+

And here is my makefile:
GPU=1
CUDNN=1
CUDNN_HALF=0
OPENCV=1
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0 # ZED SDK 3.0 and above
ZED_CAMERA_v2_8=0 # ZED SDK 2.X

I have already tried redownloading it and recompiling it, but the same error message keeps popping up.

**Comment by ntdat017** [comment]
I think you should downgrade CUDA version to 10.1.

**Comment by cat768** [comment]
How do I downgrade cuda?

**Comment by cat768** [comment]
This error doesn't show up anymore after I rebooted my machine.

Don't know how but the problem was solved
