### ISSUE TITLE
CUDA error occurs when training with multiple GPUs.

### ISSUE THREAD

**Issue by keita-honsho** [AlexeyAB/darknet#5301]
hi @AlexeyAB 

When training with the same cfg file, these errors will only occur if you are using multiple GPUs.

Windows10, VisualStudio 2019, GeForce GTX1080, CUDA 10.2, cuDNN 7.6.5, OpenCV 4.2.0
yolov3-voc.cfg --> batch 64, subdivisions 32, classes 4, train 25864 images, valid 2873 images.

**darknet.exe built on 3/25/2020, no error. (1GPU)**

**darknet.exe built on 3/25/2020, error occurred 4 times. (2GPU)**

> CUDA Error: out of memory: No error
>  CUDA Error: out of memory

**darknet.exe built on 4/11/2020, error occurred 3 times. (2GPU)**
2x
> CUDA Error: out of memory: No error
>  CUDA Error: out of memory

1x
> CUDA Error: out of memory: Invalid argument
>  CUDA Error: out of memory

Presumably, the memory leak was fixed during this time.

**darknet.exe built on 4/21/2020, error occurred 3 times. (2GPU)**
3x
> Syncing... Saving weights to data/backup/yolov3-train_fsi_20200313_416_32_last.weights
> CUDA Error: out of memory: Invalid argument
> Done!
>  CUDA allocate done! 
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_free() : line: 454 : build time: Apr 21 2020 - 13:56:41 
>  CUDA Error: out of memory

Is it a bug that I get an error like the one above when learning on multiple GPUs?

---
<details>
<summary>darknet.exe built on 3/25/2020

GTX1080 x1 : success
GTX1080 x2 : 4 errors.
</summary>

>  Try to set subdivisions=64 in your cfg-file. 
>  Try to set subdivisions=64 in your cfg-file. 
> CUDA Error: out of memory: No error
> P@0.5 = 95.67 %, best = 95.67 % 
>  15481: 0.147021, 0.163870 avg loss, 0.002000 rate, 3.014000 seconds, 1362328 images, 48.237407 hours left
> Loaded: 0.000000 seconds
>  (next mAP calculation at 17826 iterations) 
>  Last accuracy mAP@0.5 = 95.67 %, best = 95.67 % 
>  15483: 0.134623, 0.160945 avg loss, 0.002000 rate, 3.075000 seconds, 1362504 images, 48.045708 hours left
> Resizing, random_coef = 1.40 
>  416 x 416 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
> Loaded: 1.267000 seconds - performance bottleneck on CPU or Disk HDD/SSD
>  (next mAP calculation at 17826 iterations) 
>  Last accuracy mAP@0.5 = 95.67 %, best = 95.67 % 
>  15485: 0.168082, 0.161659 avg loss, 0.002000 rate, 2.952000 seconds, 1362680 images, 47.861792 hours left
> Loaded: 0.000000 seconds
>  (next mAP calculation at 17826 iterations) 
>  Last accuracy mAP@0.5 = 95.67 %, best = 95.67 % 
>  15487: 0.252509, 0.170744 avg loss, 0.002000 rate, 2.999000 seconds, 1362856 images, 47.790015 hours left
> Loaded: 0.000000 seconds
>  (next mAP calculation at 17826 iterations) 
>  Last accuracy mAP@0.5 = 95.67 %, best = 95.67 % 
>  15489: 0.177707, 0.171440 avg loss, 0.002000 rate, 3.004000 seconds, 1363032 images, 47.601293 hours left
> Loaded: 0.000000 seconds
>  (next mAP calculation at 17826 iterations) 
>  Last accuracy mAP@0.5 = 95.67 %, best = 95.67 % 
>  15491: 0.171659, 0.171462 avg loss, 0.002000 rate, 3.016000 seconds, 1363208 images, 47.414924 hours left
> Loaded: 0.000000 seconds
>  (next mAP calculation at 17826 iterations) 
>  Last accuracy mAP@0.5 = 95.67 %, best = 95.67 % 
>  15493: 0.190108, 0.173327 avg loss, 0.002000 rate, 3.060000 seconds, 1363384 images, 47.231559 hours left
> Loaded: 0.000000 seconds
>  (next mAP calculation at 17826 iterations) 
>  Last accuracy mAP@0.5 = 95.67 %, best = 95.67 % 
>  15495: 0.173823, 0.173376 avg loss, 0.002000 rate, 3.051000 seconds, 1363560 images, 47.054253 hours left
> Loaded: 0.000000 seconds
>  (next mAP calculation at 17826 iterations) 
>  Last accuracy mAP@0.5 = 95.67 %, best = 95.67 % 
>  15497: 0.217498, 0.177789 avg loss, 0.002000 rate, 3.036000 seconds, 1363736 images, 46.877835 hours left
> Loaded: 0.000000 seconds
>  (next mAP calculation at 17826 iterations) 
>  Last accuracy mAP@0.5 = 95.67 %, best = 95.67 % 
>  15499: 0.156313, 0.175641 avg loss, 0.002000 rate, 3.012000 seconds, 1363912 images, 46.701719 hours left
> Loaded: 0.000000 seconds
>  (next mAP calculation at 17826 iterations) 
>  Last accuracy mAP@0.5 = 95.67 %, best = 95.67 % 
>  15501: 0.168809, 0.174958 avg loss, 0.002000 rate, 3.014000 seconds, 1364088 images, 46.525034 hours left
> Loaded: 0.000000 seconds
>  (next mAP calculation at 17826 iterations) 
>  Last accuracy mAP@0.5 = 95.67 %, best = 95.67 % 
>  15503: 0.139174, 0.171379 avg loss, 0.002000 rate, 2.956000 seconds, 1364264 images, 46.350291 hours left
> Resizing, random_coef = 1.40 
>  512 x 512 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
> Loaded: 0.000000 seconds
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_make_array() : line: 373 : build time: Apr 13 2020 - 12:33:34 
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_make_array() : line: 373 : build time: Apr 13 2020 - 12:33:34 
>  CUDA Error: out of memory
>  CUDA Error: out of memory
> 

>  (next mAP calculation at 31926 iterations) 
>  Last accuracy mAP@0.5 = 95.99 %, best = 95.99 % 
>  29843: 0.138822, 0.148634 avg loss, 0.002000 rate, 3.005000 seconds, 2626184 images, 20.452617 hours left
> Resizing, random_coef = 1.40 
> 
>  544 x 544 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA  Try to set subdivisions=64 in your cfg-file. 
>  Try to set subdivisions=64 in your cfg-file. 
> CUDA Error: out of memory: No error
> allocate done! 
> Loaded: 0.000000 seconds
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_make_array() : line: 373 : build time: Apr 13 2020 - 12:33:34 
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_make_array() : line: 373 : build time: Apr 13 2020 - 12:33:34 
>  CUDA Error: out of memory
>  CUDA Error: out of memory
>

>  Try to set subdivisions=64 in your cfg-file. 
>  Try to set subdivisions=64 in your cfg-file. 
> CUDA Error: out of memory: No error
> 0.089131, 0.088822 avg loss, 0.000200 rate, 3.021000 seconds, 3873496 images, 6.448461 hours left
> Loaded: 0.000000 seconds
>  (next mAP calculation at 46226 iterations) 
>  Last accuracy mAP@0.5 = 96.69 %, best = 96.91 % 
>  44019: 0.088612, 0.088801 avg loss, 0.000200 rate, 3.028000 seconds, 3873672 images, 6.435862 hours left
> Loaded: 0.000000 seconds
>  (next mAP calculation at 46226 iterations) 
>  Last accuracy mAP@0.5 = 96.69 %, best = 96.91 % 
>  44021: 0.085738, 0.088495 avg loss, 0.000200 rate, 3.025000 seconds, 3873848 images, 6.423492 hours left
> Loaded: 0.000000 seconds
>  (next mAP calculation at 46226 iterations) 
>  Last accuracy mAP@0.5 = 96.69 %, best = 96.91 % 
>  44023: 0.115433, 0.091189 avg loss, 0.000200 rate, 3.049000 seconds, 3874024 images, 6.411178 hours left
> Resizing, random_coef = 1.40 
>  544 x 544 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
> Loaded: 0.000000 seconds
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_make_array() : line: 373 : build time: Apr 13 2020 - 12:33:34 
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_make_array() : line: 373 : build time: Apr 13 2020 - 12:33:34 
>  CUDA Error: out of memory
>  CUDA Error: out of memory
>
</details>

---
<details>
<summary>darknet.exe built on 4/11/2020

GTX1080 x2 : 3 errors. (No error x2, Invalid argument x1)
</summary>

>  (next mAP calculation at 15544 iterations) 
>  Last accuracy mAP@0.5 = 94.45 %, best = 94.86 % 
>  15118: 0.120453, 0.135776 avg loss, 0.002000 rate, 5.734000 seconds, 1935104 images, 54.999709 hours left
> Loaded: 0.000000 seconds
> Syncing...  Try to set subdivisions=64 in your cfg-file. 
>  Try to set subdivisions=64 in your cfg-file. 
> CUDA Error: out of memory: No error
> Done!
>  (next mAP calculation at 15544 iterations) 
>  Last accuracy mAP@0.5 = 94.45 %, best = 94.86 % 
>  15120: 0.140084, 0.136207 avg loss, 0.002000 rate, 6.182000 seconds, 1935360 images, 55.008490 hours left
> Resizing, random_coef = 1.40 
>  480 x 480 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
> Loaded: 1.781000 seconds - performance bottleneck on CPU or Disk HDD/SSD
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_make_array() : line: 373 : build time: Apr 13 2020 - 12:33:34 
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_make_array() : line: 373 : build time: Apr 13 2020 - 12:33:34 
>  CUDA Error: out of memory
>  CUDA Error: out of memory
>

>  (next mAP calculation at 29644 iterations) 
>  Last accuracy mAP@0.5 = 96.90 %, best = 97.18 % 
>  28838: 0.123831, 0.114447 avg loss, 0.002000 rate, 4.286000 seconds, 3691264 images, 36.079182 hours left
> Loaded: 0.000000 seconds
> Syncing...  Try to set subdivisions=64 in your cfg-file. 
>  Try to set subdivisions=64 in your cfg-file. 
> CUDA Error: out of memory: No error
> Done!
>  (next mAP calculation at 29644 iterations) 
>  Last accuracy mAP@0.5 = 96.90 %, best = 97.18 % 
>  28840: 0.128050, 0.115807 avg loss, 0.002000 rate, 4.767000 seconds, 3691520 images, 35.972717 hours left
> Resizing, random_coef = 1.40 
>  576 x 576 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
> Loaded: 0.000000 seconds
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_make_array() : line: 373 : build time: Apr 13 2020 - 12:33:34 
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_make_array() : line: 373 : build time: Apr 13 2020 - 12:33:34 
>  CUDA Error: out of memory
>  CUDA Error: out of memory
>

>  (next mAP calculation at 43344 iterations) 
>  Last accuracy mAP@0.5 = 96.99 %, best = 97.04 % 
>  43118: 0.058075, 0.079578 avg loss, 0.000200 rate, 3.599000 seconds, 5519104 images, 11.462055 hours left
> Loaded: 0.000000 seconds
> Syncing... CUDA Error: out of memory: Invalid argument
> Done!
>  (next mAP calculation at 43344 iterations) 
>  Last accuracy mAP@0.5 = 96.99 %, best = 97.04 % 
>  43120: 0.073396, 0.078959 avg loss, 0.000200 rate, 4.024000 seconds, 5519360 images, 11.418235 hours left
> Resizing, random_coef = 1.40 
>  448 x 448 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_free() : line: 454 : build time: Apr 13 2020 - 12:33:34 
>  CUDA Error: out of memory
>
</details>

---
<details>
<summary>darknet.exe built on 4/21/2020

GTX1080 x2 : 3 errors. (Invalid argument x3)
</summary>

>  (next mAP calculation at 15544 iterations) 
>  Last accuracy mAP@0.5 = 91.64 %, best = 95.57 % 
>  15358: 0.180298, 0.144135 avg loss, 0.002000 rate, 3.959000 seconds, 1965824 images, 50.729219 hours left
> Loaded: 0.000000 seconds
> Syncing... CUDA Error: out of memory: Invalid argument
> Done!
>  (next mAP calculation at 15544 iterations) 
>  Last accuracy mAP@0.5 = 91.64 %, best = 95.57 % 
>  15360: 0.173733, 0.147094 avg loss, 0.002000 rate, 4.352000 seconds, 1966080 images, 50.605092 hours left
> Resizing, random_coef = 1.40 
>  608 x 608 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_free() : line: 454 : build time: Apr 21 2020 - 13:56:41 
>  CUDA Error: out of memory
>

>  (next mAP calculation at 29844 iterations) 
>  Last accuracy mAP@0.5 = 96.44 %, best = 96.72 % 
>  29378: 0.080444, 0.107043 avg loss, 0.002000 rate, 4.690000 seconds, 3760384 images, 33.179480 hours left
> Loaded: 0.000000 seconds
> Syncing... CUDA Error: out of memory: Invalid argument
> Done!
>  (next mAP calculation at 29844 iterations) 
>  Last accuracy mAP@0.5 = 96.44 %, best = 96.72 % 
>  29380: 0.089955, 0.105334 avg loss, 0.002000 rate, 5.151000 seconds, 3760640 images, 33.118950 hours left
> Resizing, random_coef = 1.40 
>  544 x 544 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_free() : line: 454 : build time: Apr 21 2020 - 13:56:41 
>  CUDA Error: out of memory
>

>  (next mAP calculation at 43844 iterations) 
>  Last accuracy mAP@0.5 = 96.69 %, best = 97.39 % 
>  43398: 0.110412, 0.080458 avg loss, 0.000200 rate, 3.905000 seconds, 5554944 images, 9.888523 hours left
> Loaded: 0.000000 seconds
> Syncing... Saving weights to data/backup/yolov3-train_fsi_20200313_416_32_last.weights
> CUDA Error: out of memory: Invalid argument
> Done!
>  (next mAP calculation at 43844 iterations) 
>  Last accuracy mAP@0.5 = 96.69 %, best = 97.39 % 
>  43400: 0.054134, 0.077825 avg loss, 0.000200 rate, 4.294000 seconds, 5555200 images, 9.863421 hours left
> Resizing, random_coef = 1.40 
>  576 x 576 
>  try to allocate additional workspace_size = 52.43 MB 
>  CUDA allocate done! 
> CUDA status Error: file: C:\local\darknet\src\dark_cuda.c : cuda_free() : line: 454 : build time: Apr 21 2020 - 13:56:41 
>  CUDA Error: out of memory
>
</details>

**Comment by AlexeyAB** [comment]
* Do you use cuDNN from the official site?
* Try to re-install CUDA and cuDNN: https://developer.nvidia.com/rdp/cudnn-archive

**Comment by keita-honsho** [comment]
> Do you use cuDNN from the official site?

Yes, I get from NVIDIA Developer's site.

> Try to re-install CUDA and cuDNN: https://developer.nvidia.com/rdp/cudnn-archive

update driver to 442.92(nvidia studio deriver)
re-install cuda 10.2, and cuDNN 7.6.5

re-training now.

**Comment by euivmar** [comment]
Hi @AlexeyAB,

I have the same problem with a similar configuration and with a version builded the 12 of May 2020.  I have tried to train yolov4 (trainvalno5k 2014 dataset)  with this configuration (Windows 10 environment) and :

```
darknet.exe detector train cfg/coco.data cfg/yolov4.cfg backup/yolov4_last.weights -gpus 0,1,2
 CUDA-version: 10020 (10020), cuDNN: 7.6.5, CUDNN_HALF=1, GPU count: 3
 CUDNN_HALF=1
 OpenCV version: 4.2.0
0,1,2
yolov4
 0 : compute_capability = 750, cudnn_half = 1, GPU: TITAN RTX
net.optimized_memory = 0
mini_batch = 4, batch = 64, time_steps = 1, train = 1
```

I have only modified yolov4.cfg to subdivisions=16 for one GPU (works ok) but the problem happens randomly with the multi-gpu configuration (CUDA Error: out of memory). 

For the multi-gpu configuration (3GPUs) I have reduced to learning_rate=0.00087 and I have increased the burn_in to 3000 as suggested.

When the error happened, the nvidia-smi command showed this info:

<img width="256" alt="nvidia_smi" src="https://user-images.githubusercontent.com/11088553/82220619-2a3e8e00-991f-11ea-857c-642390bab078.png">

The flag  -cuda_debug_sync did not give more info about the error.

**Comment by AlexeyAB** [comment]
* Do you train with `-map` flag? If yes, download the latest version, it was fixed.

* Also try to train with `subdivisions=32`

**Comment by euivmar** [comment]
Thank you for your fast reply.
> * Do you train with `-map` flag? If yes, download the latest version, it was fixed.
No, I train without map flag. 
> * Also try to train with `subdivisions=32`


I have just trainned with subdivision=32 and same error. It seems to work ok for more Iterations than with subdivision=16 but eventually fails. 

 I don't understand the error because with subdivision 32 I have only 7.6 G of Memory Usage from 24G. 

![image](https://user-images.githubusercontent.com/11088553/82291641-a8e00d80-99a9-11ea-86c5-14cb8afacd1c.png)

**Comment by keita-honsho** [comment]
Hi @AlexeyAB,

I'm using the -map option.
I changed the driver to the latest version (SD442.92) and installed the overwritten CUDA and cuDNN that I downloaded again.
I'm learning v4 on darknet, which I built on 4/27. (without 0ef5052)
It is currently 228226/500500, but there is no error.

thanks.

**Comment by AlexeyAB** [comment]
So it seems this bug is fixed.

**Comment by euivmar** [comment]
I can confirm that your last bug-fix solved my problem. 

Thank you  so much @AlexeyAB!
