### ISSUE TITLE
CUDA Error Prev: an illegal memory access was encountered

### ISSUE THREAD

**Issue by ThunderSui** [AlexeyAB/darknet#5407]
I trained yolov4 on my own data set with the param **"-dont_show -map -gpus 1,2"**, and an error occurred while calculating mAP.
We have 2 Tesla K80 (4 GPU in total) and I trained my dataset on GPUs with index 1 & 2 (they are not on the same card). I've followed the steps in "How to train with multi-GPU" that train on 1 GPU first.

**error logs:**
+----------------------------------------------------------------------------+
 (next mAP calculation at 40292 iterations)
40292: 1.286420, 1.314193 avg loss, 0.001000 rate, 21.316723 seconds, 5157376 images, 204.057233 hours left
Resizing to initial size: 416 x 416  try to allocate additional workspace_size = 99.68 MB
 CUDA allocate done!
 try to allocate additional workspace_size = 99.68 MB
 CUDA allocate done!

 calculation mAP (mean average precision)...
4
 CUDA Error Prev: an illegal memory access was encountered
CUDA Error Prev: an illegal memory access was encountered: Success
darknet: ./src/utils.c:325: error: Assertion `0' failed.
Aborted (core dumped)
+----------------------------------------------------------------------------+

**My envs:**
    CUDA=10.0
    CuDNN=7.6.5
    OpenCV=4.3.0
**My cfg setting:**
    batch=64
    subdivisions=16
    width=416
    height=416

**Besides**, I found that when the multi-GPU training stops and I use yolo_last again for multi-GPU training, the number of iterations gets weird, like stopping at 9000s and continuing the training will show 14000s, how should I fix the number of iterations?

**Comment by AlexeyAB** [comment]
* Do you use the latest Darknet version?


* Yes, there is some issue with training with -map flag with multi-GPUs on K80 (2014). So try to train without -map flag and check the accuracy later

**Comment by ThunderSui** [comment]
Thank you for your reply, I'll check the accuracy later!

I'm using the Darknet with "commit 65506eb04acacc050a1903614066337071e866b8" which is committed at Apr 27, 2020. Does this version of darknet need to be updated?

**Comment by AlexeyAB** [comment]
In your case, no.

**Comment by DocF** [comment]
Hi @AlexeyAB 
I just have the same question on  4 GTX TITAN X with param `-dont_show -map -gpus 0,1,2,3`. 
Recently, Is there any new solution for this error ? thx a lot!

**Comment by AlexeyAB** [comment]
@DocF 

* Provide more info.

* Show screenshot of the error.

* Try to train without `-map` flag

**Comment by DocF** [comment]
@AlexeyAB 
This is my screenshot including the command on the bottom.
![Screenshot from 2020-05-07 09-45-52](https://user-images.githubusercontent.com/24698266/81245763-6da81b00-9048-11ea-8824-5db2a18067d3.png)
Training without `-map` flag is ok.

**Comment by DocF** [comment]
I am sorry, the command is 
`./darknet detector train data/custom/NWPU.data yolov4-NWPU.cfg backup/yolov4-NWPU_2000.weights -map -dont_show  -gpus 0,1,2,3`

**Comment by AlexeyAB** [comment]
> Training without -map flag is ok.

Train without map, until I fix it.

**Comment by Sudhakar17** [comment]
@AlexeyAB : I got the same error for yolov4-tiny.cfg(with map) but there is no error for yolov3-tiny.cfg(with map). Is it possible to save the best weights without -map ?

**Comment by jiarenyf** [comment]
Having the same question ...

**Comment by hoangphucITJP** [comment]
> @AlexeyAB : I got the same error for yolov4-tiny.cfg(with map) but there is no error for yolov3-tiny.cfg(with map). Is it possible to save the best weights without -map ?

Hi @AlexeyAB . I still got the same issue.

Also, training without `-map` won't produce `best.weights` which means that the best weight is based on mAP, right?
Shouldn't the best weight be picked based on validation loss instead?

**Comment by never-to-never** [comment]
I have the same problem, is it fixed?thanks

**Comment by korhun** [comment]
I have the same issue using yolov4-tiny.cfg with using -map as well. Without using -map there is no problem. But I don't know which weight file produced is the best. Any help to workaround this error, or a way to understand which weight file is the best one without using -map argument; is very appreciated.

**Comment by zl286947277** [comment]
@AlexeyAB
I have solved the same problem above, by setting batch=16, subdivisions=1.
My GPU is RTX8000. I checked GPU memory usage when the error occurs,  it show that it's not a problem of insufficient  memory.
It seems that when the condition mini_batch <= 16 is met , the program can run normally with flag -map.

I hope this clues help you locate the bug.

**Comment by huiyiygy** [comment]
@zl286947277 
Tankyou for your solution!!!  (*^▽^*)
I have  the same problem. 
In my case, GPU is rtx2080 ti，batch=96, subdivisions=6. mini_batch=16 dont work, when it starts to calcuate MAP. 
So，I change subdivisions=8. mini_batch=12, then it calculates map **correctly**
But on gtx1080 ti or TITAN V gpu，when using batch=96, subdivisions=6. mini_batch=16 at the same config and dataset, this error will not happen.  So strange~ ┓( ´∀` )┏

@AlexeyAB 
I hope these clues can help you locate the bug.
