### ISSUE TITLE
compiled binary of darknet is not running in other windows machines

### ISSUE THREAD

**Issue by physxP** [AlexeyAB/darknet#5498]
I compiled the binary of darknet using cmake gui method on my windows 10 with cuda 10.0. I followed all the steps and the binary runs fine in my pc. The problem occurs whenever I try to run the binary in remote computer using windows 10 (with cuda 10.0). I get the following error:
`CUDA status Error: file: F:/stuff/Projects/people_detection/darknet/src/blas_kernels.cu : add_bias_gpu() : line: 103 : build time: May  6 2020 - 11:44:10

 CUDA Error: no kernel image is available for execution on the device`

 The thing is the directory above " F:/stuff/Projects/people_detection/darknet/src/blas_kernels.cu" is the directory in which the code was compiled. I don't know why this is showing or if the problem is path related. The same problem happened in 2 other remote computers.

here is my console output:
[error snap.txt](https://github.com/AlexeyAB/darknet/files/4586297/error.snap.txt)

**Comment by AlexeyAB** [comment]
And copy all required DLLs from source PC: cudart64_100.dll cublas64_100.dll cudnn64_7.dll opencv_world420.dll pthreadVC2.dll

Install MSVS-redist on destination PC, f.e. if you use MSVS2015: https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1

Set ALL for CUDA_ARCH, and compile Darknet.

![image](https://user-images.githubusercontent.com/4096485/81178440-de9bf400-8fb0-11ea-92a6-4b35578c5ad8.png)

**Comment by physxP** [comment]
Thank you so much! I was stuck for a few days and this fixed it. Setting CUDA_ARCHITECTURES to All was giving some weird compilation errors so I set it for the target system and it worked.

**Comment by physxP** [comment]
Thank you so much! I was stuck for a few days and this fixed it. Setting CUDA_ARCHITECTURES to All was giving some weird compilation errors so I set it for the target system and it worked.
