### ISSUE TITLE
CUDA Error: invalid device ordinal

### ISSUE THREAD

**Issue by JasonRuan5** [AlexeyAB/darknet#5524]
Hi @AlexeyAB
We like to call yolo_cpp_dll.dll from C#, so we wrote a com wrapper in C++.  There is one Create method as below:
`STDMETHODIMP CDetector::Create(BSTR strCfg, BSTR strFileWeights, int gpuID, VARIANT_BOOL* bOK)
{
	try {
		if (pDetector != 0) 
			delete pDetector;
			
		char *pCfg = _com_util::ConvertBSTRToString(strCfg);
		char *pWeights = _com_util::ConvertBSTRToString(strFileWeights);
		pDetector = new Detector(pCfg, pWeights, gpuID);
		delete[] pCfg;
		delete[] pWeights;
	}
	catch (...) {
		return E_FAIL;
	}
	*bOK = 1;

	return S_OK;
}
`
We also wrote a quick test to call Create as below:
`static void Main(string[] args) {
            string strCfg = @"E:\yoloData\yolov3-tiny.cfg";
            string strWeight = @"E:\yoloData\yolov3-tiny.weights";

            int gpuID = 0;
            Detector yolo = new Detector();
            try {
                yolo.Create(strCfg, strWeight, gpuID);
            } finally {
                yolo.Close();
            }
            return;
        }
`
When we run, sometime is perfect, but sometime throws
CUDA status Error: cuda_set_device()
CUDA Error: invalid device ordinal
When I traced into, it seems occurred at either 
check_cuda( cudaGetDevice(&old_gpu_index) ) or 
cuda_set_device(cur_gpu_id) in 
LIB_API Detector::Detector(std::string cfg_filename, std::string weight_filename, int gpu_id) constructor.
What could cause the problem and any work around?

**Comment by yeongwoonIm** [comment]
I have a same problem..
doesn't it support GTX1050 ??? or other problems??
I run training on GTX1080 Ti is fine..
but when I run C# with wrapper C++(yolo.dll) On GTX1050 , it appears error.
and I trace that I figure out that it stopped at code here
>>>    check_cuda( cudaGetDevice(&old_gpu_index) );
win event viewer show ntdll.dll
*------------------------------*
오류 있는 응용 프로그램 이름: crackDetector.exe, 버전: 1.0.0.0, 타임스탬프: 0x5ed89d0f
오류 있는 모듈 이름: ntdll.dll, 버전: 6.3.9600.19153, 타임스탬프: 0x5b93ffa7
예외 코드: 0xc0000374
오류 오프셋: 0x00000000000f1cd0
오류 있는 프로세스 ID: 0x375c
오류 있는 응용 프로그램 시작 시간: 0x01d63a4052aa24a9
오류 있는 응용 프로그램 경로: F:\ywim\02.source \crackDetector_vs17\crackDetector\crackDetector\bin\x64\Release\crackDetector.exe
오류 있는 모듈 경로: C:\Windows\SYSTEM32\ntdll.dll
보고서 ID: 91c26c0c-a633-11ea-8291-b3d58ceac8c1
오류 있는 패키지 전체 이름: 
오류 있는 패키지에 상대적인 응용 프로그램 ID: 
*-----------------------------------------------------*

**Comment by yeongwoonIm** [comment]
> I have a same problem..
> doesn't it support GTX1050 ??? or other problems??
> I run training on GTX1080 Ti is fine..
> but when I run C# with wrapper C++(yolo.dll) On GTX1050 , it appears error.
> and I trace that I figure out that it stopped at code here
> 
> > > > check_cuda( cudaGetDevice(&old_gpu_index) );
> > > > win event viewer show ntdll.dll

------------------------------------------------------------------------------------
I made a mistake ;;;
wrapper linked  Yolo-v2. and using Yolo-v4 dll.
check it what version of yolo linked.
I changed link Yolo-v2 to Yolo-v4, then problem solved~
that's it!
