### ISSUE TITLE
CUDA compiler not found when compiling Darknet in Windows using CMake

### ISSUE THREAD

**Issue by dsbyprateekg** [AlexeyAB/darknet#5716]
Hi,

I am trying to compile the Darknet code with GPU enable settings to use YOLO v4.
I made the required GPU enable settings in Makefile and ran the compile command:**.\build.ps1**

This command runs successfully but in the console I am seeing following line-

> Looking for a CUDA compiler - NOTFOUND

Now when I ran the command mentioned in the section **How to evaluate FPS of YOLOv4 on GPU**, I am getting average FPS as 0.4 which I thought is due to CPU uses. So my GPU is not used.

It seems either .\build.ps1 command is not using Makefile GPU settings or it is not able to find CUDA compiler. I have verified my GPU uses by running a TensorFlow 2.2 deep learning model and it was using the GPU.

My system configuration is as below-
Windows 10 64 bit 16 GB RAM
NVIDIA GeForce GTX 1660 Ti Version 445.87
CUDA 10.1
cuDNN 7.6.5
Visual Studio 2017

Using YOLOv4 without GPU is not useful for my project. Can anyone please look into this issue?
If not possible with .\build.ps1 file, is there any way to install and compile the code with GPU enable seetings using VCPKG?

![build_not_found](https://user-images.githubusercontent.com/30830541/82725677-2f735280-9cfc-11ea-94cc-62d521fb626a.JPG)

![GPU_not_used](https://user-images.githubusercontent.com/30830541/82725801-2f278700-9cfd-11ea-8baf-a2f9c18af41f.JPG)

![makefile](https://user-images.githubusercontent.com/30830541/82725827-639b4300-9cfd-11ea-8c12-ecf8e1229626.JPG)

**Comment by AlexeyAB** [comment]
@cenit Hi, what could be the reason?

**Comment by cenit** [comment]
It seems that CUDA has been installed without Visual Studio integration (a specific default component to install during CUDA installation).
@dsbyprateekg can you please reinstall CUDA making sure to install also VS integration?
Otherwise, you can try to bypass it creating an environment variable, `CUDACXX`, and make it point to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe` (in case you installed your CUDA 10.1 in the default folder, change it appropriately otherwise)

**Comment by dsbyprateekg** [comment]
Thanks @cenit and @AlexeyAB for looking into my issue.

Since this afternoon I was looking into to somehow compile the code with GPU and just now I am able to do it. So I am sharing what option worked for me.

1. Downloaded the latest VCPKG from below repo:
[https://github.com/Microsoft/vcpkg](url)

2. Installed the VCPKG via Windows Power Shell opened as admin

3. Created a environment variable VCPKG_ROOT with the root directory of the VCPKG

4. Disabled the antivirus setting (otherwise step 4 will not be completed successfully)

5. Followed the 'How to compile on Windows (using vcpkg)' section of your repo and '.\vcpkg install darknet[full]:x64-windows' command took a while but compiled the code successfully

After this when I ran the command `./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -dont_show -ext_output` I am able to see my GPU is used and I am getting average FPS as 6.7

![after_gpu_fps](https://user-images.githubusercontent.com/30830541/82732892-e1774280-9d2d-11ea-9fb5-248ff9a6a296.JPG)

![image_gpu_yolo](https://user-images.githubusercontent.com/30830541/82732913-09ff3c80-9d2e-11ea-9bf6-8c1aa4255154.JPG)

So in my case installing and building the code with VCPKG worked. Please close the issue as I am now able to use my GPU with YOLO v4.

**Comment by cenit** [comment]
vcpkg in fact has ninja integrated within itself and uses the trick I told you to build darknet.

In any case, in darknet we use a very modern way to build CUDA with CMake. Tensorflow (and openCV, for what you might be interested) still do not use it and so they do something different. Unfortunately from time to time we suffer from some bugs, due to being so bleeding edge, but in the long run we will be ready without having to modify anything. I am still very confident that your VS CUDA integration is broken, but good for you that now you're able to build darknet

**Comment by nizarmasmoudi** [comment]
> It seems that CUDA has been installed without Visual Studio integration (a specific default component to install during CUDA installation).
> @dsbyprateekg can you please reinstall CUDA making sure to install also VS integration?
> 
> Otherwise, you can try to bypass it creating an environment variable, `CUDACXX`, and make it point to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe`. In this case, you also have to open the `build.ps1` script and change `$use_ninja` from `$false` to `$true`. This also means that you have to install ninja-build (you can download it from [here](https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-win.zip) and move the exe file in a folder within your PATH )
> 
> The problem seems clear thanks to the fact that the CUDA compiler is not found, but some lines after CUDA itself is found

My CUDA was not found by darknet build even though I had it correctly installed and have been using it for tensorflow. I tried the ninja build you mentioned and I keep getting an error (ObjectNotFound) apparently it is looking for `darknet\build_win_release_novcpkg\DarknetConfig.cmake` and it's none existent. Any help ?
Thank you in advance !

**Comment by cenit** [comment]
full log please.
Also post it within triple accent (`), so that it's properly readable here with markdown syntax

**Comment by deyu001** [comment]
> > It seems that CUDA has been installed without Visual Studio integration (a specific default component to install during CUDA installation).
> > @dsbyprateekg can you please reinstall CUDA making sure to install also VS integration?
> > Otherwise, you can try to bypass it creating an environment variable, `CUDACXX`, and make it point to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe`. In this case, you also have to open the `build.ps1` script and change `$use_ninja` from `$false` to `$true`. This also means that you have to install ninja-build (you can download it from [here](https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-win.zip) and move the exe file in a folder within your PATH )
> > The problem seems clear thanks to the fact that the CUDA compiler is not found, but some lines after CUDA itself is found
> 
> My CUDA was not found by darknet build even though I had it correctly installed and have been using it for tensorflow. I tried the ninja build you mentioned and I keep getting an error (ObjectNotFound) apparently it is looking for `darknet\build_win_release_novcpkg\DarknetConfig.cmake` and it's none existent. Any help ?
> Thank you in advance !

i have the same issues，you need CUDA\**v10.2**
