### ISSUE TITLE
Training failed after 900 iterations on K80:  CUDA Error Prev: an illegal memory access was encountered

### ISSUE THREAD

**Issue by awaisbajwaml** [AlexeyAB/darknet#5779]
@AlexeyAB 

After 900 iterations of training, I received the following error and it fails:

![image](https://user-images.githubusercontent.com/47017344/83218616-440c7c00-a13c-11ea-9122-b7bbe60d0977.png)

Here is the output chart: 

![image](https://user-images.githubusercontent.com/47017344/83218658-5c7c9680-a13c-11ea-8083-832ede2f821a.png)

System details:

I am using the latest build of Darknet v4 with this training command. 

Here is the initialization: 

![image](https://user-images.githubusercontent.com/47017344/83218804-baa97980-a13c-11ea-9438-1b50d7c42daa.png)

Here is the output of nvidia-smi

![image](https://user-images.githubusercontent.com/47017344/83218240-b4ff6400-a13b-11ea-9df8-65f3adaa4d85.png)

# cfg file

`[net]
batch=64
subdivisions=16

width=416
height=416
#width=608
#height=608
channels=3
momentum=0.949
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 6000
policy=steps
steps=4800,5400
scales=.1,.1`

If you have any suggestions on what is happening or if I can look at any log? I didn't see any bad.* file in the darknet folder.

**Comment by AlexeyAB** [comment]
Train on K80 without -map flag

**Comment by awaisbajwaml** [comment]
@AlexeyAB  - just to let you know it worked fine without -map flag as you suggested.  But is there a fix? why did it happen if you would like to explain please

**Comment by yassinesefrioui** [comment]
@awaisbajwaml did you resolve it ? 
thank you

**Comment by awaisbajwaml** [comment]
@yassinesefrioui  yes I solved it - I changed the training using non -map version.

**Comment by awaisbajwaml** [comment]
closing the isssue

**Comment by cccaaannn** [comment]
I have the same problem with M60. After first map calculation I get the same error.  I changed subdivisions to 64 and tried training with last weights after the error, it trains fine like this even with map flag. Maybe it also works for you.
