### ISSUE TITLE
Yolov4-tiny custom training : Out  of memory

### ISSUE THREAD

**Issue by s2ac8es2123** [AlexeyAB/darknet#6162]
Hello!

I am training custom model of yolov4-tiny,
but there was 'CUDA Error: out of memory' when training

llike this :
```
CUDA-version: 10010 (10020), cuDNN: 7.6.3, GPU count: 1  
 OpenCV version: 4.3.0
 Prepare additional network for mAP calculation...
 0 : compute_capability = 610, cudnn_half = 0, GPU: GeForce GTX 1060 6GB 
net.optimized_memory = 0 
mini_batch = 1, batch = 16, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 2    640 x 640 x   3 ->  320 x 320 x  32 0.177 BF
   1 conv     64       3 x 3/ 2    320 x 320 x  32 ->  160 x 160 x  64 0.944 BF
   2 conv     64       3 x 3/ 1    160 x 160 x  64 ->  160 x 160 x  64 1.887 BF
   3 route  2 		                       1/2 ->  160 x 160 x  32 
   4 conv     32       3 x 3/ 1    160 x 160 x  32 ->  160 x 160 x  32 0.472 BF
   5 conv     32       3 x 3/ 1    160 x 160 x  32 ->  160 x 160 x  32 0.472 BF
   6 route  5 4 	                           ->  160 x 160 x  64 
   7 conv     64       1 x 1/ 1    160 x 160 x  64 ->  160 x 160 x  64 0.210 BF
   8 route  2 7 	                           ->  160 x 160 x 128 
   9 max                2x 2/ 2    160 x 160 x 128 ->   80 x  80 x 128 0.003 BF
  10 conv    128       3 x 3/ 1     80 x  80 x 128 ->   80 x  80 x 128 1.887 BF
  11 route  10 		                       1/2 ->   80 x  80 x  64 
  12 conv     64       3 x 3/ 1     80 x  80 x  64 ->   80 x  80 x  64 0.472 BF
  13 conv     64       3 x 3/ 1     80 x  80 x  64 ->   80 x  80 x  64 0.472 BF
  14 route  13 12 	                           ->   80 x  80 x 128 
  15 conv    128       1 x 1/ 1     80 x  80 x 128 ->   80 x  80 x 128 0.210 BF
  16 route  10 15 	                           ->   80 x  80 x 256 
  17 max                2x 2/ 2     80 x  80 x 256 ->   40 x  40 x 256 0.002 BF
  18 conv    256       3 x 3/ 1     40 x  40 x 256 ->   40 x  40 x 256 1.887 BF
  19 route  18 		                       1/2 ->   40 x  40 x 128 
  20 conv    128       3 x 3/ 1     40 x  40 x 128 ->   40 x  40 x 128 0.472 BF
  21 conv    128       3 x 3/ 1     40 x  40 x 128 ->   40 x  40 x 128 0.472 BF
  22 route  21 20 	                           ->   40 x  40 x 256 
  23 conv    256       1 x 1/ 1     40 x  40 x 256 ->   40 x  40 x 256 0.210 BF
  24 route  18 23 	                           ->   40 x  40 x 512 
  25 max                2x 2/ 2     40 x  40 x 512 ->   20 x  20 x 512 0.001 BF
  26 conv    512       3 x 3/ 1     20 x  20 x 512 ->   20 x  20 x 512 1.887 BF
  27 conv  256274       1 x 1/ 1     20 x  20 x 512 ->   20 x  20 x256274 104.970 BF
  28  Try to set subdivisions=64 in your cfg-file. 
CUDA status Error: file: ./src/dark_cuda.c : () : line: 373 : build time: May 15 2020 - 12:46:22 

 CUDA Error: out of memory
CUDA Error: out of memory: File exists
```

As seen, model loading is always stop in layer 28

this is my cfg file
```
[net]
#Testing
#batch=1
#subdivisions=1
#Training
batch=64
subdivisions=16
width=640
height=640
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1
flip=0

learning_rate=0.00261
burn_in=1000
max_batches = 4000
policy=steps
steps=3200,3600
scales=.1,.1

[convolutional]
batch_normalize=1
filters=32
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[route]
layers=-1
groups=2
group_id=1

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[route]
layers = -1,-2

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[route]
layers = -6,-1

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[route]
layers=-1
groups=2
group_id=1

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[route]
layers = -1,-2

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[route]
layers = -6,-1

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[route]
layers=-1
groups=2
group_id=1

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[route]
layers = -1,-2

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[route]
layers = -6,-1

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

##################################

[convolutional]
batch_normalize=1
filters=256274
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=18
activation=linear



[yolo]
mask = 3,4,5
#anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
anchors = 24, 18,  28, 24,  35, 37,  44, 39,  43, 63,  64, 61
classes=1
num=6
jitter=.3
scale_x_y = 1.05274
cls_normalizer=1.0
iou_normalizer=0.07
iou_loss=giou
ignore_thresh = .7
truth_thresh = 1
random=0
resize=1.5
nms_kind=greedynms
beta_nms=0.6

[route]
layers = -4

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = -1, 23

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=18
activation=linear

[yolo]
mask = 1,2,3
#anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
anchors = 24, 18,  28, 24,  35, 37,  44, 39,  43, 63,  64, 61
classes=1
num=6
jitter=.3
scale_x_y = 1.05
cls_normalizer=1.0
iou_normalizer=0.07
iou_loss=giou
ignore_thresh = .7
truth_thresh = 1
random=0
resize=1.5
nms_kind=greedynms
beta_nms=0.6
```

Learning other models like yolov3-tuny, yolov4 works very well
So I don't know why this is happening

Does anyone know how to fix this?

**Comment by ankandrew** [comment]
Try with `subdivisions=32` or `subdivisions=64`

**Comment by s2ac8es2123** [comment]
I've already done that, but the results are the same.

**Comment by WongKinYiu** [comment]
because you use `filters=256274` in your cfg.
it should be `filters=256`.

**Comment by ankandrew** [comment]
I think OP wanted to recreate the essence of GPT-3 with YOLO :)

**Comment by s2ac8es2123** [comment]
@WongKinYiu 
I couldn't bear to see that part.
change my cfg file and it works well. Thank you.
