### ISSUE TITLE
CUDA Error: invalid device pointer

### ISSUE THREAD

**Issue by ahmeterenodaci** [AlexeyAB/darknet#6270]
Can you give me some suggestion? I couldn't find any solutions.
Thank you!

```
darknet.exe detector train build/darknet/x64/data/vehicle.data build/darknet/x64/cfg/yolov4-vehicle.cfg build/darknet/x64/yolov4.conv.137

CUDA-version: 10000 (11000), cuDNN: 8.0.1, GPU count: 1
 OpenCV version: 4.3.0
yolov4-vehicle
 0 : compute_capability = 610, cudnn_half = 0, GPU: GeForce GTX 1050
net.optimized_memory = 0
mini_batch = 1, batch = 32, time_steps = 1, train = 1

.....

Done! Loaded 137 layers from weights-file
Learning Rate: 0.001, Momentum: 0.949, Decay: 0.0005
 Detection layer: 139 - type = 27
 Detection layer: 150 - type = 27
 Detection layer: 161 - type = 27
 If error occurs - run training with flag: -dont_show
Resizing, random_coef = 1.40

 704 x 704
 Create 6 permanent cpu-threads
CUDA status Error: file: c:\git\darknet\src\dark_cuda.c : cuda_free() : line: 454 : build time: Jul 17 2020 - 22:12:24

 CUDA Error: invalid device pointer
```

**Comment by d-cota** [comment]
I have the same issue when trying to resize the net.

> darknet.exe detector train data/mask.data cfg/yolov4-mask.cfg data/yolov4.conv.137 -dont_show
 CUDA-version: 11000 (11000), cuDNN: 8.0.1, GPU count: 1
 OpenCV version: 4.1.0
yolov4-mask
 0 : compute_capability = 750, cudnn_half = 0, GPU: GeForce GTX 1650 with Max-Q Design
net.optimized_memory = 0
mini_batch = 1, batch = 64, time_steps = 1, train = 1
...
CUDA status Error: file: C:\Users\david\PycharmProjects\darknet\src\dark_cuda.c : cuda_free() : line: 454 : build time: Jul 28 2020 - 11:08:22
CUDA Error: invalid argument

**Comment by d-cota** [comment]
I solved it by changing the way in which the variable `net.workspace` has been allocated in `parser.c`. The problem was that when `workspace_size` is 0, the array is allocated calling `xcalloc`, but `network_resize` uses `cudaFree` that requires an array initialized using `cudaMalloc` or similar. The following code solved the problem for me.

> /*
        if (workspace_size) {
            fprintf(stderr, " Allocate additional workspace_size = %1.2f MB \n", (float)workspace_size/1000000);
            net.workspace = cuda_make_array(0, workspace_size / sizeof(float) + 1);
        }
        else {
            net.workspace = (float*)xcalloc(1, workspace_size);
        }*/
        fprintf(stderr, " Allocate additional workspace_size = %1.2f MB \n", (float)workspace_size / 1000000);
        net.workspace = cuda_make_array(0, workspace_size / sizeof(float) + 1);

@AlexeyAB tell me if it makes sense, I'm a newbie with CUDA :)
