### ISSUE TITLE
Image detection is unstable and crashes with CUDA status Error: file: ./src/dark_cuda.c : () : line: 469

### ISSUE THREAD

**Issue by aseveryn** [AlexeyAB/darknet#6844]
Hi, 
I've set up a simple Flask RPC server that uses darknet.py to detect images.
Everything works fine, and I can process hundreds of images but at some point (can be anywhere from 5-20 minutes) the program crashes with the following message:

```
CUDA status Error: file: ./src/dark_cuda.c : () : line: 469
CUDA Error: an illegal memory access was encountered
python3: : Unknown error 825294243
```

Looking at the source code of dark_cuda.c, I see that the line 469 corresponds to  CHECK_CUDA(status):
```
void cuda_push_array(float *x_gpu, float *x, size_t n)
{
    size_t size = sizeof(float)*n;
    //cudaError_t status = cudaMemcpy(x_gpu, x, size, cudaMemcpyHostToDevice);
    cudaError_t status = cudaMemcpyAsync(x_gpu, x, size, cudaMemcpyHostToDevice, get_cuda_stream());
    CHECK_CUDA(status);
}
```

Here is my setup:
```
$ nvidia-smi
Sat Oct 17 11:40:42 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    On   | 00000000:01:00.0 Off |                  N/A |
|  0%   28C    P8     5W / 151W |    155MiB /  8119MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1070    On   | 00000000:02:00.0 Off |                  N/A |
|  0%   30C    P8     5W / 151W |      6MiB /  8119MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1070    On   | 00000000:04:00.0 Off |                  N/A |
|  0%   34C    P8     5W / 151W |      6MiB /  8119MiB |      0%      Default |
|                               |                      |                  N/A |
```

**Comment by zylove006** [comment]
Hi， how do you resolve this problem？Thank you

**Comment by iljoong** [comment]
I have had a very similar issue and I found that this issues was due to flask multi-threading. You can fix this by using thread lock.

```
lock = threading.Lock()
lock.acquire()

darknet.detect_image(...)

lock.release()
```
see my implementation, https://github.com/iljoong/azure-lva/blob/master/2_Extension/darknetpy/main.py

**Comment by aseveryn** [comment]
Thanks! I resolved my problem by switching from Flask to FastApi together with Gunicorn.
