### ISSUE TITLE
CUDA Error: invalid argument: File exists

### ISSUE THREAD

**Issue by AlwaysTrying** [AlexeyAB/darknet#6919]
Hi, when I run  ./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights data/person.jpg
I got this error
![Screenshot from 2020-11-04 03-01-06](https://user-images.githubusercontent.com/5558967/98060533-1691d000-1e4a-11eb-9b33-3afad007406e.png)

any help please !!! I tried many previous suggested solutions but none was good for my case :(

**Comment by stephanecharette** [comment]
Did you mean to close it?  Did you find the cause?

Is it perhaps related to this:  https://www.ccoderun.ca/programming/2020-09-25_Darknet_FAQ/#cuda_out_of_memory

**Comment by AlwaysTrying** [comment]
thank you for your comment, yes I solved the problem , 
I had many versions of cuda in the server and the problem was in the path. I changed to the right version of cuda 10.1 in the Makefile.
