### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by Sultan29** [AlexeyAB/darknet#700]
Hello Alexey! I have this kind a problem. 
![error](https://user-images.githubusercontent.com/29767744/39251842-0cf24ad6-48c6-11e8-84d7-98f1f4320704.PNG)
Would be very happy if you help. Thanks.

**Comment by ashuezy** [comment]
https://github.com/AlexeyAB/darknet/issues/601

**Comment by Sultan29** [comment]
Thank you for response. I tried different combinations, but result is the same.

**Comment by Sultan29** [comment]
Hi,
NVIDIA Quadro 6000
Cuda 8.0 cuDNN( I don't know for sure, but probably 9.1)
darknet_coco_9000. I did dowloaded all weights and tried to change batch and subdivision. But it didn't help. Thank you for reply.

**Comment by AlexeyAB** [comment]
* Try to disabel CUDNN_HALF:
 open `\darknet.sln` -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and remove this: `CUDNN_HALF;`

* Try to disable cuDNN: 
 open `\darknet.sln` -> (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and remove this: `CUDNN;`

* Compile as **x64 & Release**

* Download yolov3-model: https://pjreddie.com/media/files/yolov3.weights
And try to run `darknet_yolo_v3.cmd`

**Comment by Sultan29** [comment]
Hi again :D 
Did everything you say and got another problem) 
CUDA Error: invalid device function 
CUDA Error: invalid device function: No error
Wanted to upload screenshoot, but something went wrong.

**Comment by EtheneXiang** [comment]
> Hi again :D
> Did everything you say and got another problem)
> CUDA Error: invalid device function
> CUDA Error: invalid device function: No error
> Wanted to upload screenshoot, but something went wrong.

hello, i met same problem while i run cmd:
darknet.exe detector test data\coco.data yolov3.cfg .\weights\yolov3.weights .\data\dog.jpg
 i do not why @AlexeyAB 

![image](https://user-images.githubusercontent.com/49241737/73726374-63853080-476a-11ea-9acc-d6ef96fe46d8.png)

![image](https://user-images.githubusercontent.com/49241737/73726311-3afd3680-476a-11ea-8fc6-6fd6bb8524b8.png)

![image](https://user-images.githubusercontent.com/49241737/73726483-9e876400-476a-11ea-9389-7d25a6f5d99b.png)

**Comment by AlexeyAB** [comment]
Did you compile **x64 & Release**

Show these 2 screenshots:

![image](https://user-images.githubusercontent.com/4096485/73742793-42b6de00-475e-11ea-98ed-6cb0bf9ca27c.png)

![image](https://user-images.githubusercontent.com/4096485/73742842-58c49e80-475e-11ea-9b4d-40ea0641c68d.png)

**Comment by EtheneXiang** [comment]
I have solved this problem
I changed the cuda10.0 to cuda10.2, then it works 
thanks@AlexeyAB

**Comment by AlexeyAB** [comment]
May be there is a bug in CUDA 10.0 for your GPU, or your CUDA was installed incorrectly.
