### ISSUE TITLE
Problems encountered during server learning

### ISSUE THREAD

**Issue by LanguageFlowCho** [AlexeyAB/darknet#7613]
Hi guys
This problem occurs after the server reboots because a problem occurs while learning in the current server.
By any chance, I removed all of the graphic drivers opencv, cudnn, and cuda, rebooted, applied, and then set again, but the problem still occurs. 

Are there any alternatives to this problem?

Currently, the server is rtx3090, Xeon E series, and Ubuntu 18.04.05 version with 32GB RAM configuration.

./darknet detector train model/car/obj.data model/car/vehicle_v1.cfg model/car/backup/vehicle_v1_last.weights
CUDA status Error: file: ./src/darknet.c : () : line: 470 : build time: Apr 18 2021 - 17:00:43 

 CUDA Error: all CUDA-capable devices are busy or unavailable
CUDA Error: all CUDA-capable devices are busy or unavailable: No such file or directory
darknet: ./src/utils.c:331: error: Assertion `0' failed.

**Comment by ekesdf** [comment]
Can you please send a screenshot from the full training output thy or copy it in a TXT file and upload it.
And a screenshot from nvidia-smi while training

**Comment by LanguageFlowCho** [comment]
Hello, thank you for your reply. However, regarding CUDA, it was solved by re-installing Ubuntu after formatting. I want to close the answer, is it okay?
