### ISSUE TITLE
error during compilation 

### ISSUE THREAD

**Issue by vulkomilev** [AlexeyAB/darknet#7637]
During the compilation of the project I got the following error : 

CUDA status Error: file: ./src/darknet.c : () : line: 470 : build time: Apr 22 2021 - 09:36:51 

 CUDA Error: the provided PTX was compiled with an unsupported toolchain.
CUDA Error: the provided PTX was compiled with an unsupported toolchain.: Success
darknet: ./src/utils.c:331: error: Assertion `0' failed.
Aborted (core dumped)

System : 
ubuntu 20.04
5950x
3080

**Comment by PetrDvoracek** [comment]
Same problem on **Manjaro 21.0.4**, **CUDA 11.3**, **CUDNN 8.2**  **RTX 3060** (laptop), nvidia driver: **2020.11.30** closed source

**Comment by skuda** [comment]
Hi,

I had the same problem while trying to run training in an RTX 3080, for me the problem was that cmake was not correctly detecting the Cuda architecture to compile for, like this:

``` shell
-- Selected CMAKE_CUDA_ARCHITECTURES: 52
-- Your setup does not support half precision (it requires CUDA_ARCHITECTURES >= 70)
```

So I modified CmakeLists.txt, adding this set:
``` shell
set(CMAKE_CUDA_ARCHITECTURES 86 CACHE STRING "CUDA architectures" FORCE)
      message(STATUS "Selected CMAKE_CUDA_ARCHITECTURES: ${CMAKE_CUDA_ARCHITECTURES}")
      if(70 IN_LIST CMAKE_CUDA_ARCHITECTURES OR
         72 IN_LIST CMAKE_CUDA_ARCHITECTURES OR
         75 IN_LIST CMAKE_CUDA_ARCHITECTURES OR
         80 IN_LIST CMAKE_CUDA_ARCHITECTURES OR
         86 IN_LIST CMAKE_CUDA_ARCHITECTURES)
        set(ENABLE_CUDNN_HALF "TRUE" CACHE BOOL "Enable CUDNN Half precision" FORCE)
        message(STATUS "Your setup supports half precision (CUDA_ARCHITECTURES >= 70)")
```

Now it works correctly.

**Comment by cenit** [comment]
If cmake automatically selects a wrong/unsupported architecture, you can manually select the CMake cuda architecture also with build script passing a 

```
-AdditionalBuildFlags -DCMAKE_CUDA_ARCHITECTURES=86
```

so the line would be

```
./build.ps1 -EnableOPENCV -EnableCUDA -EnableCUDNN -AdditionalBuildFlags -DCMAKE_CUDA_ARCHITECTURES=86

**Comment by cenit** [comment]
if you call cmake directly yes

if you use the build.ps1 wrapper (it works also on linux) you have to pass the flags as i wrote

**Comment by Goru1890** [comment]
@cenit I think I have the same issue, does it works now also with vcpkg?

**Comment by cenit** [comment]
of course, your build line will be

```
./build.ps1 -UseVCPKG -EnableOPENCV -EnableCUDA -EnableCUDNN -AdditionalBuildFlags -DCMAKE_CUDA_ARCHITECTURES=86
```

**Comment by cenit** [comment]
note the additional `-UseVCPKG`

**Comment by Goru1890** [comment]
does it work I install darknet on my vckpg local repo with vcpkg install darknet... ?

**Comment by Goru1890** [comment]
> of course, your build line will be
> 
> ```
> ./build.ps1 -UseVCPKG -EnableOPENCV -EnableCUDA -EnableCUDNN -AdditionalBuildFlags -DCMAKE_CUDA_ARCHITECTURES=86
> ```

Will that command reinstall my current darknet installation on my vcpkg folder in `C:\` which I installed time ago with a `.\vcpkg install darknet` ?

**Comment by Goru1890** [comment]
It still doesn't work for me, still having the same issue as above. 

I have a 3060(laptop)

**Comment by cenit** [comment]
nope, in your case it's better if you clone darknet outside of vcpkg, and use vcpkg only for darknet dependencies

```
git clone https://github.com/AlexeyAB/darknet
cd darknet
.\build.ps1 .....
```￼

**Comment by Goru1890** [comment]
![image](https://user-images.githubusercontent.com/35274844/127619010-0f67caf1-bd94-4916-b114-9e18a33f67c9.png)

**Comment by cenit** [comment]
3060 mobile should be cc 8.6, strange that it does not work for you.
can you share full logs about the build, start to end?

**Comment by Goru1890** [comment]
> 3060 mobile should be cc 8.6, strange that it does not work for you.
> can you share full logs about the build, start to end?

Do you mean the logs that I can find in `C:\vcpkg\buildtrees\darknet` ?

**Comment by Goru1890** [comment]
[config-x64-windows-dbg-out.log](https://github.com/AlexeyAB/darknet/files/6906185/config-x64-windows-dbg-out.log)
 I found this one, but I think this is from a darknet installation I made directly inside vcpkg.

**Comment by cenit** [comment]
no what I mean is from. \build.ps1 command to the build complete output

**Comment by Goru1890** [comment]
[log.txt](https://github.com/AlexeyAB/darknet/files/6907073/log.txt)

**Comment by cenit** [comment]
-- Selected CMAKE_CUDA_ARCHITECTURES: 52

something is not working in your case, please let me investigate what might be happening

**Comment by Goru1890** [comment]
Were you able to find a solution? If you, I think I can just compile darknet manually.

**Comment by cenit** [comment]
I cannot reproduce the error, but also i had some very busy days. Did you try anything more? you can edit the build script and add the -DCMAKE_CUDA_ARCHITECTURE=80 at the end in the cmake_sega variable manually if you are in a hurry

**Comment by Goru1890** [comment]
I tried that and I'm still having the same issue.
I will try to compile it tomorrow manually.

3060 doesn't look like it's supported on the Makefile.

**Comment by cenit** [comment]
Makefile on windows is unsupported. What do you mean compile manually??

**Comment by Goru1890** [comment]
I mean instead of using the powershell script I could try to use visual code and cmake just how it's described in the readme to compile darknet.

**Comment by Goru1890** [comment]
Sorry @cenit for making so many questions but do you know why cmake didn't find cuda?

![image](https://user-images.githubusercontent.com/35274844/128563675-db23d8c0-803f-4632-b024-285e7ed7e0bf.png)

**Comment by cenit** [comment]
seems like you are not using ninja and "visual studio integration for cuda" is not installed (part of cuda installation)

**Comment by Goru1890** [comment]
I just reinstalled cuda but I have now a problem with opencv

![image](https://user-images.githubusercontent.com/35274844/128594203-3805e3f8-afac-42c4-a6a4-b1a490f9b031.png)

But I have opencv installed with vcpkg 

![image](https://user-images.githubusercontent.com/35274844/128594219-4cd270ba-0cf3-4a61-8d41-4986ac87f3f0.png)

**Comment by Goru1890** [comment]
![image](https://user-images.githubusercontent.com/35274844/128594556-9392b1bb-5f9e-4d0d-93d5-0dab2aefa65e.png)
 
Selected CMAKE_CUDA_ARCHITECTURES: 52

Seems like I have the same issue here.

**Comment by cenit** [comment]
yes, you need to manually define it on cache on a different value and then it will be valid. It is very strange that the additional build options on command line does not work on your setup. I had not much time to do better diagnose but still i think we should work on that front. Sorry for being late but it's a very busy time for me

**Comment by Goru1890** [comment]
Sorry I had a busy time. How can I define it on cache?

**Comment by willSapgreen** [comment]
I had the same problem and here is my solution. Hopefully it is helpful and please let me know if you need more information or any questions.

**OS: Window 10 Pro for Workstations, Version 20H2
GPU: Turing T1200 (Based on https://en.wikipedia.org/wiki/CUDA, compute capability version is 7.5)
Visual Studio: 2019 professional version
CUDA: v11.3.1
cuDNN: v8.2.1.32
CMake: 3.21.1
OpenCV 4.5.2
darknet commit hash: b8dceb7ed055b1ab2094bdbd0756b61473db3ef6**

Like @Goru1890  pointed out,
the default value for CMAKE_CUDA_ARCHITECTURES in CMake GUI is **52**.
I manually changed it to **75** for my GPU, and "Configure" -> "Generate" -> "Open Project" in CMake GUI.
Then I rebuilt darknet in Visual Studio and the issue is resolved.

**Comment by shanhuaton** [comment]
I had the same problem like
` CUDA Error: the provided PTX was compiled with an unsupported toolchain.
`
and my solution is update my NVIDIA Driver from https://www.nvidia.com/Download/index.aspx?lang=en-us#
OS:windows10
GPU:RTX 3070(laptop)
CUDA:v11.7.0
cuDNN:v8.4.0.27
