### ISSUE TITLE
CUDA Error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by stephanecharette** [AlexeyAB/darknet#7850]
Did a "git pull" today in my darknet directory to grab the most recent changes.  When I go to train with this new version, I get this error as soon as training hits 1000 iterations and it attempts to calculate mAP:

```
 Tensor Cores are disabled until the first 3000 iterations are reached.
Loaded: 0.000041 seconds
 (next mAP calculation at 1000 iterations) 
 1000: 7.182863, 7.897405 avg loss, 0.000100 rate, 0.384910 seconds, 64000 images, 2.178889 hours left
4CUDA Error: an illegal memory access was encountered: Success
darknet: ./src/utils.c:331: error: Assertion `0' failed.
Command terminated by signal 6
```

Training command and all training files, images, annotations are from an existing project that hasn't changed in the last few months, so I'm certain things are correct.

Training command is:  `/home/stephane/darknet/darknet detector -map -dont_show train /home/stephane/nn/mailboxes/mailboxes.data /home/stephane/nn/mailboxes/mailboxes.cfg`

Configuration is yolov4-tiny.

Darknet version I'm using is this:

```
> git log -1
commit 86ced7151a71c05fab57bc14f77d6a4bb97b9ee6 (HEAD -> master, origin/master, origin/HEAD)
Author: Alexey <AlexeyAB@users.noreply.github.com>
Date:   Wed Jun 30 06:51:24 2021 +0300
    Update README.md
```

Makefile contains these changes:

```
-GPU=0
-CUDNN=0
-CUDNN_HALF=0
-OPENCV=0
+GPU=1
+CUDNN=1
+CUDNN_HALF=1
+OPENCV=1
 AVX=0
-OPENMP=0
-LIBSO=0
+OPENMP=1
+LIBSO=1
```

Ubuntu 20.04 with these relevant libs installed:

```
> dpkg -l | egrep "opencv-dev|cuda |cudnn.-dev"
ii  cuda                                          11.3.1-1                                          amd64        CUDA meta-package
ii  libcudnn8-dev                                 8.2.0.53-1+cuda11.3                               amd64        cuDNN development libraries and headers
ii  libopencv-dev                                 3.2.0+dfsg-4ubuntu0.1                             amd64        development files for opencv
```

GPU is NVidia RTX 2070:

```
> nvidia-smi 
Thu Jul  1 14:38:32 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| 37%   34C    P8    27W / 175W |     16MiB /  7981MiB |      0%      Default |
```

**Comment by stephanecharette** [comment]
Noticed that CUDA 11.4 is now available, and my GPU rig hadn't been rebooted in 26 days.

Upgraded from CUDA 11.3 to 11.4, installed other updates, and rebooted the server.  Rebuild darknet.  (Is that required after upgrading CUDA?  I have no idea.)

```
> dpkg -l | egrep "opencv-dev|cuda |cudnn.-dev"
ii  cuda                                          11.4.0-1                                          amd64        CUDA meta-package
ii  libcudnn8-dev                                 8.2.1.32-1+cuda11.3                               amd64        cuDNN development libraries and headers
ii  libopencv-dev                                 3.2.0+dfsg-4ubuntu0.1                             amd64        development files for opencv
```

Same problem still exists.  Darknet crashes as soon as I get to iteration 1000:

```
 Tensor Cores are disabled until the first 3000 iterations are reached.
Loaded: 0.000041 seconds

 (next mAP calculation at 1000 iterations) 
 1000: 10.328301, 8.518983 avg loss, 0.000100 rate, 0.413506 seconds, 64000 images, 2.186883 hours left
4CUDA Error: an illegal memory access was encountered: Success
darknet: ./src/utils.c:331: error: Assertion `0' failed.
```

**Comment by stephanecharette** [comment]
@AlexeyAB :

Checked out several commits and tried to train.  These ones fail with the error described above:

- 86ced7151a71c05fab57bc14f77d6a4bb97b9ee6 (2021-06-29)
- 97ccee56283ad92118153f0cd1036d1ea07ba115 (2021-06-29)
- 85c6278ef1f8a0bed424567c5ac86da44a65474a (2021-06-29)
- 24bb6a8ebf5ec32bff4f30ec0801d9a9a9fca3f6 (2021-06-29)

These ones are working correctly:

- 9a86fce494b1d82b774d36be76747fcb58f81aa4 (2021-06-26)
- 28952006b010146344319fd14f9e41b5ee5d828b (2021-06-26)

So from what I can tell, the problem started with commit 24bb6a8ebf5ec32bff4f30ec0801d9a9a9fca3f6 on June 29.

**Comment by JeremyKeusters** [comment]
I seem to be having the same issue in #4655 ! Also with a YOLOv4-tiny. Increasing the subdivisions helped for me.

**Comment by AlexeyAB** [comment]
@JeremyKeusters @stephanecharette Hi,
I fixed this bug. Try the latest commit.

**Comment by stephanecharette** [comment]
This is not fixed for me, @AlexeyAB.  I'm using:

```
> git log -1
commit 335ac662c84421982ca3a54a47e64926b88297d5 (HEAD -> master, origin/master, origin/HEAD)
Author: AlexeyAB <kikots@mail.ru>
Date:   Sat Jul 3 04:46:55 2021 +0300
    Improved [net] optimized_memory=1 to reduce GPU memory usage.
```

As soon as it gets to 1000 iterations during training, I see the same error as reported above:

```
 Tensor Cores are disabled until the first 3000 iterations are reached.
Loaded: 0.000042 seconds

 (next mAP calculation at 1000 iterations) 
 1000: 5.749605, 4.749646 avg loss, 0.002610 rate, 0.419783 seconds, 64000 images, 2.186135 hours left
4CUDA Error: an illegal memory access was encountered: Success
darknet: ./src/utils.c:331: error: Assertion `0' failed.
```

**Comment by AlexeyAB** [comment]
@stephanecharette 

I just can't reproduce this issue.

Can you share your cfg-file? 
Do you use `optimized_memory=1` param or not in cfg-file?
Do you use `stopbackward=1` param or not in cfg-file?

Do you get this issue if you comment these lines? 
* https://github.com/AlexeyAB/darknet/blob/335ac662c84421982ca3a54a47e64926b88297d5/src/parser.c#L1698-L1713
* https://github.com/AlexeyAB/darknet/blob/335ac662c84421982ca3a54a47e64926b88297d5/src/parser.c#L1433-L1434
* https://github.com/AlexeyAB/darknet/blob/335ac662c84421982ca3a54a47e64926b88297d5/src/parser.c#L1413-L1428

**Comment by AlexeyAB** [comment]
@stephanecharette I added another 2 possible fixes: https://github.com/AlexeyAB/darknet/commit/be3985210ed336477b2e1317fd13c6cf1494adb1 and https://github.com/AlexeyAB/darknet/commit/005513a9db14878579adfbb61083962c99bb0a89

**Comment by stephanecharette** [comment]
> Can you share your cfg-file?

Yes, please see attached.

> Do you use `optimized_memory=1` param or not in cfg-file?
> Do you use `stopbackward=1` param or not in cfg-file?

Never heard of either of those 2 settings.  I checked in the .cfg file and I don't have either of them.  My cfg file is very close to the normal yolov4-tiny.cfg, with the exception of max_batches, steps, mosaic, filters, and classes.  The usual settings people customize.

I tried the latest changes:

- 335ac662c84421982ca3a54a47e64926b88297d5 crashes when it gets to 1000
- be3985210ed336477b2e1317fd13c6cf1494adb1 this is the first commit that works for me since June 26
- 005513a9db14878579adfbb61083962c99bb0a89 this commit also works for me

[mailboxes.cfg.txt](https://github.com/AlexeyAB/darknet/files/6759405/mailboxes.cfg.txt)

**Comment by AlexeyAB** [comment]
@stephanecharette Thanks! As I understand it, this bug is fixed.

**Comment by jmp1986** [comment]
Sorry: Still getting this error...

<img width="1074" alt="Error" src="https://user-images.githubusercontent.com/21009656/124808563-62f45900-df5f-11eb-9473-0db9e8f5c515.png">

My Tensorflow and Cuda Version:

<img width="849" alt="Tensorflow-Version" src="https://user-images.githubusercontent.com/21009656/124808574-6556b300-df5f-11eb-9590-e15732e571c0.png">
<img width="764" alt="Cuda-Version" src="https://user-images.githubusercontent.com/21009656/124808561-612a9580-df5f-11eb-9fe2-f496c38abc09.png">

What to do?

**Comment by jmp1986** [comment]
> I seem to be having the same issue in #4655 ! Also with a YOLOv4-tiny. Increasing the subdivisions helped for me.

I did the same thing using tiny-yolov4 now (changed subdivisions=1 to 8). I hope this helps.

**Comment by tamim662** [comment]
> @AlexeyAB I tried with two latest commit changes, but still, get an error when it reached 1000 iterations.
![azure_model_train_problem](https://user-images.githubusercontent.com/34623418/128641758-415c9b0a-4deb-4282-aab9-bfde90234d1b.png)
 Can you please help me out to solve this problem?

**Comment by jmp1986** [comment]
Oh, sorry. I forgot to give feedback again.

@tamim662: Changing the subdivisions from 1 to 8 actually fixed it for me - for whatever reason.

**Comment by tamim662** [comment]
> Oh, sorry. I forgot to give feedback again.
> 
> @tamim662: Changing the subdivisions from 1 to 8 actually fixed it for me - for whatever reason.

I already assign subdivision to 16. But it didn't solve the issue.

**Comment by jmp1986** [comment]
Then I'm afraid I'll have to pass on to @AlexeyAB or someone else. I hope someone can help you (and others) with the problem.

**Comment by ugogalassi** [comment]
I confirm, the problem still occurs and can be avoided by increasing the value of the subdivision field. Which value to use depends on the model.

**Comment by tamim662** [comment]
The problem is now solved by removing -map end of the command. But before upgrading CUDA 11.4 version it worked well as I trained the same model just three weeks ago even using -map also.

**Comment by AlexeyAB** [comment]
@tamim662 So is the issue CUDA 11.4? What CUDA version did you use previously?

**Comment by ugogalassi** [comment]
Hi @AlexeyAB 

The bug is still present.

I use Cuda 10.1.
The model that i'm training is yolo4-tiny (2layers) customized to work with 3 custom classes on grayscale images. It is trained from scratch.

```
batch=64
subdivisions=1
width=416
height=416
channels=1
```
[yolov4-tiny2l.cfg.txt](https://github.com/AlexeyAB/darknet/files/6974566/yolov4-tiny2l.cfg.txt)


It crashes during mAP calculation. 
Increasing subdivision the error doesn't occur. [i.e., subdivision=4]


I launched the training with : `-map -cuda_debug_sync -benchmark_layers`
Here last lines of the output, hoping it could help.


```
 (next mAP calculation at 1169 iterations) 
 1168: 0.799702, 0.624902 avg loss, 0.002610 rate, 0.366392 seconds, 74752 images, 10.194199 hours left
known client: 26, sent = 182179, must be sent outlen = 182179
 MJPEG-stream sent. 
Loaded: 0.000055 seconds

 fw-layer 0 - type: 0 - 5.970000 ms - avg_time 6.060557 ms 

 fw-layer 1 - type: 0 - 4.598000 ms - avg_time 4.708131 ms 

 fw-layer 2 - type: 0 - 7.630000 ms - avg_time 7.734545 ms 

 fw-layer 3 - type: 9 - 2.041000 ms - avg_time 1.999546 ms 

 fw-layer 4 - type: 0 - 2.651000 ms - avg_time 2.627685 ms 

 fw-layer 5 - type: 0 - 2.679000 ms - avg_time 2.622149 ms 

 fw-layer 6 - type: 9 - 5.218000 ms - avg_time 4.376945 ms 

 fw-layer 7 - type: 0 - 3.477000 ms - avg_time 3.372345 ms 

 fw-layer 8 - type: 9 - 4.732000 ms - avg_time 4.641015 ms 

 fw-layer 9 - type: 3 - 1.027000 ms - avg_time 1.029394 ms 

 fw-layer 10 - type: 0 - 4.676000 ms - avg_time 4.653883 ms 

 fw-layer 11 - type: 9 - 2.108000 ms - avg_time 1.800954 ms 

 fw-layer 12 - type: 0 - 2.050000 ms - avg_time 2.057398 ms 

 fw-layer 13 - type: 0 - 2.026000 ms - avg_time 2.053456 ms 

 fw-layer 14 - type: 9 - 4.375000 ms - avg_time 3.558608 ms 

 fw-layer 15 - type: 0 - 1.986000 ms - avg_time 2.024914 ms 

 fw-layer 16 - type: 9 - 4.480000 ms - avg_time 4.486966 ms 

 fw-layer 17 - type: 3 - 0.545000 ms - avg_time 0.550651 ms 

 fw-layer 18 - type: 0 - 4.536000 ms - avg_time 4.549547 ms 

 fw-layer 19 - type: 9 - 2.201000 ms - avg_time 1.690275 ms 

 fw-layer 20 - type: 0 - 1.404000 ms - avg_time 1.428520 ms 

 fw-layer 21 - type: 0 - 1.406000 ms - avg_time 1.415528 ms 

 fw-layer 22 - type: 9 - 2.944000 ms - avg_time 3.559832 ms 

 fw-layer 23 - type: 0 - 1.372000 ms - avg_time 1.340063 ms 

 fw-layer 24 - type: 9 - 2.641000 ms - avg_time 3.484157 ms 

 fw-layer 25 - type: 3 - 0.314000 ms - avg_time 0.306412 ms 

 fw-layer 26 - type: 0 - 3.262000 ms - avg_time 3.231166 ms 

 fw-layer 27 - type: 0 - 0.673000 ms - avg_time 0.643950 ms 

 fw-layer 28 - type: 0 - 2.037000 ms - avg_time 1.947378 ms 

 fw-layer 29 - type: 0 - 0.250000 ms - avg_time 0.212122 ms 
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 30 Avg (IOU: 0.568153), count: 12, class_loss = 0.236714, iou_loss = 0.099899, total_loss = 0.336613 

 fw-layer 30 - type: 28 - 20.261000 ms - avg_time 18.607000 ms 

 fw-layer 31 - type: 9 - 1.491000 ms - avg_time 1.643160 ms 

 fw-layer 32 - type: 0 - 0.411000 ms - avg_time 0.362922 ms 

 fw-layer 33 - type: 33 - 0.279000 ms - avg_time 0.265410 ms 

 fw-layer 34 - type: 9 - 3.329000 ms - avg_time 3.484488 ms 

 fw-layer 35 - type: 0 - 6.345000 ms - avg_time 6.335190 ms 

 fw-layer 36 - type: 0 - 0.195000 ms - avg_time 0.214594 ms 
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 37 Avg (IOU: 0.575062), count: 42, class_loss = 0.742304, iou_loss = 4.362844, total_loss = 5.105147 

 fw-layer 37 - type: 28 - 25.866000 ms - avg_time 25.554409 ms 


Sorted by time (forward):
0 - fw-sort-layer 37 - type: 28 - avg_time 25.554409 ms 
1 - fw-sort-layer 30 - type: 28 - avg_time 18.607000 ms 
2 - fw-sort-layer 2 - type: 0 - avg_time 7.734545 ms 
3 - fw-sort-layer 35 - type: 0 - avg_time 6.335190 ms 
4 - fw-sort-layer 0 - type: 0 - avg_time 6.060557 ms 
5 - fw-sort-layer 1 - type: 0 - avg_time 4.708131 ms 
6 - fw-sort-layer 10 - type: 0 - avg_time 4.653883 ms 
7 - fw-sort-layer 8 - type: 9 - avg_time 4.641015 ms 
8 - fw-sort-layer 18 - type: 0 - avg_time 4.549547 ms 
9 - fw-sort-layer 16 - type: 9 - avg_time 4.486966 ms 
10 - fw-sort-layer 6 - type: 9 - avg_time 4.376945 ms 
11 - fw-sort-layer 22 - type: 9 - avg_time 3.559832 ms 
12 - fw-sort-layer 14 - type: 9 - avg_time 3.558608 ms 
13 - fw-sort-layer 34 - type: 9 - avg_time 3.484488 ms 
14 - fw-sort-layer 24 - type: 9 - avg_time 3.484157 ms 
15 - fw-sort-layer 7 - type: 0 - avg_time 3.372345 ms 
16 - fw-sort-layer 26 - type: 0 - avg_time 3.231166 ms 
17 - fw-sort-layer 4 - type: 0 - avg_time 2.627685 ms 
18 - fw-sort-layer 5 - type: 0 - avg_time 2.622149 ms 
19 - fw-sort-layer 12 - type: 0 - avg_time 2.057398 ms 
20 - fw-sort-layer 13 - type: 0 - avg_time 2.053456 ms 
21 - fw-sort-layer 15 - type: 0 - avg_time 2.024914 ms 
22 - fw-sort-layer 3 - type: 9 - avg_time 1.999546 ms 
23 - fw-sort-layer 28 - type: 0 - avg_time 1.947378 ms 
24 - fw-sort-layer 11 - type: 9 - avg_time 1.800954 ms 
25 - fw-sort-layer 19 - type: 9 - avg_time 1.690275 ms 
26 - fw-sort-layer 31 - type: 9 - avg_time 1.643160 ms 
27 - fw-sort-layer 20 - type: 0 - avg_time 1.428520 ms 
28 - fw-sort-layer 21 - type: 0 - avg_time 1.415528 ms 
29 - fw-sort-layer 23 - type: 0 - avg_time 1.340063 ms 
30 - fw-sort-layer 9 - type: 3 - avg_time 1.029394 ms 
31 - fw-sort-layer 27 - type: 0 - avg_time 0.643950 ms 
32 - fw-sort-layer 17 - type: 3 - avg_time 0.550651 ms 
33 - fw-sort-layer 32 - type: 0 - avg_time 0.362922 ms 
34 - fw-sort-layer 25 - type: 3 - avg_time 0.306412 ms 
35 - fw-sort-layer 33 - type: 33 - avg_time 0.265410 ms 
36 - fw-sort-layer 36 - type: 0 - avg_time 0.214594 ms 
37 - fw-sort-layer 29 - type: 0 - avg_time 0.212122 ms 

 bw-layer 37 - type: 28 - 0.071000 ms - avg_time 0.074299 ms 

 bw-layer 36 - type: 0 - 0.828000 ms - avg_time 0.835175 ms 

 bw-layer 35 - type: 0 - 9.614000 ms - avg_time 9.583383 ms 

 bw-layer 34 - type: 9 - 3.999000 ms - avg_time 3.900512 ms 

 bw-layer 33 - type: 33 - 0.183000 ms - avg_time 0.184268 ms 

 bw-layer 32 - type: 0 - 0.644000 ms - avg_time 0.673031 ms 

 bw-layer 31 - type: 9 - 2.777000 ms - avg_time 1.906915 ms 

 bw-layer 30 - type: 28 - 0.064000 ms - avg_time 0.043629 ms 

 bw-layer 29 - type: 0 - 0.571000 ms - avg_time 0.511652 ms 

 bw-layer 28 - type: 0 - 3.697000 ms - avg_time 3.806623 ms 

 bw-layer 27 - type: 0 - 1.273000 ms - avg_time 1.246623 ms 

 bw-layer 26 - type: 0 - 6.117000 ms - avg_time 6.157737 ms 

 bw-layer 25 - type: 3 - 0.805000 ms - avg_time 0.855727 ms 

 bw-layer 24 - type: 9 - 4.105000 ms - avg_time 3.992277 ms 

 bw-layer 23 - type: 0 - 2.511000 ms - avg_time 2.566774 ms 

 bw-layer 22 - type: 9 - 2.867000 ms - avg_time 3.704263 ms 

 bw-layer 21 - type: 0 - 2.733000 ms - avg_time 2.730622 ms 

 bw-layer 20 - type: 0 - 2.740000 ms - avg_time 2.737818 ms 

 bw-layer 19 - type: 9 - 1.597000 ms - avg_time 1.890723 ms 

 bw-layer 18 - type: 0 - 6.970000 ms - avg_time 7.025948 ms 

 bw-layer 17 - type: 3 - 1.500000 ms - avg_time 1.560316 ms 

 bw-layer 16 - type: 9 - 4.842000 ms - avg_time 5.002291 ms 

 bw-layer 15 - type: 0 - 3.959000 ms - avg_time 3.974248 ms 

 bw-layer 14 - type: 9 - 4.164000 ms - avg_time 4.242882 ms 

 bw-layer 13 - type: 0 - 4.092000 ms - avg_time 3.974245 ms 

 bw-layer 12 - type: 0 - 4.067000 ms - avg_time 3.981975 ms 

 bw-layer 11 - type: 9 - 2.115000 ms - avg_time 2.120107 ms 

 bw-layer 10 - type: 0 - 11.366000 ms - avg_time 11.444599 ms 

 bw-layer 9 - type: 3 - 2.968000 ms - avg_time 3.007167 ms 

 bw-layer 8 - type: 9 - 6.393000 ms - avg_time 6.044023 ms 

 bw-layer 7 - type: 0 - 7.484000 ms - avg_time 7.460224 ms 

 bw-layer 6 - type: 9 - 5.485000 ms - avg_time 5.046196 ms 

 bw-layer 5 - type: 0 - 6.130000 ms - avg_time 6.268665 ms 

 bw-layer 4 - type: 0 - 6.153000 ms - avg_time 6.488886 ms 

 bw-layer 3 - type: 9 - 2.758000 ms - avg_time 2.683299 ms 

 bw-layer 2 - type: 0 - 16.560000 ms - avg_time 16.682543 ms 

 bw-layer 1 - type: 0 - 21.292000 ms - avg_time 21.146132 ms 

 bw-layer 0 - type: 0 - 10.172000 ms - avg_time 10.272852 ms 


Sorted by time (backward):
0 - bw-sort-layer 1 - type: 0 - avg_time 21.146132 ms 
1 - bw-sort-layer 2 - type: 0 - avg_time 16.682543 ms 
2 - bw-sort-layer 10 - type: 0 - avg_time 11.444599 ms 
3 - bw-sort-layer 0 - type: 0 - avg_time 10.272852 ms 
4 - bw-sort-layer 35 - type: 0 - avg_time 9.583383 ms 
5 - bw-sort-layer 7 - type: 0 - avg_time 7.460224 ms 
6 - bw-sort-layer 18 - type: 0 - avg_time 7.025948 ms 
7 - bw-sort-layer 4 - type: 0 - avg_time 6.488886 ms 
8 - bw-sort-layer 5 - type: 0 - avg_time 6.268665 ms 
9 - bw-sort-layer 26 - type: 0 - avg_time 6.157737 ms 
10 - bw-sort-layer 8 - type: 9 - avg_time 6.044023 ms 
11 - bw-sort-layer 6 - type: 9 - avg_time 5.046196 ms 
12 - bw-sort-layer 16 - type: 9 - avg_time 5.002291 ms 
13 - bw-sort-layer 14 - type: 9 - avg_time 4.242882 ms 
14 - bw-sort-layer 24 - type: 9 - avg_time 3.992277 ms 
15 - bw-sort-layer 12 - type: 0 - avg_time 3.981975 ms 
16 - bw-sort-layer 15 - type: 0 - avg_time 3.974248 ms 
17 - bw-sort-layer 13 - type: 0 - avg_time 3.974245 ms 
18 - bw-sort-layer 34 - type: 9 - avg_time 3.900512 ms 
19 - bw-sort-layer 28 - type: 0 - avg_time 3.806623 ms 
20 - bw-sort-layer 22 - type: 9 - avg_time 3.704263 ms 
21 - bw-sort-layer 9 - type: 3 - avg_time 3.007167 ms 
22 - bw-sort-layer 20 - type: 0 - avg_time 2.737818 ms 
23 - bw-sort-layer 21 - type: 0 - avg_time 2.730622 ms 
24 - bw-sort-layer 3 - type: 9 - avg_time 2.683299 ms 
25 - bw-sort-layer 23 - type: 0 - avg_time 2.566774 ms 
26 - bw-sort-layer 11 - type: 9 - avg_time 2.120107 ms 
27 - bw-sort-layer 31 - type: 9 - avg_time 1.906915 ms 
28 - bw-sort-layer 19 - type: 9 - avg_time 1.890723 ms 
29 - bw-sort-layer 17 - type: 3 - avg_time 1.560316 ms 
30 - bw-sort-layer 27 - type: 0 - avg_time 1.246623 ms 
31 - bw-sort-layer 25 - type: 3 - avg_time 0.855727 ms 
32 - bw-sort-layer 36 - type: 0 - avg_time 0.835175 ms 
33 - bw-sort-layer 32 - type: 0 - avg_time 0.673031 ms 
34 - bw-sort-layer 29 - type: 0 - avg_time 0.511652 ms 
35 - bw-sort-layer 33 - type: 33 - avg_time 0.184268 ms 
36 - bw-sort-layer 37 - type: 28 - avg_time 0.074299 ms 
37 - bw-sort-layer 30 - type: 28 - avg_time 0.043629 ms 
 total_bbox = 76372, rewritten_bbox = 2.058346 % 

 (next mAP calculation at 1169 iterations) 
 1169: 0.489977, 0.611409 avg loss, 0.002610 rate, 0.373444 seconds, 74816 images, 10.192861 hours left

 calculation mAP (mean average precision)...
 Detection layer: 30 - type = 28 
 Detection layer: 37 - type = 28 
4
 fw-layer 0 - type: 0 - 0.402000 ms - avg_time 5.494701 ms 

 fw-layer 1 - type: 0 - 0.328000 ms - avg_time 4.270118 ms 

 fw-layer 2 - type: 0 - 1.096000 ms - avg_time 7.070690 ms 

 fw-layer 3 - type: 9 - 0.038000 ms - avg_time 1.803392 ms 

 fw-layer 4 - type: 0 - 0.311000 ms - avg_time 2.396017 ms 

 fw-layer 5 - type: 0 - 0.299000 ms - avg_time 2.389834 ms 

 fw-layer 6 - type: 9 - 0.068000 ms - avg_time 3.946050 ms 

 fw-layer 7 - type: 0 - 0.234000 ms - avg_time 3.058511 ms 

 fw-layer 8 - type: 9 - 0.101000 ms - avg_time 4.187014 ms 

 fw-layer 9 - type: 3 - 0.089000 ms - avg_time 0.935354 ms 

 cudaError_t status = cudaDeviceSynchronize() Error in: file: /home/akita/sources/darknet/src/convolutional_kernels.cu : () : line: 555 : build time: Jul 24 2021 - 12:15:00 
CUDA status = cudaDeviceSynchronize() Error: file: /home/akita/sources/darknet/src/dark_cuda.c : () : line: 46 : build time: Jul 24 2021 - 12:14:30 

 CUDA Error: an illegal memory access was encountered
Darknet error location: /home/akita/sources/darknet/src/dark_cuda.c, check_error, line #70
CUDA Error: an illegal memory access was encountered: File exists
Close socket: out = 0, in = 0 
MJPG_sender: close clinet: 0 
Close socket: out = 0, in = 0 
MJPG_sender: close acceptor: 0 
```

Thanks!

**Comment by tamim662** [comment]
> @tamim662 So is the issue CUDA 11.4? What CUDA version did you use previously?

I think so. Before using CUDA 11.4 I was working on CUDA 10.2, 11.0, and that time it worked well.

**Comment by Sisetus** [comment]
Hi @AlexeyAB ,

I am also facing a similar problem with CUDA 11.1, GTX 3090, Windows 10:

```
\Desktop\darknet\build\darknet\x64>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.relgpu_drvr455TC455_06.29069683_0
```

I use the yolo v4 custom with 1 class. My .cfg (no big changes, just usual to make it work with 1 class) [yolo-obj.cfg.txt](https://github.com/AlexeyAB/darknet/files/7007651/yolo-obj.cfg.txt)

The beginning:

```

\Desktop\darknet\build\darknet\x64>darknet.exe detector train data/obj.data yolo-obj.cfg backup\yolo-obj_last.weights
 CUDA-version: 11010 (11040), cuDNN: 8.2.1, CUDNN_HALF=1, GPU count: 1
 CUDNN_HALF=1
 OpenCV version: 3.4.15
yolo-obj
 0 : compute_capability = 860, cudnn_half = 1, GPU: NVIDIA GeForce RTX 3090
net.optimized_memory = 0
mini_batch = 2, batch = 64, time_steps = 1, train = 1
   layer   filters  size/strd(dil)      input                output
   0 Create CUDA-stream - 0
 Create cudnn-handle 0
conv     32       3 x 3/ 1    768 x 768 x   3 ->  768 x 768 x  32 1.019 BF
   1 conv     64       3 x 3/ 2    768 x 768 x  32 ->  384 x 384 x  64 5.436 BF
   2 conv     64       1 x 1/ 1    384 x 384 x  64 ->  384 x 384 x  64 1.208 BF
   3 route  1                                      ->  384 x 384 x  64
   4 conv     64       1 x 1/ 1    384 x 384 x  64 ->  384 x 384 x  64 1.208 BF
   5 conv     32       1 x 1/ 1    384 x 384 x  64 ->  384 x 384 x  32 0.604 BF
   6 conv     64       3 x 3/ 1    384 x 384 x  32 ->  384 x 384 x  64 5.436 BF
   7 Shortcut Layer: 4,  wt = 0, wn = 0, outputs: 384 x 384 x  64 0.009 BF
   8 conv     64       1 x 1/ 1    384 x 384 x  64 ->  384 x 384 x  64 1.208 BF
   9 route  8 2                                    ->  384 x 384 x 128
  10 conv     64       1 x 1/ 1    384 x 384 x 128 ->  384 x 384 x  64 2.416 BF
  11 conv    128       3 x 3/ 2    384 x 384 x  64 ->  192 x 192 x 128 5.436 BF
  12 conv     64       1 x 1/ 1    192 x 192 x 128 ->  192 x 192 x  64 0.604 BF
  13 route  11                                     ->  192 x 192 x 128
  14 conv     64       1 x 1/ 1    192 x 192 x 128 ->  192 x 192 x  64 0.604 BF
  15 conv     64       1 x 1/ 1    192 x 192 x  64 ->  192 x 192 x  64 0.302 BF
  16 conv     64       3 x 3/ 1    192 x 192 x  64 ->  192 x 192 x  64 2.718 BF
  17 Shortcut Layer: 14,  wt = 0, wn = 0, outputs: 192 x 192 x  64 0.002 BF
  18 conv     64       1 x 1/ 1    192 x 192 x  64 ->  192 x 192 x  64 0.302 BF
  19 conv     64       3 x 3/ 1    192 x 192 x  64 ->  192 x 192 x  64 2.718 BF
  20 Shortcut Layer: 17,  wt = 0, wn = 0, outputs: 192 x 192 x  64 0.002 BF
  21 conv     64       1 x 1/ 1    192 x 192 x  64 ->  192 x 192 x  64 0.302 BF
  22 route  21 12                                  ->  192 x 192 x 128
  23 conv    128       1 x 1/ 1    192 x 192 x 128 ->  192 x 192 x 128 1.208 BF
  24 conv    256       3 x 3/ 2    192 x 192 x 128 ->   96 x  96 x 256 5.436 BF
  25 conv    128       1 x 1/ 1     96 x  96 x 256 ->   96 x  96 x 128 0.604 BF
  26 route  24                                     ->   96 x  96 x 256
  27 conv    128       1 x 1/ 1     96 x  96 x 256 ->   96 x  96 x 128 0.604 BF
  28 conv    128       1 x 1/ 1     96 x  96 x 128 ->   96 x  96 x 128 0.302 BF
  29 conv    128       3 x 3/ 1     96 x  96 x 128 ->   96 x  96 x 128 2.718 BF
  30 Shortcut Layer: 27,  wt = 0, wn = 0, outputs:  96 x  96 x 128 0.001 BF
  31 conv    128       1 x 1/ 1     96 x  96 x 128 ->   96 x  96 x 128 0.302 BF
  32 conv    128       3 x 3/ 1     96 x  96 x 128 ->   96 x  96 x 128 2.718 BF
  33 Shortcut Layer: 30,  wt = 0, wn = 0, outputs:  96 x  96 x 128 0.001 BF
  34 conv    128       1 x 1/ 1     96 x  96 x 128 ->   96 x  96 x 128 0.302 BF
  35 conv    128       3 x 3/ 1     96 x  96 x 128 ->   96 x  96 x 128 2.718 BF
  36 Shortcut Layer: 33,  wt = 0, wn = 0, outputs:  96 x  96 x 128 0.001 BF
  37 conv    128       1 x 1/ 1     96 x  96 x 128 ->   96 x  96 x 128 0.302 BF
  38 conv    128       3 x 3/ 1     96 x  96 x 128 ->   96 x  96 x 128 2.718 BF
  39 Shortcut Layer: 36,  wt = 0, wn = 0, outputs:  96 x  96 x 128 0.001 BF
  40 conv    128       1 x 1/ 1     96 x  96 x 128 ->   96 x  96 x 128 0.302 BF
  41 conv    128       3 x 3/ 1     96 x  96 x 128 ->   96 x  96 x 128 2.718 BF
  42 Shortcut Layer: 39,  wt = 0, wn = 0, outputs:  96 x  96 x 128 0.001 BF
  43 conv    128       1 x 1/ 1     96 x  96 x 128 ->   96 x  96 x 128 0.302 BF
  44 conv    128       3 x 3/ 1     96 x  96 x 128 ->   96 x  96 x 128 2.718 BF
  45 Shortcut Layer: 42,  wt = 0, wn = 0, outputs:  96 x  96 x 128 0.001 BF
  46 conv    128       1 x 1/ 1     96 x  96 x 128 ->   96 x  96 x 128 0.302 BF
  47 conv    128       3 x 3/ 1     96 x  96 x 128 ->   96 x  96 x 128 2.718 BF
  48 Shortcut Layer: 45,  wt = 0, wn = 0, outputs:  96 x  96 x 128 0.001 BF
  49 conv    128       1 x 1/ 1     96 x  96 x 128 ->   96 x  96 x 128 0.302 BF
  50 conv    128       3 x 3/ 1     96 x  96 x 128 ->   96 x  96 x 128 2.718 BF
  51 Shortcut Layer: 48,  wt = 0, wn = 0, outputs:  96 x  96 x 128 0.001 BF
  52 conv    128       1 x 1/ 1     96 x  96 x 128 ->   96 x  96 x 128 0.302 BF
  53 route  52 25                                  ->   96 x  96 x 256
  54 conv    256       1 x 1/ 1     96 x  96 x 256 ->   96 x  96 x 256 1.208 BF
  55 conv    512       3 x 3/ 2     96 x  96 x 256 ->   48 x  48 x 512 5.436 BF
  56 conv    256       1 x 1/ 1     48 x  48 x 512 ->   48 x  48 x 256 0.604 BF
  57 route  55                                     ->   48 x  48 x 512
  58 conv    256       1 x 1/ 1     48 x  48 x 512 ->   48 x  48 x 256 0.604 BF
  59 conv    256       1 x 1/ 1     48 x  48 x 256 ->   48 x  48 x 256 0.302 BF
  60 conv    256       3 x 3/ 1     48 x  48 x 256 ->   48 x  48 x 256 2.718 BF
  61 Shortcut Layer: 58,  wt = 0, wn = 0, outputs:  48 x  48 x 256 0.001 BF
  62 conv    256       1 x 1/ 1     48 x  48 x 256 ->   48 x  48 x 256 0.302 BF
  63 conv    256       3 x 3/ 1     48 x  48 x 256 ->   48 x  48 x 256 2.718 BF
  64 Shortcut Layer: 61,  wt = 0, wn = 0, outputs:  48 x  48 x 256 0.001 BF
  65 conv    256       1 x 1/ 1     48 x  48 x 256 ->   48 x  48 x 256 0.302 BF
  66 conv    256       3 x 3/ 1     48 x  48 x 256 ->   48 x  48 x 256 2.718 BF
  67 Shortcut Layer: 64,  wt = 0, wn = 0, outputs:  48 x  48 x 256 0.001 BF
  68 conv    256       1 x 1/ 1     48 x  48 x 256 ->   48 x  48 x 256 0.302 BF
  69 conv    256       3 x 3/ 1     48 x  48 x 256 ->   48 x  48 x 256 2.718 BF
  70 Shortcut Layer: 67,  wt = 0, wn = 0, outputs:  48 x  48 x 256 0.001 BF
  71 conv    256       1 x 1/ 1     48 x  48 x 256 ->   48 x  48 x 256 0.302 BF
  72 conv    256       3 x 3/ 1     48 x  48 x 256 ->   48 x  48 x 256 2.718 BF
  73 Shortcut Layer: 70,  wt = 0, wn = 0, outputs:  48 x  48 x 256 0.001 BF
  74 conv    256       1 x 1/ 1     48 x  48 x 256 ->   48 x  48 x 256 0.302 BF
  75 conv    256       3 x 3/ 1     48 x  48 x 256 ->   48 x  48 x 256 2.718 BF
  76 Shortcut Layer: 73,  wt = 0, wn = 0, outputs:  48 x  48 x 256 0.001 BF
  77 conv    256       1 x 1/ 1     48 x  48 x 256 ->   48 x  48 x 256 0.302 BF
  78 conv    256       3 x 3/ 1     48 x  48 x 256 ->   48 x  48 x 256 2.718 BF
  79 Shortcut Layer: 76,  wt = 0, wn = 0, outputs:  48 x  48 x 256 0.001 BF
  80 conv    256       1 x 1/ 1     48 x  48 x 256 ->   48 x  48 x 256 0.302 BF
  81 conv    256       3 x 3/ 1     48 x  48 x 256 ->   48 x  48 x 256 2.718 BF
  82 Shortcut Layer: 79,  wt = 0, wn = 0, outputs:  48 x  48 x 256 0.001 BF
  83 conv    256       1 x 1/ 1     48 x  48 x 256 ->   48 x  48 x 256 0.302 BF
  84 route  83 56                                  ->   48 x  48 x 512
  85 conv    512       1 x 1/ 1     48 x  48 x 512 ->   48 x  48 x 512 1.208 BF
  86 conv   1024       3 x 3/ 2     48 x  48 x 512 ->   24 x  24 x1024 5.436 BF
  87 conv    512       1 x 1/ 1     24 x  24 x1024 ->   24 x  24 x 512 0.604 BF
  88 route  86                                     ->   24 x  24 x1024
  89 conv    512       1 x 1/ 1     24 x  24 x1024 ->   24 x  24 x 512 0.604 BF
  90 conv    512       1 x 1/ 1     24 x  24 x 512 ->   24 x  24 x 512 0.302 BF
  91 conv    512       3 x 3/ 1     24 x  24 x 512 ->   24 x  24 x 512 2.718 BF
  92 Shortcut Layer: 89,  wt = 0, wn = 0, outputs:  24 x  24 x 512 0.000 BF
  93 conv    512       1 x 1/ 1     24 x  24 x 512 ->   24 x  24 x 512 0.302 BF
  94 conv    512       3 x 3/ 1     24 x  24 x 512 ->   24 x  24 x 512 2.718 BF
  95 Shortcut Layer: 92,  wt = 0, wn = 0, outputs:  24 x  24 x 512 0.000 BF
  96 conv    512       1 x 1/ 1     24 x  24 x 512 ->   24 x  24 x 512 0.302 BF
  97 conv    512       3 x 3/ 1     24 x  24 x 512 ->   24 x  24 x 512 2.718 BF
  98 Shortcut Layer: 95,  wt = 0, wn = 0, outputs:  24 x  24 x 512 0.000 BF
  99 conv    512       1 x 1/ 1     24 x  24 x 512 ->   24 x  24 x 512 0.302 BF
 100 conv    512       3 x 3/ 1     24 x  24 x 512 ->   24 x  24 x 512 2.718 BF
 101 Shortcut Layer: 98,  wt = 0, wn = 0, outputs:  24 x  24 x 512 0.000 BF
 102 conv    512       1 x 1/ 1     24 x  24 x 512 ->   24 x  24 x 512 0.302 BF
 103 route  102 87                                 ->   24 x  24 x1024
 104 conv   1024       1 x 1/ 1     24 x  24 x1024 ->   24 x  24 x1024 1.208 BF
 105 conv    512       1 x 1/ 1     24 x  24 x1024 ->   24 x  24 x 512 0.604 BF
 106 conv   1024       3 x 3/ 1     24 x  24 x 512 ->   24 x  24 x1024 5.436 BF
 107 conv    512       1 x 1/ 1     24 x  24 x1024 ->   24 x  24 x 512 0.604 BF
 108 max                5x 5/ 1     24 x  24 x 512 ->   24 x  24 x 512 0.007 BF
 109 route  107                                            ->   24 x  24 x 512
 110 max                9x 9/ 1     24 x  24 x 512 ->   24 x  24 x 512 0.024 BF
 111 route  107                                            ->   24 x  24 x 512
 112 max               13x13/ 1     24 x  24 x 512 ->   24 x  24 x 512 0.050 BF
 113 route  112 110 108 107                        ->   24 x  24 x2048
 114 conv    512       1 x 1/ 1     24 x  24 x2048 ->   24 x  24 x 512 1.208 BF
 115 conv   1024       3 x 3/ 1     24 x  24 x 512 ->   24 x  24 x1024 5.436 BF
 116 conv    512       1 x 1/ 1     24 x  24 x1024 ->   24 x  24 x 512 0.604 BF
 117 conv    256       1 x 1/ 1     24 x  24 x 512 ->   24 x  24 x 256 0.151 BF
 118 upsample                 2x    24 x  24 x 256 ->   48 x  48 x 256
 119 route  85                                     ->   48 x  48 x 512
 120 conv    256       1 x 1/ 1     48 x  48 x 512 ->   48 x  48 x 256 0.604 BF
 121 route  120 118                                ->   48 x  48 x 512
 122 conv    256       1 x 1/ 1     48 x  48 x 512 ->   48 x  48 x 256 0.604 BF
 123 conv    512       3 x 3/ 1     48 x  48 x 256 ->   48 x  48 x 512 5.436 BF
 124 conv    256       1 x 1/ 1     48 x  48 x 512 ->   48 x  48 x 256 0.604 BF
 125 conv    512       3 x 3/ 1     48 x  48 x 256 ->   48 x  48 x 512 5.436 BF
 126 conv    256       1 x 1/ 1     48 x  48 x 512 ->   48 x  48 x 256 0.604 BF
 127 conv    128       1 x 1/ 1     48 x  48 x 256 ->   48 x  48 x 128 0.151 BF
 128 upsample                 4x    48 x  48 x 128 ->  192 x 192 x 128
 129 route  23                                     ->  192 x 192 x 128
 130 conv    128       1 x 1/ 1    192 x 192 x 128 ->  192 x 192 x 128 1.208 BF
 131 route  130 128                                ->  192 x 192 x 256
 132 conv    128       1 x 1/ 1    192 x 192 x 256 ->  192 x 192 x 128 2.416 BF
 133 conv    256       3 x 3/ 1    192 x 192 x 128 ->  192 x 192 x 256 21.743 BF
 134 conv    128       1 x 1/ 1    192 x 192 x 256 ->  192 x 192 x 128 2.416 BF
 135 conv    256       3 x 3/ 1    192 x 192 x 128 ->  192 x 192 x 256 21.743 BF
 136 conv    128       1 x 1/ 1    192 x 192 x 256 ->  192 x 192 x 128 2.416 BF
 137 conv    256       3 x 3/ 1    192 x 192 x 128 ->  192 x 192 x 256 21.743 BF
 138 conv     18       1 x 1/ 1    192 x 192 x 256 ->  192 x 192 x  18 0.340 BF
 139 yolo
[yolo] params: iou loss: ciou (4), iou_norm: 0.07, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.20
nms_kind: greedynms (1), beta = 0.600000
 140 route  136                                            ->  192 x 192 x 128
 141 conv    256       3 x 3/ 4    192 x 192 x 128 ->   48 x  48 x 256 1.359 BF
 142 route  141 126                                ->   48 x  48 x 512
 143 conv    256       1 x 1/ 1     48 x  48 x 512 ->   48 x  48 x 256 0.604 BF
 144 conv    512       3 x 3/ 1     48 x  48 x 256 ->   48 x  48 x 512 5.436 BF
 145 conv    256       1 x 1/ 1     48 x  48 x 512 ->   48 x  48 x 256 0.604 BF
 146 conv    512       3 x 3/ 1     48 x  48 x 256 ->   48 x  48 x 512 5.436 BF
 147 conv    256       1 x 1/ 1     48 x  48 x 512 ->   48 x  48 x 256 0.604 BF
 148 conv    512       3 x 3/ 1     48 x  48 x 256 ->   48 x  48 x 512 5.436 BF
 149 conv     18       1 x 1/ 1     48 x  48 x 512 ->   48 x  48 x  18 0.042 BF
 150 yolo
[yolo] params: iou loss: ciou (4), iou_norm: 0.07, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.10
nms_kind: greedynms (1), beta = 0.600000
 151 route  147                                            ->   48 x  48 x 256
 152 conv    512       3 x 3/ 2     48 x  48 x 256 ->   24 x  24 x 512 1.359 BF
 153 route  152 116                                ->   24 x  24 x1024
 154 conv    512       1 x 1/ 1     24 x  24 x1024 ->   24 x  24 x 512 0.604 BF
 155 conv   1024       3 x 3/ 1     24 x  24 x 512 ->   24 x  24 x1024 5.436 BF
 156 conv    512       1 x 1/ 1     24 x  24 x1024 ->   24 x  24 x 512 0.604 BF
 157 conv   1024       3 x 3/ 1     24 x  24 x 512 ->   24 x  24 x1024 5.436 BF
 158 conv    512       1 x 1/ 1     24 x  24 x1024 ->   24 x  24 x 512 0.604 BF
 159 conv   1024       3 x 3/ 1     24 x  24 x 512 ->   24 x  24 x1024 5.436 BF
 160 conv     18       1 x 1/ 1     24 x  24 x1024 ->   24 x  24 x  18 0.021 BF
 161 yolo
[yolo] params: iou loss: ciou (4), iou_norm: 0.07, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.05
nms_kind: greedynms (1), beta = 0.600000
Total BFLOPS 258.225
avg_outputs = 1995847
 Allocate additional workspace_size = 259.52 MB
Loading weights from backup\yolo-obj_last.weights...
 seen 64, trained: 115 K-images (1 Kilo-batches_64)
Done! Loaded 162 layers from weights-file
Learning Rate: 0.001, Momentum: 0.949, Decay: 0.0005
 Detection layer: 139 - type = 28
 Detection layer: 150 - type = 28
 Detection layer: 161 - type = 28
 If error occurs - run training with flag: -dont_show
Resizing, random_coef = 1.40

 1120 x 1120
 Create 6 permanent cpu-threads
 try to allocate additional workspace_size = 482.39 MB
 CUDA allocate done!
Loaded: 4.085000 seconds

 1088 x 1088
 try to allocate additional workspace_size = 455.25 MB
 CUDA allocate done!
```

It starts executing but then randomly at any iteration it throws the error / no error:

```
1830: 1.344411, 1.350044 avg loss, 0.001000 rate, 9.374000 seconds, 117120 images, 18.426719 hours left
Resizing, random_coef = 1.40

 1088 x 1088
 try to allocate additional workspace_size = 455.25 MB
 CUDA allocate done!
Loaded: 1.339000 seconds - performance bottleneck on CPU or Disk HDD/SSD
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.614526), count: 6, class_loss = 2.218373, iou_loss = 114.688530, total_loss = 116.906906
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000434, iou_loss = 0.000000, total_loss = 0.000434
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12769, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.000000), count: 1, class_loss = 0.000039, iou_loss = 0.000000, total_loss = 0.000039
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12769, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.000000), count: 1, class_loss = 0.143183, iou_loss = 0.000000, total_loss = 0.143183
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12769, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.554494), count: 4, class_loss = 0.624861, iou_loss = 74.261322, total_loss = 74.886185
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12773, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.385929), count: 8, class_loss = 3.477727, iou_loss = 57.571472, total_loss = 61.049198
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.660152), count: 2, class_loss = 1.085335, iou_loss = 9.604399, total_loss = 10.689734
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12783, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.717729), count: 3, class_loss = 0.825437, iou_loss = 55.373161, total_loss = 56.198597
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12786, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.456257), count: 1, class_loss = 0.642659, iou_loss = 21.443045, total_loss = 22.085703
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12787, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.555001), count: 5, class_loss = 1.674222, iou_loss = 113.544067, total_loss = 115.218292
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12792, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.683467), count: 8, class_loss = 2.438021, iou_loss = 189.249954, total_loss = 191.687973
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12800, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.707879), count: 6, class_loss = 2.378169, iou_loss = 124.877296, total_loss = 127.255463
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12806, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.000000), count: 1, class_loss = 0.000173, iou_loss = 0.000000, total_loss = 0.000173
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12806, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.353368), count: 2, class_loss = 0.167852, iou_loss = 29.870682, total_loss = 30.038534
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12808, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.603256), count: 2, class_loss = 0.827219, iou_loss = 49.814388, total_loss = 50.641609
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12810, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.740545), count: 7, class_loss = 2.055195, iou_loss = 134.992401, total_loss = 137.047592
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000016, iou_loss = 0.000000, total_loss = 0.000016
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12817, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.733161), count: 20, class_loss = 7.096892, iou_loss = 466.078033, total_loss = 473.174927
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000001, iou_loss = 0.000000, total_loss = 0.000001
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12837, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.544502), count: 7, class_loss = 2.548342, iou_loss = 141.112885, total_loss = 143.661224
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.000015, iou_loss = 0.000000, total_loss = 0.000015
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12844, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.662587), count: 39, class_loss = 13.634548, iou_loss = 798.510986, total_loss = 812.145508
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.000000), count: 1, class_loss = 0.005219, iou_loss = 0.000000, total_loss = 0.005219
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12883, rewritten_bbox = 0.000000 %
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.730384), count: 30, class_loss = 7.274044, iou_loss = 630.657532, total_loss = 637.931580
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 150 Avg (IOU: 0.401008), count: 2, class_loss = 1.025823, iou_loss = 3.258185, total_loss = 4.284009
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 161 Avg (IOU: 0.000000), count: 1, class_loss = 0.000000, iou_loss = 0.000000, total_loss = 0.000000
 total_bbox = 12915, rewritten_bbox = 0.000000 %
CUDA status Error: file: d:\repos\darknet\src\dark_cuda.c : cuda_push_array() : line: 589 : build time: Aug 12 2021 - 08:56:28

 CUDA Error: an illegal memory access was encountered
Darknet error location: d:\repos\darknet\src\dark_cuda.c, check_error, line #70
CUDA Error: an illegal memory access was encountered: No error
```

I am not sure whether it is the same since the illegal memory access encountered is: No error in my case. But I am willing to test whatever you propose to help solve the issue!

Thank you,

**Comment by AlexeyAB** [comment]
@ugogalassi 

> I use Cuda 10.1.
> It crashes during mAP calculation.
> Increasing subdivision the error doesn't occur. [i.e., subdivision=4]

It seems there is just `Out of GPU memory` error, which is displayed incorrectly, like `an illegal memory access was encountered`. Just use a higher subdivision.

**Comment by AlexeyAB** [comment]
@Sisetus 

> I am also facing a similar problem with CUDA 11.1, GTX 3090, Windows 10:
> batch=64
> subdivisions=32

Do you get this error if you use `subdivisions=64` ?

**Comment by Sisetus** [comment]
Hi @AlexeyAB , 

Thanks for the quick answer. 

Unfortunately, I've just tried the subdivisions=64 and it did not work. Same error.

I was monitoring the GPU memory usage, it used around 12 out of the 24 GB available, when it crashed.

In fact, the execution halts with the:
```
 total_bbox = 24879, rewritten_bbox = 0.000000 %
CUDA status Error: file: d:\repos\darknet\src\dark_cuda.c : cuda_push_array() : line: 589 : build time: Aug 12 2021 - 08:56:28

CUDA Error: an illegal memory access was encountered
```

Then when I press the ctrl+c to stop execution it prints the rest:

```
Darknet error location: d:\repos\darknet\src\dark_cuda.c, check_error, line #70
CUDA Error: an illegal memory access was encountered: No error
^C
```

**Comment by AlexeyAB** [comment]
@Sisetus 
* It would be great if you can try CUDA 10.2 or  11.0 instead of CUDA 11.1, just to check where is the issue.
* What way did you use for training, is it: vcpkg, Cmake or Legacy way (fixing darknet.sln manually)?

**Comment by Sisetus** [comment]
@AlexeyAB ,

Thanks as always!

I will try to change CUDA version, no problem. 

I used the CMake approach with Visual Studio 2017.

I will let you know as soon as I get the results, in the meantime if you have any idea/comment let me know!

**Comment by JeremyKeusters** [comment]
@AlexeyAB I also [replied](https://github.com/AlexeyAB/darknet/issues/4655#issuecomment-882693344) some time ago in issue #4655 , which is about the same error/issue. My information there might help too?

**Comment by AlexeyAB** [comment]
@JeremyKeusters 

>CUDA-version: 10010 (10010), cuDNN: 7.6.5, GPU count: 1  
> OpenCV version: 4.9.1
>mini_batch = 32, batch = 64, time_steps = 1, train = 1 
>As I already said, when I set the subdivisions to 4, the issue disappears.

* Do you use CUDA 10.1?
* There is no issue if you use high `subdivisions=4` or higher, or if you don't use `-map` flag?

**Comment by Sisetus** [comment]
@AlexeyAB ,

I tried to change CUDA version but my gtx 3090 is not compatible with previous versions of CUDA (11.1 was the one introducing compatibilty with them). 

So I decided to try the CUDA 11.4 but same error.

**Comment by AlexeyAB** [comment]
@Sisetus It seems that CUDA 11.0 supports RTX 3090 and doesn't have this issue. 
Can you try `CUDA 11.0`? With for example `Download cuDNN v8.1.1 (Feburary 26th, 2021), for CUDA 11.0,11.1 and 11.2` https://developer.nvidia.com/rdp/cudnn-archive

**Comment by Sisetus** [comment]
@AlexeyAB ,

I found that CUDA 11.0 does not support RTX 3090 (it supports some A.. but no the RTX 3000 series, https://en.wikipedia.org/wiki/CUDA ). I tried it anyway but there is an error during the cmake which basically says that CUDA 11.0 does not support architechture 8.6.

Any other test that I might perform?

Thanks,

**Comment by Pratyush-DS** [comment]
> > Oh, sorry. I forgot to give feedback again.
> > @tamim662: Changing the subdivisions from 1 to 8 actually fixed it for me - for whatever reason.
> 
> I already assign subdivision to 16. But it didn't solve the issue.

same for me

**Comment by Pratyush-DS** [comment]
> @ugogalassi
> 
> > I use Cuda 10.1.
> > It crashes during mAP calculation.
> > Increasing subdivision the error doesn't occur. [i.e., subdivision=4]
> 
> It seems there is just `Out of GPU memory` error, which is displayed incorrectly, like `an illegal memory access was encountered`. Just use a higher subdivision.

I tried subdivision to 128, 64,32 and reduced batch size to 8 but not working giving the same issue

**Comment by Pratyush-DS** [comment]
@Sisetus 
Have you figured out something ?

**Comment by ugogalassi** [comment]
> @ugogalassi
> 
> > I use Cuda 10.1.
> > It crashes during mAP calculation.
> > Increasing subdivision the error doesn't occur. [i.e., subdivision=4]
> 
> It seems there is just `Out of GPU memory` error, which is displayed incorrectly, like `an illegal memory access was encountered`. Just use a higher subdivision.

Hi @AlexeyAB , thanks for the reply. And sorry for the delay with which I reply to thank you!

**Comment by Sisetus** [comment]
@Pratyush-DS , up to this moment I have not figure it out yet. I am trying to change my RTX 3090 for a new one but it will take some time.
I ended up thinking that it might be some hardware issue because I was also using Keras and TensorFlow and in both frameworks I had similar problems. I do not know whether it is hardware or maybe some driver issue.

**Comment by hjedamski97** [comment]
Hi @AlexeyAB , 

I've got a similar Error like Sisetus during training.

My first log-file-lines:
<img width="308" alt="layers_frozen" src="https://user-images.githubusercontent.com/97537748/179190011-4fa25135-b44d-48ec-a22f-fdf2cb35d449.PNG">

Then..
<img width="943" alt="error" src="https://user-images.githubusercontent.com/97537748/179190313-fcba7d06-4f45-4f90-adb2-d9386e81c39c.PNG">

My yolov4-custom.cfg-changes:
<img width="129" alt="params" src="https://user-images.githubusercontent.com/97537748/179191303-43cdc3cd-5dd1-4d02-9c00-a5398cffd7f9.PNG">

<img width="529" alt="stopbackward" src="https://user-images.githubusercontent.com/97537748/179191331-77d935dd-a4cb-4e1e-831d-c0156c586bff.PNG">

<img width="527" alt="head-3" src="https://user-images.githubusercontent.com/97537748/179195722-6111c68e-ccc2-430d-85fe-33585e1d212c.PNG">

My Makefile-changes:
<img width="657" alt="MakefileP100" src="https://user-images.githubusercontent.com/97537748/179191428-0894cb9c-b4d5-44c5-81dd-62a559dff4f5.PNG">

nvidia-smi:
<img width="441" alt="nvidia-smi" src="https://user-images.githubusercontent.com/97537748/179191561-e3caef7e-ea52-489c-8a58-de1fcf4dfa6c.PNG">

nvcc:
<img width="256" alt="nvcc" src="https://user-images.githubusercontent.com/97537748/179191634-e34e4686-a96c-4806-acad-9d58a4a1aa22.PNG">

My Training-command:
./darknet detector train ./data/../obj.data  ./data/../cfg/yolo-finetuning.cfg  ./data/../models/mybestweights.conv.137 -dont_show -map -clear > ./data/../logs/logfile.log

When i remove stopbackward=1 in Layer 136 all works fine.

I already try to put stopbackward into Layer 135 etc.
Training without -map flag didn't work.

cuda-version: 11.7
cudNN-version: 8.4.1.50

I'm confused and hope you can help me. 

Thanks a lot.

**Comment by tamim662** [comment]
> Hi @AlexeyAB ,
> 
> I've got a similar Error like Sisetus during training.
> 
> My first log-file-lines: <img alt="layers_frozen" width="308" src="https://user-images.githubusercontent.com/97537748/179190011-4fa25135-b44d-48ec-a22f-fdf2cb35d449.PNG">
> 
> then.. <img alt="error" width="1323" src="https://user-images.githubusercontent.com/97537748/179198421-2a7e1571-dbbe-417d-98f8-f19faa8e2f23.PNG">
> 
> My yolov4-custom.cfg-changes:
> 
> <img alt="params" width="129" src="https://user-images.githubusercontent.com/97537748/179191303-43cdc3cd-5dd1-4d02-9c00-a5398cffd7f9.PNG">
> 
> 
> <img alt="stopbackward" width="529" src="https://user-images.githubusercontent.com/97537748/179191331-77d935dd-a4cb-4e1e-831d-c0156c586bff.PNG">
> 
> 
> <img alt="head-3" width="527" src="https://user-images.githubusercontent.com/97537748/179195722-6111c68e-ccc2-430d-85fe-33585e1d212c.PNG">
> 
> makefile-changes: <img alt="MakefileP100" width="657" src="https://user-images.githubusercontent.com/97537748/179191428-0894cb9c-b4d5-44c5-81dd-62a559dff4f5.PNG">
> 
> nvidia-smi: <img alt="nvidia-smi" width="441" src="https://user-images.githubusercontent.com/97537748/179191561-e3caef7e-ea52-489c-8a58-de1fcf4dfa6c.PNG">
> 
> nvcc: <img alt="nvcc" width="256" src="https://user-images.githubusercontent.com/97537748/179191634-e34e4686-a96c-4806-acad-9d58a4a1aa22.PNG">
> 
> My Training-command: ./darknet detector train ./data/../obj.data ./data/../cfg/yolo-finetuning.cfg ./data/../models/mybestweights.conv.137 -dont_show -map -clear > ./data/../logs/logfile.log
> 
> When i remove stopbackward=1 in Layer 136 all works fine.
> 
> I already tried to put stopbackward into Layer 135 etc. Training without -map flag didn't work.
> 
> And tried different subdivisions like 8/8 (First log-file lines), 16/8, 64/64
> 
> cuda-version: 11.7 cudNN-version: 8.4.1.50
> 
> I'm confused and hope you can help me to fine tune my model.
> 
> Thanks a lot.

@hjedamski97 Can you set subdivisions = 32 and try to train again and also skip -clear flag for now.

**Comment by tamim662** [comment]
Hi @hjedamski97 setting batch=64 and subdivisions=32 worked for me where I also skipped -map flag. However, I can suggest you to keep CUDNN_HALF=0 as it requires more memory. As you are training your model entirely on GPU. so you can keep AVX=0
OPENMP=0
LIBSO=0 as well. Then compile again by running 'make' command.
You can also decrease your height and width which should be multiplied by 32, like 416*416, 608*608. Another thing, don't keep the same value for batch and subdivisions as you did 64/64. Here, subdivisions work like a mini-batch, try to keep subdivisions value smaller than the batch.

**Comment by hjedamski97** [comment]
Next Try - Same Error:

<img width="243" alt="Makefile_edit" src="https://user-images.githubusercontent.com/97537748/179721979-e2bdf9d1-82c9-450c-b1f2-9d6fde9903db.PNG">

Train-cmd:
./darknet detector train ./data/../obj.data  ./data/../yolov4-freeze.cfg ./data/../yolov4-freeze.conv.137 -dont_show > ./../train.log


<img width="86" alt="cfg" src="https://user-images.githubusercontent.com/97537748/179722868-4b7754e5-093c-42df-a28b-39f38056e40a.PNG">

Error-Log:
<img width="464" alt="error-edit_log" src="https://user-images.githubusercontent.com/97537748/179722986-ce7c0b84-3650-49d4-a3d6-4a35d4f96d06.PNG">

Error-Train-pane (tmux):
<img width="261" alt="error-edit_" src="https://user-images.githubusercontent.com/97537748/179723566-ab73fb46-32c8-4b2d-9ed8-5fb7a73fdad9.PNG">

**Comment by tamim662** [comment]
@hjedamski97 Btw, my error location was in ./src/dark_cuda.c which is not same to you as it showed that your error location is in ./src/blas_kernels.cu(). So the "CUDA Error: an illegal memory access was encountered" may be happened for a different issue. But, yeah you can try older Cuda versions like 11.4, 11.0, or even 10.2.
