### ISSUE TITLE
CUDA status Error: file: ./src/dark_cuda.c : () : line: 39 : Darknet error location: ./src/dark_cuda.c, check_error, line #70 CUDA Error: unknown error: Bad file descriptor

### ISSUE THREAD

**Issue by Gancheekim** [AlexeyAB/darknet#8126]
![image](https://user-images.githubusercontent.com/55738449/135522511-d7fb8ed2-f2b8-4a1e-8ad9-bd8905095c2a.png)

gpu: rtx 2080 super
ubuntu: 20.04
cuda version: 11.0
nvidia driver version: 450.119.03
cudnn: 8.1.0

makefile: GPU = 1, CUDNN = 1.

i need help...
i tried everything i could and searched literally every possible solution on the internet, nothing solves the problem.
most important thing is that the error message were unknown.

for my own attempt, i checked the variable <gpu_index> locate in darknet.c,
turns out that gpu_index isn't equal to -1 or either 0, more like a 417654526 kind of random integer.

my guess is that darknet could locate/communicate with the gpu?

another guess is that in dark_cuda.c, line 38,
cudaError_t status = cudaSetDevice(n);
maybe cudaSetDevice(n) couldn't work? 
will it be that the current cuda installation caused the issue?

anyway, thanks for the assist in advance.

**Comment by Gancheekim** [comment]
problem solved.

my procedure:
1. reinstall cuda driver, cuda toolkit, cudnn
2.  make sure cuda/cudnn is compatible with your current OS system. (mine was Ubuntu 20.04, cuda-11.4, cuda driver: 470.57.02)
3.  make sure that every PATH in Makefile are changed according to your machine environment.
     Noted: here are the PATHs that may had to change: 
     -nvcc
     -GPU section's COMMON, LDFLAGS
     -cudnn section's CFLAGS, DFLAGS

that's it for me. Hope that anyone occurs same problem with me gets help!
