### ISSUE TITLE
Cudnn64_8.dll error on windows11, exception code: 0xc0000409

### ISSUE THREAD

**Issue by 1027663760** [AlexeyAB/darknet#8239]
CUDA-version: 11050 (11050), cuDNN: 8.3.0, CUDNN_HALF=1, GPU count: 1
 CUDNN_HALF=1
 OpenCV version: 4.5.4
yolov4-tiny_4l_spp
 0 : compute_capability = 860, cudnn_half = 1, GPU: NVIDIA GeForce RTX 3060
net.optimized_memory = 1
mini_batch = 64, batch = 64, time_steps = 1, train = 1
   layer   filters  size/strd(dil)      input                output
   0 Create CUDA-stream - 0
Could not load library cudnn_cnn_infer64_8.dll. Error code 126
Please make sure cudnn_cnn_infer64_8.dll is in your library path!
![1](https://user-images.githubusercontent.com/26378634/142217598-6a58527f-bb2f-4abb-87dd-7e7b1b66069c.png)

**Comment by cenit** [comment]
did you install cudnn completely? it looks like you missed some files

**Comment by 1027663760** [comment]
> did you install cudnn completely? it looks like you missed some files

I have compiled and used darknet for more than two years, it is impossible to make mistakes

**Comment by cenit** [comment]
newer cudnn versions are different than before. Besides cudnn64_8.dll there are other files to copy, maybe you missed them.
The program is complaining that cudnn_cnn_infer64_8.dll is missing...

**Comment by 1027663760** [comment]
> newer cudnn versions are different than before. Besides cudnn64_8.dll there are other files to copy, maybe you missed them. The program is complaining that cudnn_cnn_infer64_8.dll is missing...

I checked and all these files exist

**Comment by cenit** [comment]
https://stackoverflow.com/questions/69879188/could-not-load-library-cudnn-cnn-infer64-8-dll-error-code-126

looks like nvidia released a cudnn version with a bug
can you try to downgrade your cudnn to the one for cuda 11.4 like they did in the link above? it should work on cuda 11.5 too, and fix the error you encountered

**Comment by cenit** [comment]
did you fix your problem downgrading cudnn?

**Comment by 1027663760** [comment]
> did you fix your problem downgrading cudnn?

I solved it using an old version of cuda with cudnn
