### ISSUE TITLE
CUDA Error: out of memory

### ISSUE THREAD

**Issue by alxistn** [AlexeyAB/darknet#827]
When I use the darknet binary to do detection with my trained model it works fine.

However, when I use the python script to do detection, I get this cuda error: CUDA Error: out of memory

Any idea why ?

**Comment by AlexeyAB** [comment]
Set batch=1 subdivision=1 in cfg-file

**Comment by alxistn** [comment]
Works fine, thank you!

**Comment by off99555** [comment]
I got this error when training.
```
 69: 145.707611, 212.681839 avg, 0.000000 rate, 0.531940 seconds, 4416 images
Loaded: 0.000031 seconds
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.500528, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: 0.097596, Class: 0.621507, Obj: 0.535854, No Obj: 0.543657, .5R: 0.000000, .75R: 0.000000,  count: 6
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.501826, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: 0.242608, Class: 0.537878, Obj: 0.601022, No Obj: 0.544957, .5R: 0.142857, .75R: 0.000000,  count: 14

 70: 146.247314, 206.038391 avg, 0.000000 rate, 0.534524 seconds, 4480 images
Resizing
576 x 576
 try to allocate workspace = 1151467520 * sizeof(float),  CUDA allocate done!
Loaded: 0.000050 seconds
CUDA Error: out of memory
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)
```

**Comment by AlexeyAB** [comment]
@off99555 What GPU do you use?

**Comment by AlexeyAB** [comment]
@alxistn I fixed darknet.py example and darknet.so/dll library. So now you need not set batch=1 to use darknet.py

**Comment by off99555** [comment]
Tesla K80.
The default one on floydhub.

**Comment by off99555** [comment]
@AlexeyAB I still got error after changing `total_byte / 2` to `total_byte / 4`
And also changed `subdivision=2` to `subdivision=4`
```

 38: 47.643734, 55.805576 avg, 0.000000 rate, 0.534847 seconds, 2432 images
Loaded: 0.000038 seconds
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.451518, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.497480, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.450531, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.498075, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.450844, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.496216, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.451381, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.496725, .5R: -nan, .75R: -nan,  count: 0

 39: 47.470825, 54.972099 avg, 0.000000 rate, 0.535093 seconds, 2496 images
Loaded: 0.000044 seconds
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.450346, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.496879, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.453199, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.498045, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.452603, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.497221, .5R: -nan, .75R: -nan,  count: 0
Region 16 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.450346, .5R: -nan, .75R: -nan,  count: 0
Region 23 Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.497302, .5R: -nan, .75R: -nan,  count: 0

 40: 47.502693, 54.225159 avg, 0.000000 rate, 0.533520 seconds, 2560 images
Resizing
-32 x -32
OpenCV Error: Assertion failed (s >= 0) in setSize, file /root/opencv/modules/core/src/matrix.cpp, line 307
terminate called after throwing an instance of 'cv::Exception'
OpenCV Error: Assertion failed (s >= 0) in setSize, file /root/opencv/modules/core/src/matrix.cpp, line 307
terminate called recursively
Aborted (core dumped)
```

**Comment by AlexeyAB** [comment]
@off99555 I fixed it: https://github.com/AlexeyAB/darknet/commit/9ba0beb413d8b443376c36c1701a0dbce1e8d566

**Comment by AlexeyAB** [comment]
@leekwunfung817 It looks like your GPU has 1 or 2 GB GPU-RAM, GeForce GT 710: https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#GeForce_700_series

Try to set `width=288 height=288` in the [net]-section in your cfg-file.

**Comment by leekwunfung817** [comment]
My GPU is contain 5GB , maybe
![untitled](https://user-images.githubusercontent.com/18736700/44628208-062e6280-a96e-11e8-8fae-c60efca3665e.png)

set width=288 height=288 already
![untitled](https://user-images.githubusercontent.com/18736700/44628221-2a8a3f00-a96e-11e8-8d85-938524013e7f.png)

The result is the follow:
![untitled](https://user-images.githubusercontent.com/18736700/44628237-789f4280-a96e-11e8-9b37-5d918810a4b1.png)

**Comment by leekwunfung817** [comment]
When the command be executed, the GPU usage raise to the peak.
![untitled](https://user-images.githubusercontent.com/18736700/44628292-5e199900-a96f-11e8-89c4-cd6d72f98b28.png)

**Comment by AlexeyAB** [comment]
@leekwunfung817 
> My GPU is contain 5GB , maybe

It is wrong. GT 710 can't have more than 2 GB. Use GPU-Z utility to see GPU specifications: https://www.techpowerup.com/download/techpowerup-gpu-z/

> set width=288 height=288 already

You didn't set it. You set it in the other file, or didn't save it.

Also try to use `width=224 height=224`

**Comment by leekwunfung817** [comment]
Finally success when I set 200 height and width

I need to fine tune the size until the gpu memory are able to obtain the neural network.

**Comment by leekwunfung817** [comment]
Can detect any thing
height: 416
width: 416
![predictions](https://user-images.githubusercontent.com/18736700/44633997-c8f5bf00-a9c5-11e8-9bcd-7278bfaed92a.jpg)


Can detect any thing
height: 224
width: 224
![predictions](https://user-images.githubusercontent.com/18736700/44634006-e7f45100-a9c5-11e8-9f31-463abc8b7b7c.jpg)


Cannot detect any thing
height: 200
width: 200
![predictions](https://user-images.githubusercontent.com/18736700/44634012-065a4c80-a9c6-11e8-9d9a-792752219dc4.jpg)

**Comment by PeterQuinn925** [comment]
I think the height/width must be divisible by 32 to work.

**Comment by AlexeyAB** [comment]
@leekwunfung817 
https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> increase network resolution in your .cfg-file (height=608, width=608 or **any value multiple of 32**) - it will increase precision

**Comment by leekwunfung817** [comment]
Can detect but not accurate.
height: 96
width: 96
![predictions](https://user-images.githubusercontent.com/18736700/44634120-afee0d80-a9c7-11e8-9215-9c1dbf455e26.jpg)

Cannot detect anything **under or equal (32*2)=(64)**
width=64
height=64
![predictions](https://user-images.githubusercontent.com/18736700/44634129-e88de700-a9c7-11e8-8818-5fa51d8746b3.jpg)

**Comment by AlexeyAB** [comment]
@leekwunfung817 

> Cannot detect anything under or equal (32*2)=(64)
> width=64
> height=64


1. The general rule is broken: 
    `train_network_width * train_obj_width / train_image_width ~= detection_network_width * detection_obj_width / detection_image_width`

    For example, for dog: `416 * 196 / 768 != 64 * 196 / 768` because `106 != 16`

https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> General rule - your training dataset should include such a set of relative sizes of objects that you want to detect:
> 
> `train_network_width * train_obj_width / train_image_width ~= detection_network_width * detection_obj_width / detection_image_width`
> `train_network_height * train_obj_height / train_image_height ~= detection_network_height * detection_obj_height / detection_image_height`


2. Also, if you want to know how neural network sees it - it was not trained (on MSCOCO) to detect so small: dog, car and bicycle:

![44634129-e88de700-a9c7-11e8-8818-5fa51d8746b3](https://user-images.githubusercontent.com/4096485/44634301-a1403000-a9a0-11e8-8275-99c6c5695c79.png)
