### ISSUE TITLE
undefined reference 

### ISSUE THREAD

**Issue by jiyoungAn** [AlexeyAB/darknet#8558]
![image](https://user-images.githubusercontent.com/31766812/173754323-585ad492-e696-41e4-9165-fc663eacc712.png)

```
/usr/bin/ld: /usr/local/cuda-11.7/lib64/libcublas.so: undefined reference to `cublasLtGetStatusString@libcublasLt.so.11'
/usr/bin/ld: /usr/local/cuda-11.7/lib64/libcublas.so: undefined reference to `cublasLtGetStatusName@libcublasLt.so.11'
collect2: error: ld returned 1 exit status
```

Current cuda version is 11.7 and I don't understand why I have this error.
I checked In /usr/local/cuda-11.7/lib64/ folder, there are both libcublas.so and libcublas.so.11
Following is my Makefile configuration.

GPU=1
CUDNN=1
CUDNN_HALF=1
OPENCV=0
AVX=0
OPENMP=0
LIBSO=0
ZED_CAMERA=0
ZED_CAMERA_v2_8=0

Thank you for your help

**Comment by jiyoungAn** [comment]
Issue solved with the following commands

`sudo ln -s /usr/local/cuda-11.7/lib64/libcublasLt.so.11 /usr/local/cuda-11.7/lib64/libcublasLt.so.11`
