### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by Newtog** [AlexeyAB/darknet#893]
used slow CUDNN algo without Workspace!
 CUDNN-slow  used slow CUDNN algo without Workspace!
 CUDNN-slow  used slow CUDNN algo without Workspace!
 CUDNN-slow  try to allocate workspace = 1107853312 * sizeof(float), CUDA Error: out of memory

I am using p2.8xlarge instance

**Comment by AlexeyAB** [comment]
What batch and subdivision do you use in cfg-file?

**Comment by Newtog** [comment]
Now it is working I changes the batch size from 1 to 64 and subdivision to 16 but it makes the training slow

**Comment by AlexeyAB** [comment]
@Newtog Messages on the screen goes slower, but training goes faster )

**Comment by Newtog** [comment]
Ohh so print is only slower ??

**Comment by Newtog** [comment]
why we choose multi gpu mode after 1000 iteration and not before that??

**Comment by Newtog** [comment]
And the calculation is appearing that is IOU, tp,fp ,recall is for classes of all frames or for each frame seperately??  And can we get these number while performing for testing?
